// Runs after `vite build`. Everything a static Apache host needs that a static
// page cannot set itself: per-page CSP, security and cache headers, the sitemap.
//
//   dist/client/.htaccess     Apache (GoDaddy shared hosting)
//   dist/client/_headers      Netlify / Cloudflare Pages
//   dist/client/sitemap.xml
//   dist/headers.json         the same policies, for scripts/serve.ts and the tests
import { existsSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { join, relative, sep } from 'node:path'
import { absolute, LOCALES, PAGES, pageUrl } from '../src/i18n/locales.ts'
import { COMMON_HEADERS, type HeaderMap, inlineBlocks, pageCsp } from './csp.ts'

const ROOT = join(import.meta.dir, '..')
const CLIENT = join(ROOT, 'dist', 'client')
const MESSAGES = join(ROOT, 'src', 'i18n', 'messages')
const ENGLISH = LOCALES[0]

const problems: string[] = []

function htmlFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name)
    if (statSync(path).isDirectory())
      return name === 'assets' || name === '__tsr' ? [] : htmlFiles(path)
    return name.endsWith('.html') ? [path] : []
  })
}

/** dist/client/ar/index.html → /ar/, dist/client/404.html → /404.html */
function urlPath(file: string): string {
  const rel = relative(CLIENT, file).split(sep).join('/')
  return `/${rel.replace(/(^|\/)index\.html$/, '$1')}`
}

function policies(): HeaderMap {
  const pages: Record<string, string> = {}
  for (const file of htmlFiles(CLIENT)) {
    const html = readFileSync(file, 'utf8')
    const path = urlPath(file)
    if (/<[a-z][^>]*\sstyle="/i.test(html))
      problems.push(`${path}: a style attribute the CSP blocks`)
    pages[path] = pageCsp(inlineBlocks(html))
  }
  const fallback = pages['/404.html']
  if (!fallback) throw new Error('dist/client/404.html is missing')
  return { pages, fallback }
}

function sitemap(): string {
  const urls = Object.values(PAGES).flatMap((page) =>
    LOCALES.map((locale) => {
      const links = [
        ...LOCALES.map(
          (each) =>
            `    <xhtml:link rel="alternate" hreflang="${each.hreflang}" href="${absolute(pageUrl(each, page.path))}" />`,
        ),
        `    <xhtml:link rel="alternate" hreflang="x-default" href="${absolute(pageUrl(ENGLISH ?? locale, page.path))}" />`,
      ]
      return `  <url>\n    <loc>${absolute(pageUrl(locale, page.path))}</loc>\n${links.join('\n')}\n  </url>`
    }),
  )
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urls.join('\n')}
</urlset>
`
}

function quoted(value: string): string {
  return `"${value.replaceAll('"', '\\"')}"`
}

/** A page is also reachable as its index.html, so both spellings get its policy. */
function spellings(path: string): string[] {
  return path.endsWith('/') ? [path, `${path}index.html`] : [path]
}

function htaccess({ pages, fallback }: HeaderMap): string {
  const common = Object.entries(COMMON_HEADERS)
    .map(([name, value]) => {
      const onlyHttps = name === 'Strict-Transport-Security' ? ' env=HTTPS' : ''
      return `  Header always set ${name} ${quoted(value)}${onlyHttps}`
    })
    .join('\n')
  // <If> sections are merged after the main context, so a page's policy
  // replaces the fallback, which covers 404s and anything unlisted.
  const perPage = Object.entries(pages)
    .filter(([path]) => path !== '/404.html')
    .map(([path, policy]) => {
      const list = spellings(path)
        .map((each) => `'${each}'`)
        .join(', ')
      return `  <If "%{REQUEST_URI} -in {${list}}">\n    Header always set Content-Security-Policy ${quoted(policy)}\n  </If>`
    })
    .join('\n')
  return `# Generated by scripts/postbuild.ts: edit there, not here. See HOSTING.md.
ErrorDocument 404 /404.html
AddType application/manifest+json .webmanifest
AddType font/woff2 .woff2
AddDefaultCharset utf-8

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTPS} off
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>

<IfModule mod_headers.c>
${common}
  Header always set Content-Security-Policy ${quoted(fallback)}
${perPage}

  # Vite names bundled assets with a content hash, so they never change.
  <FilesMatch "-[A-Za-z0-9_-]{8}\\.(css|js|woff2|ttf)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>
  <FilesMatch "\\.(png|svg|txt|webmanifest)$">
    Header set Cache-Control "public, max-age=2592000"
  </FilesMatch>
  # Pages, the sitemap and the server-function data are revalidated, so a new
  # build is live at once.
  <FilesMatch "\\.(html|xml|json)$">
    Header set Cache-Control "no-cache"
  </FilesMatch>
</IfModule>

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css text/plain text/xml text/javascript application/javascript application/json application/xml application/manifest+json image/svg+xml font/ttf
</IfModule>
`
}

function headersFile({ pages }: HeaderMap): string {
  const common = Object.entries(COMMON_HEADERS)
    .map(([name, value]) => `  ${name}: ${value}`)
    .join('\n')
  // Netlify joins a header set by several matching rules, and two CSPs would
  // intersect, so the policy is only ever set per page.
  const perPage = Object.entries(pages)
    .flatMap(([path, policy]) =>
      spellings(path).map((each) => `${each}\n  Content-Security-Policy: ${policy}`),
    )
    .join('\n\n')
  return `# Generated by scripts/postbuild.ts for hosts that read _headers (Netlify, Cloudflare Pages).
/*
${common}

/assets/*
  Cache-Control: public, max-age=2592000

${perPage}
`
}

// ---- Translation report, as the old generator printed it ----

function flatten(
  value: unknown,
  prefix = '',
  into = new Map<string, string>(),
): Map<string, string> {
  if (typeof value !== 'object' || value === null) return into
  for (const [key, child] of Object.entries(value)) {
    if (key === '_comment' || key.endsWith('_comment')) continue
    const path = prefix ? `${prefix}.${key}` : key
    if (typeof child === 'string') into.set(path, child)
    else flatten(child, path, into)
  }
  return into
}

function report(): string[] {
  const read = (code: string): Map<string, string> | null => {
    const file = join(MESSAGES, `${code}.json`)
    return existsSync(file) ? flatten(JSON.parse(readFileSync(file, 'utf8'))) : null
  }
  const english = read('en') ?? new Map()
  return LOCALES.map(({ code }) => {
    const own = read(code)
    if (!own) return `  ${code.padEnd(4)} no file, English throughout`
    const missing = [...english.keys()].filter((key) => !own.get(key)?.trim())
    return `  ${code.padEnd(4)} ${missing.length ? `${missing.length} missing (${missing.slice(0, 6).join(', ')})` : 'complete'}`
  })
}

// ---- The 404 page ships without the app ----

// The host serves 404.html at whatever unknown URL was asked for, and React
// would hydrate it against a route that cannot match, so the page is left
// static: links are plain anchors and the language menu is a <details>. Only
// the pre-paint theme script stays.
function staticNotFound(): void {
  const file = join(CLIENT, '404.html')
  const html = readFileSync(file, 'utf8')
    .replace(/<link rel="modulepreload"[^>]*>/g, '')
    .replace(/<script(\s[^>]*)?>([\s\S]*?)<\/script>/g, (whole, attributes = '', body = '') =>
      /application\/(?:ld\+)?json/.test(attributes) || body.includes('ihsaanly.theme') ? whole : '',
    )
  writeFileSync(file, html)
}

// ---- Main ----

// The 404 route also prerenders as /404/; only /404.html is served.
rmSync(join(CLIENT, '404'), { recursive: true, force: true })
staticNotFound()

const map = policies()
writeFileSync(join(CLIENT, '.htaccess'), htaccess(map))
writeFileSync(join(CLIENT, '_headers'), headersFile(map))
writeFileSync(join(CLIENT, 'sitemap.xml'), sitemap())
writeFileSync(join(ROOT, 'dist', 'headers.json'), `${JSON.stringify(map, null, 2)}\n`)

console.log(`postbuild: ${Object.keys(map.pages).length} pages, each with its own CSP`)
console.log('translations:')
for (const line of report()) console.log(line)
if (problems.length) {
  for (const problem of problems) console.error(`  ${problem}`)
  process.exit(1)
}
