import type { SupportedLanguage } from '@/i18n/locale'

/** The English table. Every other language must match its shape; see Strings. */
export const en = {
  tabs: {
    today: 'Today',
    library: 'Library',
    more: 'More',
  },
  today: {
    title: 'Today',
    nothingElse: 'Nothing else is asked of you today.',
    empty: 'Nothing here yet.',
    needsLocationTitle: 'Where are you?',
    needsLocation:
      'Prayer windows, the Hijri date and everything the day asks of you follow from a rough location. It is worked out on this phone and never sent anywhere.',
    chooseCity: 'Choose a city instead',
    chooseCityDetail: 'No permission needed. Everything still works.',
  },
  plan: {
    rightNow: 'Right now',
    tryOneMore: 'Try one more',
    add: 'Add',
    notNow: 'Not now',
    alsoNow: 'Also now',
    upNext: 'Up next',
    before: 'Before',
    after: 'After',
    soon: 'Soon',
    inAboutAnHour: 'In about an hour',
    inAboutHours: (hours: number): string => `In about ${hours} hours`,
    context: 'Where you are',
    comingUp: 'Later this week',
    alsoToday: 'Also today',
    tomorrow: 'Tomorrow',
    inDays: (days: number): string => `In ${days} days`,
    prayers: 'Prayers',
    optional: 'Optional',
    expected: 'Expected',
    confirmLocally: 'Confirm with your local authority',
    prayed: 'Prayed',
    makeUp: 'To make up',
    outstanding: (count: number): string => `${count} to make up`,
  },
  prayer: {
    fajr: 'Fajr',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghrib',
    isha: 'Isha',
  },
  window: {
    fajr: 'Fajr',
    sunrise: 'Morning',
    dhuhr: 'After Dhuhr',
    asr: 'Evening',
    maghrib: 'After Maghrib',
    isha: 'Night',
  },
  notifications: {
    title: 'Reminders',
    windows: 'Morning and evening adhkar',
    lookAhead: 'Upcoming fasting days',
    prayers: 'Prayer reminders',
    prayersDetail: 'Off by default \u2014 your adhan app already does this.',
    quietHours: 'Quiet hours',
    quietHoursDetail: (from: number, to: number): string => `${from}:00 to ${to}:00`,
    quietHoursOff: 'Off',
    perDay: 'Daily limit',
    permission: 'Permission',
    permissionGranted: 'Allowed',
    permissionDenied: 'Turned off in system settings',
    permissionUndetermined: 'Not asked yet',
    permissionUnavailable: 'Not available on this device',
    openSettings: 'Open system settings',
    whichItems: 'Which items',
    whichItemsDetail: 'Only items that have a moment to remind you of appear here.',
    sendTest: 'Send a test reminder',
    sendTestDetail: 'Arrives in a few seconds.',
    testTitle: 'A test reminder',
    testBody: 'This is what a reminder from Ihsaanly looks like.',
    action: {
      done: 'Done',
      later: 'Later',
    },
    body: {
      window: 'Now, until the window closes.',
      windowUntil: (closes: string): string => `Open until ${closes}.`,
      tomorrow: 'Tomorrow.',
      prayerWindow: 'The time has entered. The window stays open until the next prayer.',
    },
  },
  event: {
    ascending: 'Going up',
    descending: 'Going down',
    driving: 'Driving',
    travel: 'Travelling',
    'leaving-home': 'Leaving home',
    'entering-home': 'Coming home',
  } as Record<string, string>,
  events: {
    title: 'Where you are',
    explanation:
      'Most of these moments cannot be detected by a phone at all \u2014 a lift, a hill, a staircase. Their duas are one tap away in the Library and on the widget instead.',
    detectHome: 'Notice when I leave home',
    detectHomeDetail:
      'Approximate. The phone notices a hundred metres or so from the door and up to a minute late, so treat it as a nudge rather than the moment.',
    setHome: 'Set home to my current place',
    homeUnset: 'Not set',
    homeNeeded: 'Nothing is being watched yet \u2014 set home below.',
    noPlaceYet: 'Set where you are first',
    manual: 'Tell the app instead',
    manualDetail: 'Raise a state yourself when no sensor can find it.',
  },
  qada: {
    title: 'To make up',
    intro:
      'Prayers owed from before you started tracking, and any owed since. A count, never a list. Counting starts from the first prayer you mark.',
    owed: 'Owed from before',
    madeUp: 'Made up now',
    record: (count: number): string => (count === 1 ? 'Record one' : `Record ${count}`),
    outstanding: (count: number): string => (count === 1 ? '1 owed' : `${count} owed`),
    none: 'Nothing owed',
    summary: (count: number): string => (count === 1 ? '1 prayer owed' : `${count} prayers owed`),
    manage: 'Adjust what you owe',
    manageDetail: 'Set what you carry over and record make-ups in one go.',
  },
  fasting: {
    title: 'Fasts',
    intro: 'Ramadan days you did not fast, and any owed from before. A count, never a list.',
    notFastingToday: 'Not fasting today',
    notFastingTodayDetail: 'Keeps one fast to make up later.',
    recordedToday: 'Noted: not fasting today',
    undo: 'Tap to undo',
    summary: (count: number): string =>
      count === 1 ? '1 fast to make up' : `${count} fasts to make up`,
    outstanding: (count: number): string => (count === 1 ? '1 owed' : `${count} owed`),
    none: 'Nothing owed',
    owed: 'Owed from before',
    recordMadeUp: 'Record one made up',
  },
  history: {
    title: 'History',
    empty: 'Nothing recorded yet.',
    firstWeek:
      'Each day you mark a prayer or finish an item is kept here. After a week you will see which prayers you tend to pray early and which items you keep.',
    daysActive: (days: number): string => `${days} ${days === 1 ? 'day' : 'days'} recorded`,
    prayers: 'Prayers',
    completed: 'Completed',
    times: (count: number): string => `${count} ${count === 1 ? 'time' : 'times'}`,
    early: (minutes: number): string => `usually about ${minutes} min into the window`,
    late: (minutes: number): string => `usually about ${minutes} min before it closes`,
  },
  data: {
    title: 'Your data',
    explanation:
      'Everything here lives on this device. Nothing leaves it unless you send it yourself, from this screen.',
    export: 'Export my data',
    exportDetail: 'Readable text you can keep, or carry to another device.',
    importing: 'Import from a file',
    importDetail: 'Merges rather than replaces. Importing the same file twice changes nothing.',
    diagnostics: 'Send a diagnostic report',
    diagnosticsDetail:
      'For fixing a problem. Contains your settings, your practice record, your approximate coordinates and recent errors. You will see it before it is sent.',
    imported: (count: number): string => `Added ${count} ${count === 1 ? 'entry' : 'entries'}.`,
    importFailed: 'That file could not be read.',
    shareFailed: 'Sharing is not available on this device.',
    delete: 'Delete my data',
    deleteDetail:
      'Everything on this device: settings and your practice record. The app starts over.',
    deleteConfirmTitle: 'Delete everything?',
    deleteConfirmBody:
      'Your settings and your practice record are removed from this device. There is no copy anywhere else unless you exported one.',
    deleteConfirm: 'Delete',
    cancel: 'Cancel',
  },
  diagnostics: {
    title: 'Diagnostic report',
    explanation:
      'This is what the report contains. Nothing is sent until you choose to send it, and you pick where it goes.',
    version: 'App version',
    device: 'Device',
    coordinates: 'Approximate coordinates',
    noCoordinates: 'None stored',
    records: 'Practice records',
    settings: 'Settings stored',
    failures: 'Recorded failures',
    failuresDetail: (count: number): string => `${count} the app handled without telling you`,
    reminders: 'Reminders',
    remindersDetail: (permission: string, pending: number): string =>
      `${permission} · ${pending} queued`,
    error: 'Recent error',
    errorIncluded: 'One is included',
    showRaw: 'Show the whole report',
    hideRaw: 'Hide the whole report',
    send: 'Send it',
    cancel: 'Not now',
  },
  about: {
    title: 'About',
    version: 'Version',
    content: 'Content',
    contentUnreviewed: (count: number): string =>
      `${count} items, drafted and awaiting review by a named scholar.`,
    contentReviewedBy: (name: string, count: number): string =>
      `${count} items, reviewed by ${name}.`,
    donate: 'Donate',
    donateBody:
      'Optional, and it unlocks nothing. Every part of the app is free and stays free. Opens in your browser.',
    privacyPolicy: 'Privacy policy',
    privacyTitle: 'Nothing leaves this phone',
    privacyBody:
      'Ihsaanly has no account, no server and no analytics. Your location is used on the device to compute prayer times and is stored only here. Your practice record is stored only here. Nothing is sent anywhere unless you export it or share it yourself. Donate is the one link out of the app: it opens your browser, and that page is not part of Ihsaanly.',
    licences: 'Built with',
    licencesBody:
      'Expo and React Native, the adhan library for prayer times, Umm al-Qura calendar tables, city data from city-timezones, and Natural Earth for the map. Each is used under its own open licence, listed in the source repository.',
  },
  memorise: {
    title: 'Learn it',
    start: 'Practise',
    hide: 'Hide one more',
    known: 'I know this',
    knownDetail: 'It stays in the Library. It stops appearing in reminders.',
    notKnown: 'Still learning',
    noAudio: 'No recitation yet for this one.',
    play: 'Play',
    stop: 'Stop',
    loop: 'Repeat',
  },
  language: {
    title: 'Language',
    restart:
      'Arabic and Urdu read right to left. Switching to or from them restarts the app, or asks you to reopen it.',
    incomplete:
      'English is the original. Every other language is a draft still awaiting review by a qualified speaker.',
    reopenTitle: 'Reopen Ihsaanly',
    reopenBody:
      'This language reads right to left. Close Ihsaanly and open it again for the change to finish.',
    names: {
      en: 'English',
      ar: 'العربية',
      fr: 'Français',
      it: 'Italiano',
      ja: '日本語',
      hi: 'हिन्दी',
      ur: 'اردو',
      so: 'Soomaali',
      zh: '中文（普通话）',
      yue: '廣東話',
    } as Record<SupportedLanguage, string>,
  },
  appearance: {
    title: 'Appearance',
    system: 'System',
    light: 'Light',
    dark: 'Dark',
    note: 'Colours still come from the system, so its contrast settings apply either way.',
  },
  moonSighting: {
    title: 'Moon sighting',
    explanation:
      'Dates in this app are calculated. Communities differ over whether to follow calculation or local sighting, and the two often disagree by a day. Follow whoever your own community follows, and adjust the date in settings so the app agrees with them.',
    disclaimer: 'These are listed so you can find yours. This app endorses none of them.',
  },
  tracking: {
    title: 'Tracking',
    active: 'Active',
    travelling: 'Travelling',
    travellingDetail:
      'Shortening is offered, the regular sunnah prayers step aside, and fasting is offered rather than expected.',
    paused: 'Pause prayer tracking',
    pausedDetail:
      'Prayers are not recorded and nothing accrues to make up. It stays off until you turn it back on.',
  },
  hijri: {
    title: 'Hijri date',
    offset: 'Adjust the date',
    approximate: 'Calculated \u2014 confirm with the authority your community follows.',
    explanation:
      'A calculated calendar and local moon sighting often differ by a day or two. Shift the date here so the app agrees with your community. Dates for fasting days are always shown as expected, never as certain.',
    offsetLabel: (days: number): string =>
      days === 0
        ? 'No change'
        : `${days > 0 ? '+' : ''}${days} day${Math.abs(days) === 1 ? '' : 's'}`,
    format: (day: number, month: string, year: number): string => `${day} ${month} ${year}`,
  },
  hijriMonth: {
    1: 'Muharram',
    2: 'Safar',
    3: 'Rabi\u2019 al-Awwal',
    4: 'Rabi\u2019 ath-Thani',
    5: 'Jumada al-Ula',
    6: 'Jumada al-Akhirah',
    7: 'Rajab',
    8: 'Sha\u2019ban',
    9: 'Ramadan',
    10: 'Shawwal',
    11: 'Dhu al-Qa\u2019dah',
    12: 'Dhu al-Hijjah',
  } as Record<number, string>,
  calculation: {
    title: 'Prayer calculation',
    method: 'Method',
    asr: 'Asr',
    highLatitude: 'High latitude',
    selected: 'Selected',
    explanation:
      'Prayer times are computed on this device and never shown as clock times \u2014 they only decide which part of the day you are in.',
    highLatitudeExplanation:
      'Above roughly 48\u00b0 north, Isha does not occur for part of the year. This decides what is used instead.',
  },
  asr: {
    shafi: 'Standard',
    hanafi: 'Hanafi',
  },
  highLatitude: {
    middleofthenight: 'Middle of the night',
    seventhofthenight: 'Seventh of the night',
    twilightangle: 'Twilight angle',
  },
  method: {
    MuslimWorldLeague: 'Muslim World League',
    Egyptian: 'Egyptian General Authority',
    Karachi: 'University of Islamic Sciences, Karachi',
    UmmAlQura: 'Umm al-Qura, Makkah',
    Dubai: 'Dubai',
    MoonsightingCommittee: 'Moonsighting Committee',
    NorthAmerica: 'ISNA, North America',
    Kuwait: 'Kuwait',
    Qatar: 'Qatar',
    Singapore: 'Singapore',
    Tehran: 'Tehran',
    Turkey: 'Turkey',
  },
  library: {
    title: 'Library',
    empty: 'Adhkar, duas and sunnah actions will be listed here.',
    search: 'Search by name or situation',
    noResults: 'Nothing matches that.',
    filterAll: 'All',
    filterOnToday: 'On Today',
    filterKnown: 'Known',
    onToday: 'On Today',
    known: 'Known',
    emptyOnToday: 'Nothing is on Today yet. Open any item and turn it on.',
    emptyKnown: 'Nothing marked known yet. Practise an item and say when you have it.',
    terms: 'Glossary',
    termsDetail: 'Sunnah, rawatib, adhkar, qada and the rest, in a sentence each.',
  },
  category: {
    adhkar: 'Adhkar',
    dhikr: 'After prayer',
    fasting: 'Fasting',
    food: 'Eating',
    home: 'Home',
    masjid: 'Masjid',
    prayer: 'Prayer',
    sleep: 'Sleep and waking',
    travel: 'Travel',
  } as Record<string, string>,
  item: {
    done: 'Done',
    doneToday: 'Done today',
    undo: 'Undo',
    counterReset: 'Start again',
    yourDay: 'Your day',
    onToday: 'On Today',
    onTodayDetail: 'Appears when its moment comes',
    remind: 'Remind me',
    remindWindow: 'When its window opens',
    remindLookAhead: 'The evening before',
    share: 'Share',
    shareText: 'Share as text',
    shareImage: 'Share as image',
    sharedFrom: 'Shared from Ihsaanly',
    transliteration: 'Transliteration',
    translation: 'Translation',
    why: 'Why',
    how: 'How',
    unreviewed: 'Awaiting review',
    evidence: 'Evidence',
    note: 'Scholars differ',
    repeat: (times: number): string => `Repeat ${times} times`,
    parts: 'What to say',
    partRepeat: (times: number): string => `${times} times`,
    gradedBy: (grader: string): string => `graded by ${grader}`,
    quranReference: (surah: number, ayah: number): string => `Qur\u2019an ${surah}:${ayah}`,
  },
  glossary: {
    title: 'What the words mean',
  },
  ruling: {
    fard: 'Obligatory',
    wajib: 'Obligatory',
    'sunnah-muakkadah': 'Emphasised sunnah',
    sunnah: 'Sunnah',
    mustahabb: 'Recommended',
    mubah: 'Permissible',
  },
  grading: {
    sahih: 'Sahih',
    hasan: 'Hasan',
    "da'if": 'Da\u2019if',
    disputed: 'Disputed',
  },
  more: {
    title: 'More',
    search: 'Search settings',
    prayer: 'Prayer',
    app: 'App',
    practice: 'Your practice',
    empty: 'History, settings and help will live here.',
  },
  onboarding: {
    welcomeTitle: 'The moment, not the clock.',
    welcomeBody:
      'Ihsaanly tells you when the evening adhkar are open. Never a time. Never a score.',
    howTitle: 'You mark the prayer. The sunnah appears.',
    howBody:
      'Tap Dhuhr when you have prayed it and the dhikr that follows is waiting. Nothing leaves this phone. No account, no server.',
    language: 'Language',
    appearance: 'Appearance',
    howSample: 'سُبْحَانَ اللهِ وَبِحَمْدِهِ',
    locationStep: 'Where are you?',
    locationWhy: 'Used on this device to work out the parts of the day. Never sent anywhere.',
    genderStep: 'The tracking pause',
    genderWhy:
      'On some days prayer tracking should stop, with nothing accruing to make up. This tells the app whether to offer that.',
    brother: 'Brother',
    brotherDetail: 'No pause',
    sister: 'Sister',
    sisterDetail: 'Pause offered',
    skip: 'Prefer not to say',
    skipDetail: 'The pause is offered anyway.',
    genderPrivacy: 'Stored on this device. Never sent anywhere, and used for nothing else.',
    remindersStep: 'Reminders',
    remindersWhy: 'Two or three a day, never in the night. Change any of this later in More.',
    windowsDetail: 'When each window opens',
    lookAheadDetail: 'The evening before',
    startStep: 'A starting point',
    startWhy:
      'Choose a size to begin with. Add or remove anything in the Library whenever you like.',
    starting: 'Just starting',
    startingDetail: (count: number): string =>
      `${count} things you can carry from day one: two windows, one dhikr, two duas. For someone new to all of this.`,
    essentials: 'Essentials',
    essentialsDetail: (count: number): string =>
      `${count} items, a reasonable day rather than a complete one. For someone who already prays and wants the sunnah around it.`,
    everything: 'Everything',
    everythingDetail: (count: number): string =>
      `All ${count} items. For someone who knows the content and wants the whole calendar.`,
    skipIntro: 'Skip',
    skipLocation: 'Skip for now',
    reminderPolicy: (perDay: number, from: number, to: number): string =>
      `At most ${perDay} a day, and nothing between ${from}:00 and ${to}:00.`,
    reminderCap: (perDay: number): string => `At most ${perDay} a day.`,
    included: 'Included',
    andMore: (count: number): string => `and ${count} more`,
    back: 'Back',
    continue: 'Continue',
    allowReminders: 'Allow reminders',
    notNow: 'Not now',
    done: 'Start',
  },
  location: {
    title: 'Location',
    notSet: 'Not set',
    currentLocation: 'Current location',
    useDevice: 'Use my location',
    useDeviceDetail: 'Nothing leaves this phone.',
    locating: 'Finding you\u2026',
    orSearch: 'or search for a city',
    follows: 'Prayer windows will follow this place.',
    search: 'Search for a city',
    noResults: 'No cities match that.',
    unavailable:
      'Location services are switched off on this device. Turn them on, or search for your city instead.',
    declined:
      'Location access was declined. Search for your city instead \u2014 everything still works.',
    explanation: 'Used on this device to work out prayer windows. It is never sent anywhere.',
    attribution: 'City data from city-timezones (MIT).',
  },
  textField: {
    clear: 'Clear',
  },
  error: {
    title: 'Something went wrong',
    retry: 'Try again',
  },
  notFound: {
    title: 'Not found',
    body: 'That screen does not exist.',
  },
}

export type Strings = typeof en
