import type { Strings } from './en'

/**
 * Hindi interface copy, in Devanagari and the आप register, using the Islamic
 * vocabulary Hindi-speaking Muslims actually use (नमाज़, सुन्नत, क़ज़ा, दुआ).
 * A draft awaiting review by a qualified speaker; the review is a release
 * condition. Content text (adhkar, duas, evidence) does not live here.
 */

/** Hindi counts: the singular for one, the plural form for everything else. */
function count(n: number, one: string, many: string): string {
  return n === 1 ? `1 ${one}` : `${n} ${many}`
}

export const hi: Strings = {
  tabs: {
    today: 'आज',
    library: 'लाइब्रेरी',
    more: 'और',
  },
  today: {
    title: 'आज',
    nothingElse: 'आज आपसे और कुछ नहीं माँगा गया है।',
    empty: 'यहाँ अभी कुछ नहीं है।',
    needsLocationTitle: 'आप कहाँ हैं?',
    needsLocation:
      'नमाज़ के वक़्त, हिजरी तारीख़ और आज का सब कुछ एक अंदाज़न जगह से तय होता है। यह इसी फ़ोन पर निकाला जाता है और कहीं नहीं भेजा जाता।',
    chooseCity: 'इसकी जगह शहर चुनें',
    chooseCityDetail: 'किसी इजाज़त की ज़रूरत नहीं। सब कुछ वैसे ही चलता है।',
  },
  plan: {
    rightNow: 'अभी',
    tryOneMore: 'एक और आज़माएँ',
    add: 'जोड़ें',
    notNow: 'अभी नहीं',
    alsoNow: 'यह भी अभी',
    upNext: 'इसके बाद',
    before: 'पहले',
    after: 'बाद में',
    soon: 'जल्द ही',
    inAboutAnHour: 'लगभग एक घंटे में',
    inAboutHours: (hours: number): string => `लगभग ${hours} घंटे में`,
    context: 'आप कहाँ हैं',
    comingUp: 'इस हफ़्ते आगे',
    alsoToday: 'आज यह भी',
    tomorrow: 'कल',
    inDays: (days: number): string => `${days} दिन में`,
    prayers: 'नमाज़ें',
    optional: 'इख़्तियारी',
    expected: 'संभावित',
    confirmLocally: 'अपनी स्थानीय संस्था से पुष्टि करें',
    prayed: 'पढ़ ली',
    makeUp: 'क़ज़ा अदा करनी है',
    outstanding: (n: number): string => `${count(n, 'नमाज़', 'नमाज़ें')} क़ज़ा अदा करनी है`,
  },
  prayer: {
    fajr: 'फ़ज्र',
    dhuhr: 'ज़ुहर',
    asr: 'अस्र',
    maghrib: 'मग़रिब',
    isha: 'इशा',
  },
  window: {
    fajr: 'फ़ज्र',
    sunrise: 'सुबह',
    dhuhr: 'ज़ुहर के बाद',
    asr: 'शाम',
    maghrib: 'मग़रिब के बाद',
    isha: 'रात',
  },
  notifications: {
    title: 'रिमाइंडर',
    windows: 'सुबह और शाम के अज़कार',
    lookAhead: 'आने वाले रोज़ों के दिन',
    prayers: 'नमाज़ के रिमाइंडर',
    prayersDetail: 'शुरू में बंद — आपकी अज़ान वाली ऐप पहले से यह करती है।',
    quietHours: 'ख़ामोशी के घंटे',
    quietHoursDetail: (from: number, to: number): string => `${from}:00 से ${to}:00 तक`,
    quietHoursOff: 'बंद',
    perDay: 'रोज़ की हद',
    permission: 'इजाज़त',
    permissionGranted: 'इजाज़त है',
    permissionDenied: 'सिस्टम सेटिंग्स में बंद है',
    permissionUndetermined: 'अभी पूछा नहीं गया',
    permissionUnavailable: 'इस डिवाइस पर उपलब्ध नहीं',
    openSettings: 'सिस्टम सेटिंग्स खोलें',
    whichItems: 'कौन-से आइटम',
    whichItemsDetail: 'यहाँ सिर्फ़ वही आइटम दिखते हैं जिनका याद दिलाने लायक़ कोई वक़्त है।',
    sendTest: 'एक टेस्ट रिमाइंडर भेजें',
    sendTestDetail: 'कुछ सेकंड में आ जाएगा।',
    testTitle: 'एक टेस्ट रिमाइंडर',
    testBody: 'इहसानली का रिमाइंडर कुछ ऐसा दिखता है।',
    action: {
      done: 'हो गया',
      later: 'बाद में',
    },
    body: {
      window: 'अभी, वक़्त ख़त्म होने तक।',
      windowUntil: (closes: string): string => `${closes} तक खुला है।`,
      tomorrow: 'कल।',
      prayerWindow: 'वक़्त शुरू हो गया है। यह अगली नमाज़ तक रहता है।',
    },
  },
  event: {
    ascending: 'ऊपर जाते हुए',
    descending: 'नीचे उतरते हुए',
    driving: 'गाड़ी चलाते हुए',
    travel: 'सफ़र में',
    'leaving-home': 'घर से निकलते हुए',
    'entering-home': 'घर लौटते हुए',
  },
  events: {
    title: 'आप कहाँ हैं',
    explanation:
      'इनमें से ज़्यादातर मौक़े फ़ोन पकड़ ही नहीं सकता — लिफ़्ट, पहाड़ी, सीढ़ियाँ। इनकी दुआएँ लाइब्रेरी और विजेट पर एक टैप की दूरी पर हैं।',
    detectHome: 'जब मैं घर से निकलूँ तो पहचानें',
    detectHomeDetail:
      'अंदाज़न। फ़ोन दरवाज़े से लगभग सौ मीटर दूर और एक मिनट तक की देरी से पहचानता है, इसलिए इसे ठीक उस पल की जगह एक इशारा समझें।',
    setHome: 'मेरी मौजूदा जगह को घर बनाएँ',
    homeUnset: 'तय नहीं',
    homeNeeded: 'अभी कुछ देखा नहीं जा रहा — नीचे घर तय करें।',
    noPlaceYet: 'पहले अपनी जगह तय करें',
    manual: 'इसकी जगह ऐप को ख़ुद बताएँ',
    manualDetail: 'जब कोई सेंसर न पकड़ सके तो हालत ख़ुद चुनें।',
  },
  qada: {
    title: 'क़ज़ा',
    intro:
      'ट्रैकिंग शुरू करने से पहले की बाक़ी नमाज़ें, और उसके बाद की भी। सिर्फ़ गिनती, कभी कोई सूची नहीं। गिनती उस पहली नमाज़ से शुरू होती है जिसे आप दर्ज करते हैं।',
    owed: 'पहले से बाक़ी',
    madeUp: 'अभी अदा की',
    record: (n: number): string => (n === 1 ? 'एक दर्ज करें' : `${n} दर्ज करें`),
    outstanding: (n: number): string => `${n} बाक़ी`,
    none: 'कुछ बाक़ी नहीं',
    summary: (n: number): string => `${count(n, 'नमाज़', 'नमाज़ें')} बाक़ी`,
    manage: 'बाक़ी नमाज़ें बदलें',
    manageDetail: 'पहले से बाक़ी गिनती तय करें और अदा की गई क़ज़ा एक साथ दर्ज करें।',
  },
  fasting: {
    title: 'रोज़े',
    intro:
      'रमज़ान के वे दिन जिनमें आपने रोज़ा नहीं रखा, और पहले से बाक़ी रोज़े। सिर्फ़ गिनती, कभी कोई सूची नहीं।',
    notFastingToday: 'आज रोज़ा नहीं है',
    notFastingTodayDetail: 'एक रोज़ा बाद में क़ज़ा रखने के लिए जुड़ जाता है।',
    recordedToday: 'दर्ज हुआ: आज रोज़ा नहीं',
    undo: 'वापस लेने के लिए टैप करें',
    summary: (n: number): string => `${count(n, 'रोज़ा', 'रोज़े')} क़ज़ा रखने हैं`,
    outstanding: (n: number): string => `${n} बाक़ी`,
    none: 'कुछ बाक़ी नहीं',
    owed: 'पहले से बाक़ी',
    recordMadeUp: 'एक क़ज़ा रोज़ा दर्ज करें',
  },
  history: {
    title: 'इतिहास',
    empty: 'अभी कुछ दर्ज नहीं हुआ।',
    firstWeek:
      'जिस दिन आप कोई नमाज़ दर्ज करते हैं या कोई आइटम पूरा करते हैं, वह यहाँ रखा जाता है। एक हफ़्ते बाद आप देखेंगे कि कौन-सी नमाज़ें आप अक्सर जल्दी पढ़ते हैं और कौन-से आइटम आप निभाते हैं।',
    daysActive: (days: number): string => `${days} दिन दर्ज`,
    prayers: 'नमाज़ें',
    completed: 'पूरे किए',
    times: (n: number): string => `${n} बार`,
    early: (minutes: number): string => `अक्सर वक़्त शुरू होने के लगभग ${minutes} मिनट बाद`,
    late: (minutes: number): string => `अक्सर वक़्त ख़त्म होने से लगभग ${minutes} मिनट पहले`,
  },
  data: {
    title: 'आपका डेटा',
    explanation:
      'यहाँ का सब कुछ इसी डिवाइस पर रहता है। जब तक आप ख़ुद इस स्क्रीन से न भेजें, कुछ बाहर नहीं जाता।',
    export: 'मेरा डेटा एक्सपोर्ट करें',
    exportDetail: 'पढ़ने लायक़ टेक्स्ट, जिसे आप रख सकते हैं या दूसरे डिवाइस पर ले जा सकते हैं।',
    importing: 'फ़ाइल से इम्पोर्ट करें',
    importDetail: 'बदलता नहीं, मिलाता है। एक ही फ़ाइल दो बार इम्पोर्ट करने से कुछ नहीं बदलता।',
    diagnostics: 'जाँच रिपोर्ट भेजें',
    diagnosticsDetail:
      'किसी दिक़्क़त को ठीक करने के लिए। इसमें आपकी सेटिंग्स, आपका अमल का रिकॉर्ड, आपके अंदाज़न निर्देशांक और हाल की ग़लतियाँ होती हैं। भेजने से पहले आप इसे देखेंगे।',
    imported: (n: number): string => (n === 1 ? '1 एंट्री जोड़ी गई।' : `${n} एंट्रियाँ जोड़ी गईं।`),
    importFailed: 'वह फ़ाइल पढ़ी नहीं जा सकी।',
    shareFailed: 'इस डिवाइस पर शेयर करना उपलब्ध नहीं है।',
    delete: 'मेरा डेटा मिटाएँ',
    deleteDetail: 'इस डिवाइस का सब कुछ: सेटिंग्स और आपका अमल का रिकॉर्ड। ऐप फिर से शुरू होगी।',
    deleteConfirmTitle: 'सब कुछ मिटा दें?',
    deleteConfirmBody:
      'आपकी सेटिंग्स और आपका अमल का रिकॉर्ड इस डिवाइस से हटा दिया जाएगा। अगर आपने एक्सपोर्ट नहीं किया है तो इसकी कोई कॉपी कहीं और नहीं है।',
    deleteConfirm: 'मिटाएँ',
    cancel: 'रद्द करें',
  },
  diagnostics: {
    title: 'जाँच रिपोर्ट',
    explanation:
      'रिपोर्ट में यही है। जब तक आप भेजना न चुनें, कुछ नहीं भेजा जाता, और कहाँ जाए यह आप तय करते हैं।',
    version: 'ऐप वर्ज़न',
    device: 'डिवाइस',
    coordinates: 'अंदाज़न निर्देशांक',
    noCoordinates: 'कुछ सहेजा नहीं गया',
    records: 'अमल के रिकॉर्ड',
    settings: 'सहेजी गई सेटिंग्स',
    failures: 'दर्ज गड़बड़ियाँ',
    failuresDetail: (n: number): string => `${n} जिन्हें ऐप ने आपको बताए बिना सँभाल लिया`,
    reminders: 'रिमाइंडर',
    remindersDetail: (permission: string, pending: number): string =>
      `${permission} · ${pending} क़तार में`,
    error: 'हाल की ग़लती',
    errorIncluded: 'एक शामिल है',
    showRaw: 'पूरी रिपोर्ट दिखाएँ',
    hideRaw: 'पूरी रिपोर्ट छिपाएँ',
    send: 'भेजें',
    cancel: 'अभी नहीं',
  },
  about: {
    title: 'परिचय',
    version: 'वर्ज़न',
    content: 'सामग्री',
    contentUnreviewed: (n: number): string =>
      `${count(n, 'आइटम', 'आइटम')}, मसौदा तैयार है और एक नामित आलिम की समीक्षा का इंतज़ार है।`,
    contentReviewedBy: (name: string, n: number): string =>
      `${count(n, 'आइटम', 'आइटम')}, ${name} द्वारा समीक्षा किए गए।`,
    donate: 'दान करें',
    donateBody:
      'इख़्तियारी है, और इससे कुछ भी अनलॉक नहीं होता। ऐप का हर हिस्सा मुफ़्त है और मुफ़्त रहेगा। आपके ब्राउज़र में खुलता है।',
    privacyPolicy: 'प्राइवेसी पॉलिसी',
    privacyTitle: 'इस फ़ोन से कुछ बाहर नहीं जाता',
    privacyBody:
      'इहसानली में कोई अकाउंट, कोई सर्वर और कोई एनालिटिक्स नहीं है। आपकी जगह डिवाइस पर ही नमाज़ के वक़्त निकालने में इस्तेमाल होती है और सिर्फ़ यहीं रखी जाती है। आपका अमल का रिकॉर्ड सिर्फ़ यहीं रखा जाता है। जब तक आप ख़ुद एक्सपोर्ट या शेयर न करें, कुछ कहीं नहीं भेजा जाता। दान करें ही ऐप से बाहर जाने वाला एकमात्र लिंक है: यह आपका ब्राउज़र खोलता है, और वह पेज इहसानली का हिस्सा नहीं है।',
    licences: 'किससे बना है',
    licencesBody:
      'Expo और React Native, नमाज़ के वक़्त के लिए adhan लाइब्रेरी, उम्मुल क़ुरा कैलेंडर टेबल, city-timezones से शहरों का डेटा, और नक़्शे के लिए Natural Earth। हर एक अपने खुले लाइसेंस के तहत इस्तेमाल होता है, जिसकी सूची सोर्स रिपॉज़िटरी में है।',
  },
  memorise: {
    title: 'इसे याद करें',
    start: 'अभ्यास करें',
    hide: 'एक और छिपाएँ',
    known: 'मुझे यह याद है',
    knownDetail: 'यह लाइब्रेरी में रहता है। रिमाइंडर में आना बंद हो जाता है।',
    notKnown: 'अभी सीख रहा हूँ',
    noAudio: 'इसकी तिलावत अभी उपलब्ध नहीं।',
    play: 'चलाएँ',
    stop: 'रोकें',
    loop: 'दोहराएँ',
  },
  language: {
    title: 'भाषा',
    restart:
      'अरबी दाएँ से बाएँ पढ़ी जाती है। उस पर या उससे बदलने पर ऐप दोबारा शुरू होती है, या आपसे उसे फिर से खोलने को कहती है।',
    incomplete:
      'असल अंग्रेज़ी है। बाक़ी हर भाषा एक मसौदा है जिसकी किसी योग्य जानकार से समीक्षा अभी बाक़ी है।',
    reopenTitle: 'इहसानली फिर से खोलें',
    reopenBody:
      'यह भाषा दाएँ से बाएँ पढ़ी जाती है। बदलाव पूरा करने के लिए इहसानली बंद करके फिर से खोलें।',
    names: {
      en: 'English',
      ar: 'العربية',
      fr: 'Français',
      it: 'Italiano',
      ja: '日本語',
      hi: 'हिन्दी',
      ur: 'اردو',
      so: 'Soomaali',
      zh: '中文（普通话）',
      yue: '廣東話',
    },
  },
  appearance: {
    title: 'रूप',
    system: 'सिस्टम',
    light: 'हल्का',
    dark: 'गहरा',
    note: 'रंग अब भी सिस्टम से आते हैं, इसलिए उसकी कंट्रास्ट सेटिंग्स हर हाल में लागू होती हैं।',
  },
  moonSighting: {
    title: 'चाँद देखना',
    explanation:
      'इस ऐप की तारीख़ें हिसाब से निकाली जाती हैं। समुदायों में इस पर इख़्तिलाफ़ है कि हिसाब माना जाए या स्थानीय चाँद देखना, और दोनों में अक्सर एक दिन का फ़र्क़ होता है। आपका अपना समुदाय जिसे मानता है, उसी को मानें, और सेटिंग्स में तारीख़ ठीक करें ताकि ऐप उनसे मेल खाए।',
    disclaimer:
      'ये इसलिए दिए गए हैं कि आप अपनी संस्था ढूँढ सकें। यह ऐप इनमें से किसी का समर्थन नहीं करती।',
  },
  tracking: {
    title: 'ट्रैकिंग',
    active: 'चालू',
    travelling: 'सफ़र में',
    travellingDetail:
      'क़स्र की सुविधा दी जाती है, सुन्नत-ए-मुअक्कदा नमाज़ें हट जाती हैं, और रोज़ा ज़रूरी की जगह इख़्तियारी दिखाया जाता है।',
    paused: 'नमाज़ ट्रैकिंग रोकें',
    pausedDetail:
      'नमाज़ें दर्ज नहीं होतीं और कोई क़ज़ा नहीं जुड़ती। जब तक आप फिर से चालू न करें, यह बंद रहता है।',
  },
  hijri: {
    title: 'हिजरी तारीख़',
    offset: 'तारीख़ ठीक करें',
    approximate: 'हिसाब से निकाली गई — अपने समुदाय की संस्था से पुष्टि करें।',
    explanation:
      'हिसाब वाला कैलेंडर और स्थानीय चाँद देखना अक्सर एक-दो दिन अलग होते हैं। यहाँ तारीख़ आगे-पीछे करें ताकि ऐप आपके समुदाय से मेल खाए। रोज़ों के दिन हमेशा संभावित दिखाए जाते हैं, कभी पक्के नहीं।',
    offsetLabel: (days: number): string =>
      days === 0 ? 'कोई बदलाव नहीं' : `${days > 0 ? '+' : ''}${days} दिन`,
    format: (day: number, month: string, year: number): string => `${day} ${month} ${year}`,
  },
  hijriMonth: {
    1: 'मुहर्रम',
    2: 'सफ़र',
    3: 'रबीउल अव्वल',
    4: 'रबीउस्सानी',
    5: 'जुमादल ऊला',
    6: 'जुमादल आख़िरा',
    7: 'रजब',
    8: 'शाबान',
    9: 'रमज़ान',
    10: 'शव्वाल',
    11: 'ज़ुलक़ादा',
    12: 'ज़ुलहिज्जा',
  },
  calculation: {
    title: 'नमाज़ के वक़्त का हिसाब',
    method: 'तरीक़ा',
    asr: 'अस्र',
    highLatitude: 'ऊँचा अक्षांश',
    selected: 'चुना गया',
    explanation:
      'नमाज़ के वक़्त इसी डिवाइस पर निकाले जाते हैं और कभी घड़ी के समय के रूप में नहीं दिखाए जाते — वे सिर्फ़ यह तय करते हैं कि आप दिन के किस हिस्से में हैं।',
    highLatitudeExplanation:
      'लगभग 48° उत्तर से ऊपर, साल के कुछ हिस्से में इशा का वक़्त आता ही नहीं। यह तय करता है कि उसकी जगह क्या इस्तेमाल हो।',
  },
  asr: {
    shafi: 'आम (जमहूर)',
    hanafi: 'हनफ़ी',
  },
  highLatitude: {
    middleofthenight: 'आधी रात',
    seventhofthenight: 'रात का सातवाँ हिस्सा',
    twilightangle: 'शफ़क़ का कोण',
  },
  method: {
    MuslimWorldLeague: 'मुस्लिम वर्ल्ड लीग',
    Egyptian: 'मिस्र की जनरल अथॉरिटी',
    Karachi: 'यूनिवर्सिटी ऑफ़ इस्लामिक साइंसेज़, कराची',
    UmmAlQura: 'उम्मुल क़ुरा, मक्का',
    Dubai: 'दुबई',
    MoonsightingCommittee: 'मूनसाइटिंग कमेटी',
    NorthAmerica: 'ISNA, उत्तरी अमेरिका',
    Kuwait: 'कुवैत',
    Qatar: 'क़तर',
    Singapore: 'सिंगापुर',
    Tehran: 'तेहरान',
    Turkey: 'तुर्की',
  },
  library: {
    title: 'लाइब्रेरी',
    empty: 'अज़कार, दुआएँ और सुन्नत आमाल यहाँ दिखेंगे।',
    search: 'नाम या हालत से खोजें',
    noResults: 'इससे कुछ मेल नहीं खाता।',
    filterAll: 'सब',
    filterOnToday: 'आज में',
    filterKnown: 'याद हैं',
    onToday: 'आज में',
    known: 'याद है',
    emptyOnToday: 'आज में अभी कुछ नहीं है। कोई भी आइटम खोलें और उसे चालू करें।',
    emptyKnown:
      'अभी कुछ भी याद के रूप में दर्ज नहीं। किसी आइटम का अभ्यास करें और याद हो जाए तो बताएँ।',
    terms: 'शब्दकोश',
    termsDetail: 'सुन्नत, रवातिब, अज़कार, क़ज़ा और बाक़ी सब, एक-एक वाक्य में।',
  },
  category: {
    adhkar: 'अज़कार',
    dhikr: 'नमाज़ के बाद',
    fasting: 'रोज़ा',
    food: 'खाना',
    home: 'घर',
    masjid: 'मस्जिद',
    prayer: 'नमाज़',
    sleep: 'सोना और जागना',
    travel: 'सफ़र',
  },
  item: {
    done: 'हो गया',
    doneToday: 'आज हो गया',
    undo: 'वापस लें',
    counterReset: 'फिर से शुरू करें',
    yourDay: 'आपका दिन',
    onToday: 'आज में',
    onTodayDetail: 'इसका वक़्त आने पर दिखता है',
    remind: 'मुझे याद दिलाएँ',
    remindWindow: 'जब इसका वक़्त शुरू हो',
    remindLookAhead: 'एक शाम पहले',
    share: 'शेयर करें',
    shareText: 'टेक्स्ट के रूप में शेयर करें',
    shareImage: 'तस्वीर के रूप में शेयर करें',
    sharedFrom: 'इहसानली से शेयर किया गया',
    transliteration: 'उच्चारण',
    translation: 'तर्जुमा',
    why: 'क्यों',
    how: 'कैसे',
    unreviewed: 'समीक्षा बाक़ी',
    evidence: 'दलील',
    note: 'उलमा की राय अलग है',
    repeat: (times: number): string => `${times} बार दोहराएँ`,
    parts: 'क्या पढ़ें',
    partRepeat: (times: number): string => `${times} बार`,
    gradedBy: (grader: string): string => `${grader} के मुताबिक़ दर्जा`,
    quranReference: (surah: number, ayah: number): string => `क़ुरआन ${surah}:${ayah}`,
  },
  glossary: {
    title: 'शब्दों के मतलब',
  },
  ruling: {
    fard: 'फ़र्ज़',
    wajib: 'वाजिब',
    'sunnah-muakkadah': 'सुन्नत-ए-मुअक्कदा',
    sunnah: 'सुन्नत',
    mustahabb: 'मुस्तहब',
    mubah: 'मुबाह',
  },
  grading: {
    sahih: 'सहीह',
    hasan: 'हसन',
    "da'if": 'ज़ईफ़',
    disputed: 'इख़्तिलाफ़ी',
  },
  more: {
    title: 'और',
    search: 'सेटिंग्स खोजें',
    prayer: 'नमाज़',
    app: 'ऐप',
    practice: 'आपका अमल',
    empty: 'इतिहास, सेटिंग्स और मदद यहाँ होंगे।',
  },
  onboarding: {
    welcomeTitle: 'घड़ी नहीं, मौक़ा।',
    welcomeBody:
      'इहसानली आपको बताती है कि शाम के अज़कार का वक़्त कब शुरू हुआ। कभी घड़ी का समय नहीं। कभी कोई स्कोर नहीं।',
    howTitle: 'आप नमाज़ दर्ज करें। सुन्नत सामने आ जाती है।',
    howBody:
      'ज़ुहर पढ़ने के बाद उस पर टैप करें, और उसके बाद का ज़िक्र आपका इंतज़ार कर रहा होगा। इस फ़ोन से कुछ बाहर नहीं जाता। न अकाउंट, न सर्वर।',
    language: 'भाषा',
    appearance: 'रूप',
    howSample: 'سُبْحَانَ اللهِ وَبِحَمْدِهِ',
    locationStep: 'आप कहाँ हैं?',
    locationWhy:
      'इसी डिवाइस पर दिन के हिस्से निकालने में इस्तेमाल होता है। कभी कहीं नहीं भेजा जाता।',
    genderStep: 'ट्रैकिंग का ठहराव',
    genderWhy:
      'कुछ दिनों में नमाज़ ट्रैकिंग रुकनी चाहिए, और कोई क़ज़ा नहीं जुड़नी चाहिए। इससे ऐप जानती है कि यह सुविधा दे या नहीं।',
    brother: 'भाई',
    brotherDetail: 'कोई ठहराव नहीं',
    sister: 'बहन',
    sisterDetail: 'ठहराव की सुविधा',
    skip: 'बताना नहीं चाहते',
    skipDetail: 'ठहराव की सुविधा फिर भी दी जाती है।',
    genderPrivacy:
      'इसी डिवाइस पर सहेजा जाता है। कभी कहीं नहीं भेजा जाता, और किसी और काम में नहीं आता।',
    remindersStep: 'रिमाइंडर',
    remindersWhy: 'दिन में दो-तीन, रात में कभी नहीं। यह सब बाद में "और" में बदल सकते हैं।',
    windowsDetail: 'जब हर वक़्त शुरू हो',
    lookAheadDetail: 'एक शाम पहले',
    startStep: 'शुरुआत',
    startWhy: 'शुरू करने के लिए एक आकार चुनें। लाइब्रेरी में जब चाहें कुछ भी जोड़ें या हटाएँ।',
    starting: 'बस शुरुआत',
    startingDetail: (n: number): string =>
      `${count(n, 'चीज़', 'चीज़ें')} जिन्हें आप पहले दिन से निभा सकते हैं: दो वक़्त, एक ज़िक्र, दो दुआएँ। उनके लिए जिनके लिए यह सब नया है।`,
    essentials: 'ज़रूरी',
    essentialsDetail: (n: number): string =>
      `${count(n, 'आइटम', 'आइटम')}, पूरा दिन नहीं बल्कि एक मुनासिब दिन। उनके लिए जो पहले से नमाज़ पढ़ते हैं और उसके आसपास की सुन्नत चाहते हैं।`,
    everything: 'सब कुछ',
    everythingDetail: (n: number): string =>
      `सभी ${n} आइटम। उनके लिए जो सामग्री जानते हैं और पूरा कैलेंडर चाहते हैं।`,
    skipIntro: 'छोड़ें',
    skipLocation: 'अभी छोड़ें',
    reminderPolicy: (perDay: number, from: number, to: number): string =>
      `दिन में ज़्यादा से ज़्यादा ${perDay}, और ${from}:00 से ${to}:00 के बीच कुछ नहीं।`,
    reminderCap: (perDay: number): string => `दिन में ज़्यादा से ज़्यादा ${perDay}।`,
    included: 'शामिल',
    andMore: (n: number): string => `${n} और`,
    back: 'पीछे',
    continue: 'आगे बढ़ें',
    allowReminders: 'रिमाइंडर की इजाज़त दें',
    notNow: 'अभी नहीं',
    done: 'शुरू करें',
  },
  location: {
    title: 'जगह',
    notSet: 'तय नहीं',
    currentLocation: 'मौजूदा जगह',
    useDevice: 'मेरी जगह इस्तेमाल करें',
    useDeviceDetail: 'इस फ़ोन से कुछ बाहर नहीं जाता।',
    locating: 'आपको ढूँढ रहे हैं…',
    orSearch: 'या कोई शहर खोजें',
    follows: 'नमाज़ के वक़्त इसी जगह के हिसाब से होंगे।',
    search: 'शहर खोजें',
    noResults: 'कोई शहर मेल नहीं खाता।',
    unavailable:
      'इस डिवाइस पर लोकेशन सेवाएँ बंद हैं। उन्हें चालू करें, या इसकी जगह अपना शहर खोजें।',
    declined: 'लोकेशन की इजाज़त नहीं दी गई। इसकी जगह अपना शहर खोजें — सब कुछ फिर भी चलता है।',
    explanation:
      'इसी डिवाइस पर नमाज़ के वक़्त निकालने में इस्तेमाल होती है। कभी कहीं नहीं भेजी जाती।',
    attribution: 'शहरों का डेटा city-timezones (MIT) से।',
  },
  textField: {
    clear: 'साफ़ करें',
  },
  error: {
    title: 'कुछ गड़बड़ हो गई',
    retry: 'फिर से कोशिश करें',
  },
  notFound: {
    title: 'नहीं मिला',
    body: 'वह स्क्रीन मौजूद नहीं है।',
  },
}
