import type { Strings } from './en'

/**
 * Japanese interface copy, polite です/ます style. A complete draft, written in
 * one pass and not yet reviewed by a qualified speaker; the review is a release
 * condition. Japanese has no plural, so counts take a counter (回, 日, 件)
 * rather than a helper. Content text (adhkar, duas, evidence) does not live here.
 */
export const ja: Strings = {
  tabs: {
    today: '今日',
    library: 'ライブラリ',
    more: 'その他',
  },
  today: {
    title: '今日',
    nothingElse: '今日はほかに求められていることはありません。',
    empty: 'まだ何もありません。',
    needsLocationTitle: 'どちらにいますか？',
    needsLocation:
      '礼拝の時間帯、ヒジュラ暦の日付、そしてその日に求められることはすべて、おおよその位置から決まります。位置はこのスマートフォンの中で計算され、どこにも送信されません。',
    chooseCity: '代わりに都市を選ぶ',
    chooseCityDetail: '許可は不要です。すべてそのまま使えます。',
  },
  plan: {
    rightNow: '今',
    tryOneMore: 'もうひとつ試す',
    add: '追加',
    notNow: '今はしない',
    alsoNow: 'こちらも今',
    upNext: '次',
    before: '前',
    after: '後',
    soon: 'まもなく',
    inAboutAnHour: 'あと1時間ほど',
    inAboutHours: (hours: number): string => `あと${hours}時間ほど`,
    context: '今いる状況',
    comingUp: '今週このあと',
    alsoToday: '今日はほかに',
    tomorrow: '明日',
    inDays: (days: number): string => `${days}日後`,
    prayers: '礼拝',
    optional: '任意',
    expected: '予定',
    confirmLocally: '地元の機関に確認してください',
    prayed: '礼拝しました',
    makeUp: '補う礼拝',
    outstanding: (count: number): string => `補う礼拝 ${count}回`,
  },
  prayer: {
    fajr: 'ファジュル',
    dhuhr: 'ズフル',
    asr: 'アスル',
    maghrib: 'マグリブ',
    isha: 'イシャー',
  },
  window: {
    fajr: 'ファジュル',
    sunrise: '朝',
    dhuhr: 'ズフルの後',
    asr: '夕方',
    maghrib: 'マグリブの後',
    isha: '夜',
  },
  notifications: {
    title: 'リマインダー',
    windows: '朝と夕べのアズカール',
    lookAhead: 'これからの断食の日',
    prayers: '礼拝のリマインダー',
    prayersDetail: '初期設定はオフです。アザーンのアプリがすでに知らせてくれます。',
    quietHours: 'おやすみ時間',
    quietHoursDetail: (from: number, to: number): string => `${from}:00〜${to}:00`,
    quietHoursOff: 'オフ',
    perDay: '1日の上限',
    permission: '通知の許可',
    permissionGranted: '許可済み',
    permissionDenied: 'システム設定でオフになっています',
    permissionUndetermined: 'まだ確認していません',
    permissionUnavailable: 'この端末では利用できません',
    openSettings: 'システム設定を開く',
    whichItems: '対象の項目',
    whichItemsDetail: '知らせるタイミングがある項目だけがここに表示されます。',
    sendTest: 'テストのリマインダーを送る',
    sendTestDetail: '数秒で届きます。',
    testTitle: 'テストのリマインダー',
    testBody: 'Ihsaanlyのリマインダーはこのように届きます。',
    action: {
      done: '完了',
      later: 'あとで',
    },
    body: {
      window: '今です。時間帯が終わるまで。',
      windowUntil: (closes: string): string => `${closes}まで開いています。`,
      tomorrow: '明日です。',
      prayerWindow: '礼拝の時間に入りました。次の礼拝まで時間帯は続きます。',
    },
  },
  event: {
    ascending: '上るとき',
    descending: '下るとき',
    driving: '運転中',
    travel: '旅行中',
    'leaving-home': '家を出るとき',
    'entering-home': '家に帰ったとき',
  },
  events: {
    title: '今いる状況',
    explanation:
      'こうした場面の多くは、エレベーターや坂や階段のように、スマートフォンではまったく検知できません。そのドゥアーは、ライブラリとウィジェットからワンタップで開けます。',
    detectHome: '家を出たら気づかせる',
    detectHomeDetail:
      'おおよその検知です。玄関から100メートルほど離れたところで、最大1分ほど遅れて気づくので、その瞬間ではなくきっかけと考えてください。',
    setHome: '今いる場所を自宅に設定',
    homeUnset: '未設定',
    homeNeeded: 'まだ何も見守っていません。下で自宅を設定してください。',
    noPlaceYet: '先に今いる場所を設定してください',
    manual: '代わりに自分で伝える',
    manualDetail: 'センサーで分からないときは、自分で状況を知らせます。',
  },
  qada: {
    title: '補う礼拝',
    intro:
      '記録を始める前からの礼拝と、その後に補うことになった礼拝です。一覧ではなく、回数だけを記録します。数え始めるのは、最初に礼拝を記録したときからです。',
    owed: '以前からの分',
    madeUp: '今補った分',
    record: (count: number): string => (count === 1 ? '1回記録する' : `${count}回記録する`),
    outstanding: (count: number): string => `残り${count}回`,
    none: '補う礼拝はありません',
    summary: (count: number): string => `補う礼拝 ${count}回`,
    manage: '補う回数を調整',
    manageDetail: '持ち越す回数の設定と、補った礼拝の記録をまとめて行えます。',
  },
  fasting: {
    title: '断食',
    intro:
      '断食しなかったラマダーンの日と、以前から補うことになっている日です。一覧ではなく、日数だけを記録します。',
    notFastingToday: '今日は断食しない',
    notFastingTodayDetail: 'あとで補う断食を1日分残します。',
    recordedToday: '記録しました：今日は断食しない',
    undo: 'タップして取り消す',
    summary: (count: number): string => `補う断食 ${count}日`,
    outstanding: (count: number): string => `残り${count}日`,
    none: '補う断食はありません',
    owed: '以前からの分',
    recordMadeUp: '1日補ったと記録する',
  },
  history: {
    title: '履歴',
    empty: 'まだ何も記録されていません。',
    firstWeek:
      '礼拝を記録したり項目を終えたりした日は、ここに残ります。1週間たつと、どの礼拝を早めに行うことが多いか、どの項目を続けているかが見えてきます。',
    daysActive: (days: number): string => `${days}日分の記録`,
    prayers: '礼拝',
    completed: '完了した項目',
    times: (count: number): string => `${count}回`,
    early: (minutes: number): string => `たいてい時間帯に入って約${minutes}分後`,
    late: (minutes: number): string => `たいてい時間帯が終わる約${minutes}分前`,
  },
  data: {
    title: 'あなたのデータ',
    explanation:
      'ここにあるものはすべてこの端末の中にあります。この画面から自分で送らない限り、外に出ることはありません。',
    export: 'データを書き出す',
    exportDetail: '保管したり、別の端末に移したりできる読みやすいテキストです。',
    importing: 'ファイルから読み込む',
    importDetail: '置き換えずに統合します。同じファイルを2回読み込んでも何も変わりません。',
    diagnostics: '診断レポートを送る',
    diagnosticsDetail:
      '問題を直すためのものです。設定、実践の記録、おおよその座標、最近のエラーが含まれます。送る前に内容を確認できます。',
    imported: (count: number): string => `${count}件を追加しました。`,
    importFailed: 'このファイルは読み込めませんでした。',
    shareFailed: 'この端末では共有を利用できません。',
    delete: 'データを削除',
    deleteDetail:
      'この端末にある設定と実践の記録のすべてです。アプリは最初からやり直しになります。',
    deleteConfirmTitle: 'すべて削除しますか？',
    deleteConfirmBody:
      '設定と実践の記録がこの端末から削除されます。書き出していない限り、ほかのどこにもコピーはありません。',
    deleteConfirm: '削除',
    cancel: 'キャンセル',
  },
  diagnostics: {
    title: '診断レポート',
    explanation:
      'レポートにはこの内容が含まれます。送ると決めるまで何も送信されず、送り先も自分で選べます。',
    version: 'アプリのバージョン',
    device: '端末',
    coordinates: 'おおよその座標',
    noCoordinates: '保存されていません',
    records: '実践の記録',
    settings: '保存された設定',
    failures: '記録された不具合',
    failuresDetail: (count: number): string => `アプリが知らせずに対処したもの ${count}件`,
    reminders: 'リマインダー',
    remindersDetail: (permission: string, pending: number): string =>
      `${permission} · 予約 ${pending}件`,
    error: '最近のエラー',
    errorIncluded: '1件含まれています',
    showRaw: 'レポート全体を表示',
    hideRaw: 'レポート全体を隠す',
    send: '送る',
    cancel: '今はしない',
  },
  about: {
    title: 'このアプリについて',
    version: 'バージョン',
    content: 'コンテンツ',
    contentUnreviewed: (count: number): string =>
      `${count}項目。下書きで、名前を明示した学者による確認を待っています。`,
    contentReviewedBy: (name: string, count: number): string =>
      `${count}項目。${name}が確認しました。`,
    donate: '寄付する',
    donateBody:
      '任意で、寄付しても何かが解放されるわけではありません。アプリのすべての機能は無料で、これからも無料です。ブラウザで開きます。',
    privacyPolicy: 'プライバシーポリシー',
    privacyTitle: 'このスマートフォンから何も出ていきません',
    privacyBody:
      'Ihsaanlyにはアカウントもサーバーも分析もありません。位置は礼拝時刻を計算するために端末上で使われ、ここにだけ保存されます。実践の記録もここにだけ保存されます。自分で書き出したり共有したりしない限り、何もどこにも送信されません。「寄付する」はアプリから外へ出る唯一のリンクです。ブラウザが開き、そのページはIhsaanlyの一部ではありません。',
    licences: '使用しているもの',
    licencesBody:
      'ExpoとReact Native、礼拝時刻のためのadhanライブラリ、ウンム・アル＝クラー暦の表、city-timezonesの都市データ、そして地図のためのNatural Earthです。それぞれ独自のオープンライセンスのもとで使用しており、ソースリポジトリに一覧があります。',
  },
  memorise: {
    title: '覚える',
    start: '練習する',
    hide: 'もうひとつ隠す',
    known: '覚えました',
    knownDetail: 'ライブラリには残ります。リマインダーには表示されなくなります。',
    notKnown: 'まだ練習中',
    noAudio: 'これにはまだ朗誦の音声がありません。',
    play: '再生',
    stop: '停止',
    loop: '繰り返し',
  },
  language: {
    title: '言語',
    restart:
      'アラビア語は右から左に読みます。アラビア語への切り替え、またはアラビア語からの切り替えでは、アプリが再起動するか、開き直すようお願いします。',
    incomplete:
      '原文は英語です。ほかの言語はすべて下書きで、資格のある話者による確認を待っています。',
    reopenTitle: 'Ihsaanlyを開き直してください',
    reopenBody:
      'この言語は右から左に読みます。変更を完了するには、Ihsaanlyを閉じてからもう一度開いてください。',
    names: {
      en: 'English',
      ar: 'العربية',
      fr: 'Français',
      it: 'Italiano',
      ja: '日本語',
      hi: 'हिन्दी',
      ur: 'اردو',
      so: 'Soomaali',
      zh: '中文（普通话）',
      yue: '廣東話',
    },
  },
  appearance: {
    title: '外観',
    system: 'システム',
    light: 'ライト',
    dark: 'ダーク',
    note: '色はシステムから取得するため、どちらを選んでもシステムのコントラスト設定が適用されます。',
  },
  moonSighting: {
    title: '新月の目視',
    explanation:
      'このアプリの日付は計算によるものです。計算に従うか地元での新月の目視に従うかは共同体によって異なり、両者は1日ずれることがよくあります。自分の共同体が従うものに従い、アプリがそれと一致するよう設定で日付を調整してください。',
    disclaimer:
      '自分の共同体の機関を見つけられるよう載せています。このアプリはどれも推奨していません。',
  },
  tracking: {
    title: '記録',
    active: '記録中',
    travelling: '旅行中',
    travellingDetail:
      '礼拝の短縮が案内され、定例のスンナの礼拝は控えめになり、断食は求められるものではなく任意として案内されます。',
    paused: '礼拝の記録を一時停止',
    pausedDetail: '礼拝は記録されず、補う礼拝も増えません。自分でオンに戻すまで停止したままです。',
  },
  hijri: {
    title: 'ヒジュラ暦の日付',
    offset: '日付を調整',
    approximate: '計算による日付です。自分の共同体が従う機関に確認してください。',
    explanation:
      '計算による暦と地元での新月の目視は、1〜2日ずれることがよくあります。アプリが自分の共同体と一致するよう、ここで日付をずらしてください。断食の日の日付は常に予定として表示され、確定としては表示されません。',
    offsetLabel: (days: number): string =>
      days === 0 ? '変更なし' : `${days > 0 ? '+' : ''}${days}日`,
    format: (day: number, month: string, year: number): string => `${year}年 ${month} ${day}日`,
  },
  hijriMonth: {
    1: 'ムハッラム',
    2: 'サファル',
    3: 'ラビーウ・アル＝アウワル',
    4: 'ラビーウ・アッ＝サーニー',
    5: 'ジュマーダー・アル＝ウーラー',
    6: 'ジュマーダー・アル＝アーヒラ',
    7: 'ラジャブ',
    8: 'シャアバーン',
    9: 'ラマダーン',
    10: 'シャウワール',
    11: 'ズー・アル＝カアダ',
    12: 'ズー・アル＝ヒッジャ',
  },
  calculation: {
    title: '礼拝時刻の計算',
    method: '計算方法',
    asr: 'アスル',
    highLatitude: '高緯度',
    selected: '選択中',
    explanation:
      '礼拝時刻はこの端末で計算され、時計の時刻として表示されることはありません。今が一日のどの部分かを決めるためだけに使われます。',
    highLatitudeExplanation:
      '北緯およそ48度より北では、一年の一時期イシャーの時刻が訪れません。その代わりに何を使うかをここで決めます。',
  },
  asr: {
    shafi: '標準',
    hanafi: 'ハナフィー派',
  },
  highLatitude: {
    middleofthenight: '夜の中間',
    seventhofthenight: '夜の7分の1',
    twilightangle: '薄明の角度',
  },
  method: {
    MuslimWorldLeague: 'ムスリム世界連盟',
    Egyptian: 'エジプト測量総局',
    Karachi: 'カラチ・イスラーム科学大学',
    UmmAlQura: 'ウンム・アル＝クラー（マッカ）',
    Dubai: 'ドバイ',
    MoonsightingCommittee: 'ムーンサイティング委員会',
    NorthAmerica: 'ISNA（北米）',
    Kuwait: 'クウェート',
    Qatar: 'カタール',
    Singapore: 'シンガポール',
    Tehran: 'テヘラン',
    Turkey: 'トルコ',
  },
  library: {
    title: 'ライブラリ',
    empty: 'アズカール、ドゥアー、スンナの行いがここに並びます。',
    search: '名前や場面で検索',
    noResults: '一致するものはありません。',
    filterAll: 'すべて',
    filterOnToday: '今日に表示',
    filterKnown: '覚えた',
    onToday: '今日に表示',
    known: '覚えた',
    emptyOnToday: 'まだ「今日」に表示しているものはありません。項目を開いてオンにしてください。',
    emptyKnown: 'まだ覚えたものはありません。項目を練習して、覚えたら知らせてください。',
    terms: '用語集',
    termsDetail: 'スンナ、ラワーティブ、アズカール、カダーなどを、それぞれ一文で。',
  },
  category: {
    adhkar: 'アズカール',
    dhikr: '礼拝の後',
    fasting: '断食',
    food: '食事',
    home: '家',
    masjid: 'マスジド',
    prayer: '礼拝',
    sleep: '眠りと目覚め',
    travel: '旅',
  },
  item: {
    done: '完了',
    doneToday: '今日完了',
    undo: '取り消す',
    counterReset: 'やり直す',
    yourDay: 'あなたの一日',
    onToday: '今日に表示',
    onTodayDetail: 'その時が来たら表示されます',
    remind: '知らせる',
    remindWindow: '時間帯が始まるとき',
    remindLookAhead: '前日の夕方',
    share: '共有',
    shareText: 'テキストで共有',
    shareImage: '画像で共有',
    sharedFrom: 'Ihsaanlyから共有',
    transliteration: '読み方',
    translation: '意味',
    why: 'なぜ',
    how: 'やり方',
    unreviewed: '確認待ち',
    evidence: '根拠',
    note: '学者の見解の相違',
    repeat: (times: number): string => `${times}回繰り返す`,
    parts: '唱える言葉',
    partRepeat: (times: number): string => `${times}回`,
    gradedBy: (grader: string): string => `${grader}による判定`,
    quranReference: (surah: number, ayah: number): string => `クルアーン ${surah}章${ayah}節`,
  },
  glossary: {
    title: '用語の意味',
  },
  ruling: {
    fard: '義務',
    wajib: '義務',
    'sunnah-muakkadah': '強く勧められたスンナ',
    sunnah: 'スンナ',
    mustahabb: '推奨',
    mubah: '許容',
  },
  grading: {
    sahih: 'サヒーフ（真正）',
    hasan: 'ハサン（良好）',
    "da'if": 'ダイーフ（弱い）',
    disputed: '見解が分かれる',
  },
  more: {
    title: 'その他',
    search: '設定を検索',
    prayer: '礼拝',
    app: 'アプリ',
    practice: 'あなたの実践',
    empty: '履歴、設定、ヘルプはここに置かれます。',
  },
  onboarding: {
    welcomeTitle: '時計ではなく、その時を。',
    welcomeBody:
      'Ihsaanlyは、夕べのアズカールの時間が始まったことを知らせます。時刻は表示しません。点数もつけません。',
    howTitle: '礼拝を記録すると、スンナが現れます。',
    howBody:
      'ズフルを礼拝したらタップしてください。その後に続くズィクルが待っています。このスマートフォンから何も出ていきません。アカウントもサーバーもありません。',
    language: '言語',
    appearance: '外観',
    howSample: 'سُبْحَانَ اللهِ وَبِحَمْدِهِ',
    locationStep: 'どちらにいますか？',
    locationWhy: '一日の区切りを計算するために、この端末上で使います。どこにも送信されません。',
    genderStep: '記録の一時停止',
    genderWhy:
      '礼拝の記録を止めるべき日があり、その間は補う礼拝も増えません。一時停止を案内するかどうかを、アプリがここで判断します。',
    brother: '男性',
    brotherDetail: '一時停止なし',
    sister: '女性',
    sisterDetail: '一時停止を案内',
    skip: '答えない',
    skipDetail: 'いずれにしても一時停止は案内されます。',
    genderPrivacy: 'この端末に保存されます。どこにも送信されず、ほかの目的には使われません。',
    remindersStep: 'リマインダー',
    remindersWhy: '1日に2〜3回、夜中には届きません。あとで「その他」からいつでも変更できます。',
    windowsDetail: 'それぞれの時間帯が始まるとき',
    lookAheadDetail: '前日の夕方',
    startStep: 'はじめの一歩',
    startWhy: 'まずは量を選んでください。ライブラリでいつでも追加したり外したりできます。',
    starting: 'はじめたばかり',
    startingDetail: (count: number): string =>
      `初日から続けられる${count}項目。2つの時間帯、1つのズィクル、2つのドゥアーです。すべてが初めての人に。`,
    essentials: '基本',
    essentialsDetail: (count: number): string =>
      `${count}項目。すべてではなく、無理のない一日です。すでに礼拝していて、その前後のスンナを加えたい人に。`,
    everything: 'すべて',
    everythingDetail: (count: number): string =>
      `全${count}項目。内容をよく知っていて、暦のすべてを使いたい人に。`,
    skipIntro: 'スキップ',
    skipLocation: '今はスキップ',
    reminderPolicy: (perDay: number, from: number, to: number): string =>
      `1日に最大${perDay}回、${from}:00〜${to}:00には届きません。`,
    reminderCap: (perDay: number): string => `1日に最大${perDay}回。`,
    included: '含まれるもの',
    andMore: (count: number): string => `ほか${count}件`,
    back: '戻る',
    continue: '続ける',
    allowReminders: 'リマインダーを許可',
    notNow: '今はしない',
    done: 'はじめる',
  },
  location: {
    title: '位置',
    notSet: '未設定',
    currentLocation: '現在地',
    useDevice: '現在地を使う',
    useDeviceDetail: 'このスマートフォンから何も出ていきません。',
    locating: '現在地を確認しています…',
    orSearch: 'または都市を検索',
    follows: '礼拝の時間帯はこの場所に基づきます。',
    search: '都市を検索',
    noResults: '一致する都市はありません。',
    unavailable:
      'この端末では位置情報サービスがオフになっています。オンにするか、代わりに都市を検索してください。',
    declined:
      '位置情報へのアクセスが許可されませんでした。代わりに都市を検索してください。すべてそのまま使えます。',
    explanation: '礼拝の時間帯を計算するために、この端末上で使います。どこにも送信されません。',
    attribution: '都市データ：city-timezones（MIT）',
  },
  textField: {
    clear: 'クリア',
  },
  error: {
    title: '問題が発生しました',
    retry: 'もう一度試す',
  },
  notFound: {
    title: '見つかりません',
    body: 'その画面は存在しません。',
  },
}
