import type { Strings } from './en'

/**
 * Urdu interface copy. A complete draft, written in one pass and awaiting
 * review by a qualified speaker; the review is a release condition. Content
 * text (adhkar, duas, evidence) does not live here.
 */

/** Urdu counts: the number, then the singular for one and the plural otherwise. */
function count(n: number, one: string, many: string): string {
  return `${n} ${n === 1 ? one : many}`
}

export const ur: Strings = {
  tabs: {
    today: 'آج',
    library: 'کتب خانہ',
    more: 'مزید',
  },
  today: {
    title: 'آج',
    nothingElse: 'آج آپ سے اور کچھ مطلوب نہیں۔',
    empty: 'ابھی یہاں کچھ نہیں۔',
    needsLocationTitle: 'آپ کہاں ہیں؟',
    needsLocation:
      'نماز کے اوقات، ہجری تاریخ اور دن کا ہر عمل ایک اندازاً مقام سے طے ہوتا ہے۔ یہ اسی فون پر حساب ہوتا ہے اور کہیں نہیں بھیجا جاتا۔',
    chooseCity: 'اس کے بجائے شہر منتخب کریں',
    chooseCityDetail: 'کسی اجازت کی ضرورت نہیں۔ سب کچھ پھر بھی چلتا ہے۔',
  },
  plan: {
    rightNow: 'ابھی',
    tryOneMore: 'ایک اور آزمائیں',
    add: 'شامل کریں',
    notNow: 'ابھی نہیں',
    alsoNow: 'یہ بھی ابھی',
    upNext: 'اس کے بعد',
    before: 'پہلے',
    after: 'بعد',
    soon: 'جلد',
    inAboutAnHour: 'تقریباً ایک گھنٹے میں',
    inAboutHours: (hours: number): string => `تقریباً ${hours} گھنٹوں میں`,
    context: 'آپ کہاں ہیں',
    comingUp: 'اس ہفتے آگے',
    alsoToday: 'یہ بھی آج',
    tomorrow: 'کل',
    inDays: (days: number): string => `${days} دن میں`,
    prayers: 'نمازیں',
    optional: 'اختیاری',
    expected: 'متوقع',
    confirmLocally: 'اپنے مقامی ادارے سے تصدیق کریں',
    prayed: 'پڑھ لی',
    makeUp: 'قضا باقی',
    outstanding: (n: number): string => `${count(n, 'نماز', 'نمازیں')} قضا باقی`,
  },
  prayer: {
    fajr: 'فجر',
    dhuhr: 'ظہر',
    asr: 'عصر',
    maghrib: 'مغرب',
    isha: 'عشاء',
  },
  window: {
    fajr: 'فجر',
    sunrise: 'صبح',
    dhuhr: 'ظہر کے بعد',
    asr: 'شام',
    maghrib: 'مغرب کے بعد',
    isha: 'رات',
  },
  notifications: {
    title: 'یاد دہانیاں',
    windows: 'صبح و شام کے اذکار',
    lookAhead: 'آنے والے روزوں کے دن',
    prayers: 'نماز کی یاد دہانیاں',
    prayersDetail: 'شروع میں بند — آپ کی اذان والی ایپ یہ کام پہلے ہی کرتی ہے۔',
    quietHours: 'خاموش اوقات',
    quietHoursDetail: (from: number, to: number): string => `${from}:00 سے ${to}:00 تک`,
    quietHoursOff: 'بند',
    perDay: 'روزانہ کی حد',
    permission: 'اجازت',
    permissionGranted: 'اجازت ہے',
    permissionDenied: 'سسٹم کی ترتیبات میں بند ہے',
    permissionUndetermined: 'ابھی پوچھا نہیں گیا',
    permissionUnavailable: 'اس آلے پر دستیاب نہیں',
    openSettings: 'سسٹم کی ترتیبات کھولیں',
    whichItems: 'کون سے اعمال',
    whichItemsDetail: 'یہاں صرف وہ اعمال نظر آتے ہیں جن کا کوئی وقت یاد دلانے کے لیے ہو۔',
    sendTest: 'آزمائشی یاد دہانی بھیجیں',
    sendTestDetail: 'چند سیکنڈ میں پہنچ جائے گی۔',
    testTitle: 'ایک آزمائشی یاد دہانی',
    testBody: 'احسانلی کی یاد دہانی ایسی دکھتی ہے۔',
    action: {
      done: 'ہو گیا',
      later: 'بعد میں',
    },
    body: {
      window: 'ابھی، جب تک وقت باقی ہے۔',
      windowUntil: (closes: string): string => `${closes} تک کھلا ہے۔`,
      tomorrow: 'کل۔',
      prayerWindow: 'وقت داخل ہو گیا ہے۔ اگلی نماز تک وقت باقی رہتا ہے۔',
    },
  },
  event: {
    ascending: 'اوپر جاتے ہوئے',
    descending: 'نیچے آتے ہوئے',
    driving: 'گاڑی چلاتے ہوئے',
    travel: 'سفر میں',
    'leaving-home': 'گھر سے نکلتے ہوئے',
    'entering-home': 'گھر آتے ہوئے',
  },
  events: {
    title: 'آپ کہاں ہیں',
    explanation:
      'ان میں سے اکثر لمحے فون پہچان ہی نہیں سکتا — لفٹ، پہاڑی، سیڑھی۔ ان کی دعائیں کتب خانے اور ویجٹ پر ایک ٹیپ کی دوری پر ہیں۔',
    detectHome: 'جب میں گھر سے نکلوں تو پہچانیں',
    detectHomeDetail:
      'اندازاً۔ فون دروازے سے تقریباً سو میٹر دور اور ایک منٹ تک کی تاخیر سے پہچانتا ہے، اس لیے اسے ٹھیک لمحہ نہیں بلکہ ایک اشارہ سمجھیں۔',
    setHome: 'میری موجودہ جگہ کو گھر بنائیں',
    homeUnset: 'مقرر نہیں',
    homeNeeded: 'ابھی کچھ نہیں دیکھا جا رہا — نیچے گھر مقرر کریں۔',
    noPlaceYet: 'پہلے اپنا مقام مقرر کریں',
    manual: 'اس کے بجائے ایپ کو خود بتائیں',
    manualDetail: 'جب کوئی سینسر نہ پہچان سکے تو حالت خود بتا دیں۔',
  },
  qada: {
    title: 'قضا',
    intro:
      'وہ نمازیں جو ریکارڈ شروع کرنے سے پہلے کی آپ کے ذمے ہیں، اور اس کے بعد کی بھی۔ صرف گنتی، کبھی فہرست نہیں۔ گنتی آپ کی پہلی نشان زد نماز سے شروع ہوتی ہے۔',
    owed: 'پہلے سے ذمے',
    madeUp: 'اب ادا کی گئیں',
    record: (n: number): string => (n === 1 ? 'ایک درج کریں' : `${n} درج کریں`),
    outstanding: (n: number): string => `${n} ذمے`,
    none: 'کچھ ذمے نہیں',
    summary: (n: number): string => `${count(n, 'نماز', 'نمازیں')} ذمے`,
    manage: 'اپنی قضا درست کریں',
    manageDetail: 'جو پہلے سے ذمے ہے وہ مقرر کریں اور ادا کی گئی قضا ایک ساتھ درج کریں۔',
  },
  fasting: {
    title: 'روزے',
    intro: 'رمضان کے وہ دن جن کا روزہ نہیں رکھا، اور پہلے سے ذمے روزے۔ صرف گنتی، کبھی فہرست نہیں۔',
    notFastingToday: 'آج روزہ نہیں',
    notFastingTodayDetail: 'بعد میں قضا کے لیے ایک روزہ درج کرتا ہے۔',
    recordedToday: 'درج ہو گیا: آج روزہ نہیں',
    undo: 'واپس لینے کے لیے ٹیپ کریں',
    summary: (n: number): string => `${count(n, 'روزہ', 'روزے')} قضا باقی`,
    outstanding: (n: number): string => `${n} ذمے`,
    none: 'کچھ ذمے نہیں',
    owed: 'پہلے سے ذمے',
    recordMadeUp: 'ایک قضا روزہ درج کریں',
  },
  history: {
    title: 'ریکارڈ',
    empty: 'ابھی کچھ درج نہیں۔',
    firstWeek:
      'جس دن آپ کوئی نماز نشان زد کریں یا کوئی عمل مکمل کریں، وہ یہاں محفوظ ہوتا ہے۔ ایک ہفتے بعد آپ دیکھیں گے کہ کون سی نمازیں آپ عموماً جلدی پڑھتے ہیں اور کون سے اعمال آپ جاری رکھتے ہیں۔',
    daysActive: (days: number): string => `${days} دن درج`,
    prayers: 'نمازیں',
    completed: 'مکمل',
    times: (n: number): string => `${n} بار`,
    early: (minutes: number): string => `عموماً وقت شروع ہونے کے تقریباً ${minutes} منٹ بعد`,
    late: (minutes: number): string => `عموماً وقت ختم ہونے سے تقریباً ${minutes} منٹ پہلے`,
  },
  data: {
    title: 'آپ کا ڈیٹا',
    explanation:
      'یہاں کی ہر چیز اسی آلے پر ہے۔ کچھ بھی باہر نہیں جاتا جب تک آپ خود اس اسکرین سے نہ بھیجیں۔',
    export: 'میرا ڈیٹا برآمد کریں',
    exportDetail: 'پڑھنے کے قابل متن جو آپ رکھ سکیں یا دوسرے آلے پر لے جا سکیں۔',
    importing: 'فائل سے درآمد کریں',
    importDetail: 'بدلتا نہیں بلکہ ملاتا ہے۔ ایک ہی فائل دو بار درآمد کرنے سے کچھ نہیں بدلتا۔',
    diagnostics: 'تشخیصی رپورٹ بھیجیں',
    diagnosticsDetail:
      'کسی مسئلے کو ٹھیک کرنے کے لیے۔ اس میں آپ کی ترتیبات، آپ کے عمل کا ریکارڈ، آپ کے اندازاً محلِ وقوع اور حالیہ خرابیاں ہوتی ہیں۔ بھیجنے سے پہلے آپ اسے دیکھ لیں گے۔',
    imported: (n: number): string => `${count(n, 'اندراج', 'اندراجات')} شامل ہوئے۔`,
    importFailed: 'وہ فائل پڑھی نہیں جا سکی۔',
    shareFailed: 'اس آلے پر شیئر کرنا دستیاب نہیں۔',
    delete: 'میرا ڈیٹا حذف کریں',
    deleteDetail: 'اس آلے پر سب کچھ: ترتیبات اور آپ کے عمل کا ریکارڈ۔ ایپ نئے سرے سے شروع ہو گی۔',
    deleteConfirmTitle: 'سب کچھ حذف کریں؟',
    deleteConfirmBody:
      'آپ کی ترتیبات اور عمل کا ریکارڈ اس آلے سے ہٹا دیے جائیں گے۔ اس کی کوئی نقل کہیں اور نہیں، سوائے اس کے جو آپ نے برآمد کی ہو۔',
    deleteConfirm: 'حذف کریں',
    cancel: 'منسوخ',
  },
  diagnostics: {
    title: 'تشخیصی رپورٹ',
    explanation:
      'رپورٹ میں یہ کچھ ہے۔ جب تک آپ بھیجنے کا فیصلہ نہ کریں کچھ نہیں بھیجا جاتا، اور کہاں جائے یہ آپ چنتے ہیں۔',
    version: 'ایپ کا ورژن',
    device: 'آلہ',
    coordinates: 'اندازاً محلِ وقوع',
    noCoordinates: 'کچھ محفوظ نہیں',
    records: 'عمل کے ریکارڈ',
    settings: 'محفوظ ترتیبات',
    failures: 'درج خرابیاں',
    failuresDetail: (n: number): string => `${n} جنہیں ایپ نے آپ کو بتائے بغیر سنبھال لیا`,
    reminders: 'یاد دہانیاں',
    remindersDetail: (permission: string, pending: number): string =>
      `${permission} · ${pending} قطار میں`,
    error: 'حالیہ خرابی',
    errorIncluded: 'ایک شامل ہے',
    showRaw: 'پوری رپورٹ دکھائیں',
    hideRaw: 'پوری رپورٹ چھپائیں',
    send: 'بھیج دیں',
    cancel: 'ابھی نہیں',
  },
  about: {
    title: 'تعارف',
    version: 'ورژن',
    content: 'مواد',
    contentUnreviewed: (n: number): string =>
      `${count(n, 'عمل', 'اعمال')}، مسودہ جو ایک نامزد عالم کی نظرِ ثانی کا منتظر ہے۔`,
    contentReviewedBy: (name: string, n: number): string =>
      `${count(n, 'عمل', 'اعمال')}، جن پر ${name} نے نظرِ ثانی کی۔`,
    donate: 'عطیہ دیں',
    donateBody:
      'اختیاری، اور اس سے کچھ بھی کھلتا نہیں۔ ایپ کا ہر حصہ مفت ہے اور مفت رہے گا۔ آپ کے براؤزر میں کھلتا ہے۔',
    privacyPolicy: 'رازداری کی پالیسی',
    privacyTitle: 'کچھ بھی اس فون سے باہر نہیں جاتا',
    privacyBody:
      'احسانلی میں نہ کوئی اکاؤنٹ ہے، نہ سرور، نہ تجزیاتی نگرانی۔ آپ کا مقام نماز کے اوقات کا حساب لگانے کے لیے آلے پر استعمال ہوتا ہے اور صرف یہیں محفوظ رہتا ہے۔ آپ کے عمل کا ریکارڈ صرف یہیں محفوظ رہتا ہے۔ کچھ بھی کہیں نہیں بھیجا جاتا جب تک آپ خود برآمد یا شیئر نہ کریں۔ عطیہ ایپ سے باہر جانے والا واحد لنک ہے: یہ آپ کا براؤزر کھولتا ہے، اور وہ صفحہ احسانلی کا حصہ نہیں۔',
    licences: 'جن سے بنی ہے',
    licencesBody:
      'Expo اور React Native، نماز کے اوقات کے لیے adhan لائبریری، ام القریٰ کیلنڈر کی جدولیں، city-timezones سے شہروں کا ڈیٹا، اور نقشے کے لیے Natural Earth۔ ہر ایک اپنے کھلے لائسنس کے تحت استعمال ہوا ہے، جو سورس ریپوزیٹری میں درج ہے۔',
  },
  memorise: {
    title: 'یاد کریں',
    start: 'مشق کریں',
    hide: 'ایک اور چھپائیں',
    known: 'مجھے یاد ہے',
    knownDetail: 'یہ کتب خانے میں رہتا ہے۔ یاد دہانیوں میں آنا بند ہو جاتا ہے۔',
    notKnown: 'ابھی یاد نہیں',
    noAudio: 'اس کی ابھی کوئی تلاوت نہیں۔',
    play: 'چلائیں',
    stop: 'روکیں',
    loop: 'دہرائیں',
  },
  language: {
    title: 'زبان',
    restart:
      'عربی اور اردو دائیں سے بائیں پڑھی جاتی ہیں۔ ان پر یا ان سے زبان بدلنے پر ایپ دوبارہ شروع ہوتی ہے، یا آپ سے اسے دوبارہ کھولنے کو کہتی ہے۔',
    incomplete:
      'اصل انگریزی ہے۔ باقی ہر زبان ایک مسودہ ہے جو ابھی کسی اہل زبان کی نظرِ ثانی کا منتظر ہے۔',
    reopenTitle: 'احسانلی دوبارہ کھولیں',
    reopenBody:
      'یہ زبان دائیں سے بائیں پڑھی جاتی ہے۔ تبدیلی مکمل کرنے کے لیے احسانلی بند کر کے دوبارہ کھولیں۔',
    names: {
      en: 'English',
      ar: 'العربية',
      fr: 'Français',
      it: 'Italiano',
      ja: '日本語',
      hi: 'हिन्दी',
      ur: 'اردو',
      so: 'Soomaali',
      zh: '中文（普通话）',
      yue: '廣東話',
    },
  },
  appearance: {
    title: 'ظاہری شکل',
    system: 'سسٹم',
    light: 'روشن',
    dark: 'تاریک',
    note: 'رنگ اب بھی سسٹم سے آتے ہیں، اس لیے اس کی کنٹراسٹ کی ترتیبات دونوں صورتوں میں لاگو رہتی ہیں۔',
  },
  moonSighting: {
    title: 'رؤیتِ ہلال',
    explanation:
      'اس ایپ میں تاریخیں حساب سے ہیں۔ کمیونٹیز میں اختلاف ہے کہ حساب کی پیروی کی جائے یا مقامی رؤیت کی، اور دونوں میں اکثر ایک دن کا فرق ہوتا ہے۔ جس کی پیروی آپ کی اپنی کمیونٹی کرتی ہے اسی کی کریں، اور ترتیبات میں تاریخ درست کر لیں تاکہ ایپ ان کے مطابق ہو۔',
    disclaimer:
      'یہ اس لیے درج ہیں کہ آپ اپنا ادارہ ڈھونڈ سکیں۔ یہ ایپ ان میں سے کسی کی تائید نہیں کرتی۔',
  },
  tracking: {
    title: 'ریکارڈ رکھنا',
    active: 'جاری',
    travelling: 'سفر میں',
    travellingDetail:
      'قصر کی پیشکش ہوتی ہے، باقاعدہ سنتیں ایک طرف ہو جاتی ہیں، اور روزہ لازم نہیں بلکہ پیشکش کے طور پر آتا ہے۔',
    paused: 'نماز کا ریکارڈ روک دیں',
    pausedDetail:
      'نمازیں درج نہیں ہوتیں اور کوئی قضا جمع نہیں ہوتی۔ یہ اس وقت تک بند رہتا ہے جب تک آپ اسے دوبارہ نہ کھولیں۔',
  },
  hijri: {
    title: 'ہجری تاریخ',
    offset: 'تاریخ درست کریں',
    approximate: 'حساب سے — اس ادارے سے تصدیق کریں جس کی آپ کی کمیونٹی پیروی کرتی ہے۔',
    explanation:
      'حساب والا کیلنڈر اور مقامی رؤیتِ ہلال اکثر ایک یا دو دن مختلف ہوتے ہیں۔ یہاں تاریخ آگے پیچھے کریں تاکہ ایپ آپ کی کمیونٹی کے مطابق ہو۔ روزوں کے دنوں کی تاریخیں ہمیشہ متوقع کے طور پر دکھائی جاتی ہیں، کبھی یقینی نہیں۔',
    offsetLabel: (days: number): string =>
      days === 0 ? 'کوئی تبدیلی نہیں' : `${days > 0 ? '+' : ''}${days} دن`,
    format: (day: number, month: string, year: number): string => `${day} ${month} ${year}`,
  },
  hijriMonth: {
    1: 'محرم',
    2: 'صفر',
    3: 'ربیع الاول',
    4: 'ربیع الثانی',
    5: 'جمادی الاولیٰ',
    6: 'جمادی الثانیہ',
    7: 'رجب',
    8: 'شعبان',
    9: 'رمضان',
    10: 'شوال',
    11: 'ذوالقعدہ',
    12: 'ذوالحجہ',
  },
  calculation: {
    title: 'نماز کے اوقات کا حساب',
    method: 'طریقہ',
    asr: 'عصر',
    highLatitude: 'بلند عرض بلد',
    selected: 'منتخب',
    explanation:
      'نماز کے اوقات اسی آلے پر حساب ہوتے ہیں اور کبھی گھڑی کے وقت کے طور پر نہیں دکھائے جاتے — یہ صرف یہ طے کرتے ہیں کہ آپ دن کے کس حصے میں ہیں۔',
    highLatitudeExplanation:
      'تقریباً 48° شمال سے اوپر، سال کے کچھ حصے میں عشاء کا وقت نہیں آتا۔ یہ طے کرتا ہے کہ اس کی جگہ کیا استعمال ہو۔',
  },
  asr: {
    shafi: 'معیاری',
    hanafi: 'حنفی',
  },
  highLatitude: {
    middleofthenight: 'آدھی رات',
    seventhofthenight: 'رات کا ساتواں حصہ',
    twilightangle: 'شفق کا زاویہ',
  },
  method: {
    MuslimWorldLeague: 'رابطہ عالم اسلامی',
    Egyptian: 'مصری جنرل اتھارٹی',
    Karachi: 'جامعہ العلوم الاسلامیہ، کراچی',
    UmmAlQura: 'ام القریٰ، مکہ مکرمہ',
    Dubai: 'دبئی',
    MoonsightingCommittee: 'مون سائٹنگ کمیٹی',
    NorthAmerica: 'ISNA، شمالی امریکہ',
    Kuwait: 'کویت',
    Qatar: 'قطر',
    Singapore: 'سنگاپور',
    Tehran: 'تہران',
    Turkey: 'ترکی',
  },
  library: {
    title: 'کتب خانہ',
    empty: 'اذکار، دعائیں اور سنت اعمال یہاں درج ہوں گے۔',
    search: 'نام یا موقع سے تلاش کریں',
    noResults: 'اس سے کچھ نہیں ملا۔',
    filterAll: 'سب',
    filterOnToday: 'آج میں شامل',
    filterKnown: 'یاد شدہ',
    onToday: 'آج میں شامل',
    known: 'یاد شدہ',
    emptyOnToday: 'ابھی آج میں کچھ شامل نہیں۔ کوئی بھی عمل کھولیں اور اسے آن کریں۔',
    emptyKnown: 'ابھی کچھ یاد شدہ نشان زد نہیں۔ کسی عمل کی مشق کریں اور یاد ہو جائے تو بتائیں۔',
    terms: 'اصطلاحات',
    termsDetail: 'سنت، سنن رواتب، اذکار، قضا اور باقی، ہر ایک ایک جملے میں۔',
  },
  category: {
    adhkar: 'اذکار',
    dhikr: 'نماز کے بعد',
    fasting: 'روزہ',
    food: 'کھانا',
    home: 'گھر',
    masjid: 'مسجد',
    prayer: 'نماز',
    sleep: 'سونا اور جاگنا',
    travel: 'سفر',
  },
  item: {
    done: 'ہو گیا',
    doneToday: 'آج ہو گیا',
    undo: 'واپس لیں',
    counterReset: 'دوبارہ شروع کریں',
    yourDay: 'آپ کا دن',
    onToday: 'آج میں شامل',
    onTodayDetail: 'اپنے وقت پر ظاہر ہوتا ہے',
    remind: 'مجھے یاد دلائیں',
    remindWindow: 'جب اس کا وقت شروع ہو',
    remindLookAhead: 'ایک شام پہلے',
    share: 'شیئر کریں',
    shareText: 'متن کے طور پر شیئر کریں',
    shareImage: 'تصویر کے طور پر شیئر کریں',
    sharedFrom: 'احسانلی سے شیئر کیا گیا',
    transliteration: 'رومن تلفظ',
    translation: 'ترجمہ',
    why: 'کیوں',
    how: 'کیسے',
    unreviewed: 'نظرِ ثانی کا منتظر',
    evidence: 'دلیل',
    note: 'علماء کا اختلاف',
    repeat: (times: number): string => `${times} بار دہرائیں`,
    parts: 'کیا پڑھیں',
    partRepeat: (times: number): string => `${times} بار`,
    gradedBy: (grader: string): string => `درجہ: ${grader}`,
    quranReference: (surah: number, ayah: number): string => `قرآن ${surah}:${ayah}`,
  },
  glossary: {
    title: 'الفاظ کے معنی',
  },
  ruling: {
    fard: 'فرض',
    wajib: 'واجب',
    'sunnah-muakkadah': 'سنتِ مؤکدہ',
    sunnah: 'سنت',
    mustahabb: 'مستحب',
    mubah: 'مباح',
  },
  grading: {
    sahih: 'صحیح',
    hasan: 'حسن',
    "da'if": 'ضعیف',
    disputed: 'مختلف فیہ',
  },
  more: {
    title: 'مزید',
    search: 'ترتیبات میں تلاش کریں',
    prayer: 'نماز',
    app: 'ایپ',
    practice: 'آپ کے اعمال',
    empty: 'ریکارڈ، ترتیبات اور مدد یہاں ہوں گی۔',
  },
  onboarding: {
    welcomeTitle: 'لمحہ، گھڑی نہیں۔',
    welcomeBody:
      'احسانلی آپ کو بتاتی ہے کہ شام کے اذکار کا وقت کب ہے۔ کبھی گھڑی کا وقت نہیں۔ کبھی نمبر نہیں۔',
    howTitle: 'آپ نماز نشان زد کریں۔ سنت سامنے آ جاتی ہے۔',
    howBody:
      'ظہر پڑھ لیں تو اس پر ٹیپ کریں، اور اس کے بعد کا ذکر منتظر ہو گا۔ کچھ بھی اس فون سے باہر نہیں جاتا۔ نہ اکاؤنٹ، نہ سرور۔',
    language: 'زبان',
    appearance: 'ظاہری شکل',
    howSample: 'سُبْحَانَ اللهِ وَبِحَمْدِهِ',
    locationStep: 'آپ کہاں ہیں؟',
    locationWhy:
      'دن کے حصے معلوم کرنے کے لیے اسی آلے پر استعمال ہوتا ہے۔ کبھی کہیں نہیں بھیجا جاتا۔',
    genderStep: 'ریکارڈ میں وقفہ',
    genderWhy:
      'کچھ دنوں میں نماز کا ریکارڈ رک جانا چاہیے، اور کوئی قضا جمع نہ ہو۔ اس سے ایپ کو معلوم ہوتا ہے کہ یہ پیشکش کرے یا نہیں۔',
    brother: 'بھائی',
    brotherDetail: 'کوئی وقفہ نہیں',
    sister: 'بہن',
    sisterDetail: 'وقفے کی پیشکش',
    skip: 'بتانا نہیں چاہتے',
    skipDetail: 'وقفے کی پیشکش پھر بھی ہو گی۔',
    genderPrivacy:
      'اسی آلے پر محفوظ۔ کبھی کہیں نہیں بھیجا جاتا، اور کسی اور کام میں استعمال نہیں ہوتا۔',
    remindersStep: 'یاد دہانیاں',
    remindersWhy: 'دن میں دو یا تین، رات میں کبھی نہیں۔ یہ سب بعد میں "مزید" میں بدل سکتے ہیں۔',
    windowsDetail: 'جب ہر وقت شروع ہو',
    lookAheadDetail: 'ایک شام پہلے',
    startStep: 'آغاز کی جگہ',
    startWhy: 'شروع کرنے کے لیے ایک مقدار چنیں۔ کتب خانے میں جب چاہیں کچھ بھی شامل کریں یا ہٹائیں۔',
    starting: 'بس شروعات',
    startingDetail: (n: number): string =>
      `${count(n, 'چیز', 'چیزیں')} جو آپ پہلے دن سے نبھا سکیں: دو اوقات، ایک ذکر، دو دعائیں۔ اس کے لیے جس کے لیے یہ سب نیا ہے۔`,
    essentials: 'بنیادی',
    essentialsDetail: (n: number): string =>
      `${count(n, 'عمل', 'اعمال')}، ایک معقول دن، مکمل نہیں۔ اس کے لیے جو پہلے سے نماز پڑھتا ہے اور اس کے ساتھ کی سنتیں چاہتا ہے۔`,
    everything: 'سب کچھ',
    everythingDetail: (n: number): string =>
      `تمام ${count(n, 'عمل', 'اعمال')}۔ اس کے لیے جو مواد جانتا ہے اور پورا کیلنڈر چاہتا ہے۔`,
    skipIntro: 'چھوڑیں',
    skipLocation: 'ابھی چھوڑ دیں',
    reminderPolicy: (perDay: number, from: number, to: number): string =>
      `دن میں زیادہ سے زیادہ ${perDay}، اور ${from}:00 سے ${to}:00 کے درمیان کچھ نہیں۔`,
    reminderCap: (perDay: number): string => `دن میں زیادہ سے زیادہ ${perDay}۔`,
    included: 'شامل',
    andMore: (n: number): string => `اور ${n} مزید`,
    back: 'واپس',
    continue: 'جاری رکھیں',
    allowReminders: 'یاد دہانیوں کی اجازت دیں',
    notNow: 'ابھی نہیں',
    done: 'شروع کریں',
  },
  location: {
    title: 'مقام',
    notSet: 'مقرر نہیں',
    currentLocation: 'موجودہ مقام',
    useDevice: 'میرا مقام استعمال کریں',
    useDeviceDetail: 'کچھ بھی اس فون سے باہر نہیں جاتا۔',
    locating: 'آپ کو تلاش کیا جا رہا ہے…',
    orSearch: 'یا کوئی شہر تلاش کریں',
    follows: 'نماز کے اوقات اس جگہ کے مطابق ہوں گے۔',
    search: 'شہر تلاش کریں',
    noResults: 'اس سے کوئی شہر نہیں ملا۔',
    unavailable:
      'اس آلے پر لوکیشن سروسز بند ہیں۔ انہیں آن کریں، یا اس کے بجائے اپنا شہر تلاش کریں۔',
    declined:
      'مقام تک رسائی کی اجازت نہیں دی گئی۔ اس کے بجائے اپنا شہر تلاش کریں — سب کچھ پھر بھی چلتا ہے۔',
    explanation:
      'نماز کے اوقات معلوم کرنے کے لیے اسی آلے پر استعمال ہوتا ہے۔ کبھی کہیں نہیں بھیجا جاتا۔',
    attribution: 'شہروں کا ڈیٹا city-timezones سے (MIT)۔',
  },
  textField: {
    clear: 'صاف کریں',
  },
  error: {
    title: 'کچھ غلط ہو گیا',
    retry: 'دوبارہ کوشش کریں',
  },
  notFound: {
    title: 'نہیں ملا',
    body: 'یہ اسکرین موجود نہیں۔',
  },
}
