import type { Strings } from './en'

/**
 * Cantonese (Traditional, Hong Kong) interface copy. A complete draft, written
 * in one pass and awaiting review by a qualified speaker; the review is a
 * release condition. Content text (adhkar, duas, evidence) does not live here.
 */
export const yue: Strings = {
  tabs: {
    today: '今日',
    library: '資料庫',
    more: '更多',
  },
  today: {
    title: '今日',
    nothingElse: '今日冇其他要做嘅喇。',
    empty: '暫時未有嘢。',
    needsLocationTitle: '你喺邊度？',
    needsLocation:
      '禮拜時段、伊斯蘭曆日期同今日要做嘅一切，都係由一個大概位置計出嚟。計算喺呢部手機上面進行，永遠唔會傳送去任何地方。',
    chooseCity: '改為揀一個城市',
    chooseCityDetail: '唔使授權，所有功能照樣用得。',
  },
  plan: {
    rightNow: '而家',
    tryOneMore: '試多一樣',
    add: '加入',
    notNow: '遲啲先',
    alsoNow: '而家仲有',
    upNext: '下一個',
    before: '之前',
    after: '之後',
    soon: '就快',
    inAboutAnHour: '大約一個鐘之後',
    inAboutHours: (hours: number): string => `大約 ${hours} 個鐘之後`,
    context: '你而家嘅情況',
    comingUp: '今個星期稍後',
    alsoToday: '今日仲有',
    tomorrow: '聽日',
    inDays: (days: number): string => `${days} 日之後`,
    prayers: '禮拜',
    optional: '自願',
    expected: '預計',
    confirmLocally: '請向你當地嘅機構確認',
    prayed: '已禮',
    makeUp: '要補禮',
    outstanding: (count: number): string => `${count} 番要補禮`,
  },
  prayer: {
    fajr: '晨禮',
    dhuhr: '晌禮',
    asr: '晡禮',
    maghrib: '昏禮',
    isha: '宵禮',
  },
  window: {
    fajr: '晨禮',
    sunrise: '上晝',
    dhuhr: '晌禮之後',
    asr: '傍晚',
    maghrib: '昏禮之後',
    isha: '夜晚',
  },
  notifications: {
    title: '提醒',
    windows: '早晚記念',
    lookAhead: '將至嘅齋戒日',
    prayers: '禮拜提醒',
    prayersDetail: '預設關閉——你嘅宣禮 app 已經會做呢樣嘢。',
    quietHours: '勿擾時段',
    quietHoursDetail: (from: number, to: number): string => `${from}:00 至 ${to}:00`,
    quietHoursOff: '關閉',
    perDay: '每日上限',
    permission: '權限',
    permissionGranted: '已允許',
    permissionDenied: '喺系統設定度關咗',
    permissionUndetermined: '未問過',
    permissionUnavailable: '呢部裝置用唔到',
    openSettings: '打開系統設定',
    whichItems: '邊啲項目',
    whichItemsDetail: '只有有特定時刻可以提醒你嘅項目先會喺度出現。',
    sendTest: '發送測試提醒',
    sendTestDetail: '幾秒之內就會收到。',
    testTitle: '測試提醒',
    testBody: 'Ihsaanly 嘅提醒就係咁嘅樣。',
    action: {
      done: '完成',
      later: '遲啲',
    },
    body: {
      window: '而家開始，直到呢個時段完結。',
      windowUntil: (closes: string): string => `開放到${closes}。`,
      tomorrow: '聽日。',
      prayerWindow: '時間已經到咗。呢個時段會一直開放到下一個禮拜。',
    },
  },
  event: {
    ascending: '上高',
    descending: '落低',
    driving: '駕車',
    travel: '出門旅行',
    'leaving-home': '出門口',
    'entering-home': '返屋企',
  },
  events: {
    title: '你而家嘅情況',
    explanation:
      '呢啲時刻大部分手機根本偵測唔到——搭𨋢、上山、行樓梯。佢哋嘅祈禱詞喺資料庫同小工具度，撳一下就有。',
    detectHome: '我出門口嗰陣留意吓',
    detectHomeDetail:
      '只係大概。手機要離門口大約一百米先會察覺，仲可能遲成一分鐘，所以當佢係一個提示，唔好當係準確嘅時刻。',
    setHome: '將我而家嘅位置設為屋企',
    homeUnset: '未設定',
    homeNeeded: '暫時乜都冇留意緊——喺下面設定屋企。',
    noPlaceYet: '請先設定你嘅位置',
    manual: '改為自己話畀 app 知',
    manualDetail: '感應器偵測唔到嘅情況，你可以自己標示。',
  },
  qada: {
    title: '要補禮',
    intro:
      '開始記錄之前欠下嘅禮拜，同埋之後欠下嘅。只係一個數目，永遠唔會係一張清單。由你標記第一番禮拜開始計。',
    owed: '以前欠下',
    madeUp: '而家補咗',
    record: (count: number): string => (count === 1 ? '記錄一番' : `記錄 ${count} 番`),
    outstanding: (count: number): string => `欠 ${count} 番`,
    none: '冇欠',
    summary: (count: number): string => `欠 ${count} 番禮拜`,
    manage: '調整你欠嘅數目',
    manageDetail: '一次過設定帶過嚟嘅數目，同埋記錄補禮。',
  },
  fasting: {
    title: '齋戒',
    intro: '萊麥丹月入面冇封齋嘅日子，同埋以前欠下嘅。只係一個數目，永遠唔會係一張清單。',
    notFastingToday: '今日冇封齋',
    notFastingTodayDetail: '記低一日，之後再補齋。',
    recordedToday: '已記低：今日冇封齋',
    undo: '撳一下取消',
    summary: (count: number): string => `${count} 日齋要補`,
    outstanding: (count: number): string => `欠 ${count} 日`,
    none: '冇欠',
    owed: '以前欠下',
    recordMadeUp: '記錄補咗一日',
  },
  history: {
    title: '紀錄',
    empty: '暫時未有紀錄。',
    firstWeek:
      '你每日標記禮拜或者完成一個項目，都會喺度保存。一個星期之後，你會睇到自己通常邊啲禮拜禮得早，同埋邊啲項目一直有做。',
    daysActive: (days: number): string => `已記錄 ${days} 日`,
    prayers: '禮拜',
    completed: '已完成',
    times: (count: number): string => `${count} 次`,
    early: (minutes: number): string => `通常喺時段開始後大約 ${minutes} 分鐘`,
    late: (minutes: number): string => `通常喺時段完結前大約 ${minutes} 分鐘`,
  },
  data: {
    title: '你嘅資料',
    explanation: '呢度所有嘢都儲存喺呢部裝置。除非你自己喺呢個畫面傳送出去，否則乜都唔會離開。',
    export: '匯出我嘅資料',
    exportDetail: '可以保存嘅可讀文字，或者帶去另一部裝置。',
    importing: '由檔案匯入',
    importDetail: '會合併，唔會取代。同一個檔案匯入兩次都唔會有任何改變。',
    diagnostics: '發送診斷報告',
    diagnosticsDetail:
      '用嚟解決問題。內容包括你嘅設定、你嘅功課紀錄、你嘅大概座標同最近嘅錯誤。發送之前你會先睇到。',
    imported: (count: number): string => `已加入 ${count} 項。`,
    importFailed: '讀唔到嗰個檔案。',
    shareFailed: '呢部裝置用唔到分享功能。',
    delete: '刪除我嘅資料',
    deleteDetail: '呢部裝置上嘅一切：設定同你嘅功課紀錄。App 會重新開始。',
    deleteConfirmTitle: '刪除所有嘢？',
    deleteConfirmBody: '你嘅設定同功課紀錄會由呢部裝置移除。除非你匯出過，否則其他地方都冇副本。',
    deleteConfirm: '刪除',
    cancel: '取消',
  },
  diagnostics: {
    title: '診斷報告',
    explanation: '報告嘅內容就係咁。你揀發送之前乜都唔會傳出去，而且由你決定傳去邊度。',
    version: 'App 版本',
    device: '裝置',
    coordinates: '大概座標',
    noCoordinates: '冇儲存',
    records: '功課紀錄',
    settings: '已儲存嘅設定',
    failures: '已記錄嘅故障',
    failuresDetail: (count: number): string => `${count} 個 app 已經處理咗、冇通知你嘅問題`,
    reminders: '提醒',
    remindersDetail: (permission: string, pending: number): string =>
      `${permission} · ${pending} 個排緊隊`,
    error: '最近嘅錯誤',
    errorIncluded: '已包括一個',
    showRaw: '顯示成份報告',
    hideRaw: '收埋成份報告',
    send: '發送',
    cancel: '遲啲先',
  },
  about: {
    title: '關於',
    version: '版本',
    content: '內容',
    contentUnreviewed: (count: number): string =>
      `${count} 個項目，已經起草，等緊一位具名學者審閱。`,
    contentReviewedBy: (name: string, count: number): string =>
      `${count} 個項目，已由${name}審閱。`,
    donate: '捐助',
    donateBody:
      '自願性質，唔會解鎖任何功能。App 每一部分都係免費，而且會一直免費。會喺你嘅瀏覽器打開。',
    privacyPolicy: '私隱政策',
    privacyTitle: '乜都唔會離開呢部手機',
    privacyBody:
      'Ihsaanly 冇帳戶、冇伺服器，亦冇數據分析。你嘅位置只喺裝置上用嚟計算禮拜時間，亦只儲存喺呢度。你嘅功課紀錄亦只儲存喺呢度。除非你自己匯出或者分享，否則乜都唔會傳送去任何地方。「捐助」係 app 唯一嘅對外連結：佢會打開你嘅瀏覽器，而嗰個網頁唔屬於 Ihsaanly。',
    licences: '採用技術',
    licencesBody:
      'Expo 同 React Native、計算禮拜時間嘅 adhan 程式庫、烏姆庫拉曆法表、來自 city-timezones 嘅城市資料，以及地圖用嘅 Natural Earth。每一樣都按照佢自己嘅開源授權使用，詳列於原始碼庫。',
  },
  memorise: {
    title: '學識佢',
    start: '練習',
    hide: '再遮多一個',
    known: '我識咗',
    knownDetail: '佢會留喺資料庫，但唔會再喺提醒度出現。',
    notKnown: '仲學緊',
    noAudio: '呢篇暫時未有誦讀錄音。',
    play: '播放',
    stop: '停止',
    loop: '重複',
  },
  language: {
    title: '語言',
    restart: '阿拉伯文由右向左閱讀。轉去或者轉走阿拉伯文，app 會重新啟動，或者請你重新打開。',
    incomplete: '英文係原文。其他所有語言都係草稿，仲等緊合資格嘅母語人士審閱。',
    reopenTitle: '重新打開 Ihsaanly',
    reopenBody: '呢種語言由右向左閱讀。請關閉 Ihsaanly 再打開，改動先會完成。',
    names: {
      en: 'English',
      ar: 'العربية',
      fr: 'Français',
      it: 'Italiano',
      ja: '日本語',
      hi: 'हिन्दी',
      ur: 'اردو',
      so: 'Soomaali',
      zh: '中文（普通话）',
      yue: '廣東話',
    },
  },
  appearance: {
    title: '外觀',
    system: '跟系統',
    light: '淺色',
    dark: '深色',
    note: '顏色始終來自系統，所以無論點揀，系統嘅對比度設定都照樣適用。',
  },
  moonSighting: {
    title: '觀月',
    explanation:
      '呢個 app 入面嘅日期係計算出嚟嘅。各地社群對於跟計算定跟當地觀月意見唔同，兩者經常相差一日。請跟你自己社群所跟隨嘅機構，並喺設定度調整日期，令 app 同佢哋一致。',
    disclaimer: '列出呢啲機構，係方便你搵到你所跟隨嘅嗰個。呢個 app 並唔認可任何一個。',
  },
  tracking: {
    title: '記錄',
    active: '進行中',
    travelling: '旅行中',
    travellingDetail: '會提供短禮，常規聖行拜暫時放低，而齋戒只係提供選擇，唔係預期要做。',
    paused: '暫停禮拜記錄',
    pausedDetail: '禮拜唔會被記錄，亦唔會累積任何要補嘅。會一直暫停，直到你再開返為止。',
  },
  hijri: {
    title: '伊斯蘭曆日期',
    offset: '調整日期',
    approximate: '計算所得——請向你社群所跟隨嘅機構確認。',
    explanation:
      '計算出嚟嘅曆法同當地觀月經常相差一兩日。喺呢度調整日期，令 app 同你嘅社群一致。齋戒日嘅日期永遠顯示為預計，唔會顯示為確定。',
    offsetLabel: (days: number): string =>
      days === 0 ? '唔調整' : `${days > 0 ? '+' : ''}${days} 日`,
    format: (day: number, month: string, year: number): string => `${year}年${month}${day}日`,
  },
  hijriMonth: {
    1: '穆哈蘭姆月',
    2: '色法爾月',
    3: '賴比爾·敖外魯月',
    4: '賴比爾·阿色尼月',
    5: '主馬達·敖外魯月',
    6: '主馬達·阿色尼月',
    7: '賴哲卜月',
    8: '舍爾邦月',
    9: '萊麥丹月',
    10: '閃瓦魯月',
    11: '都爾喀爾德月',
    12: '都爾黑哲月',
  },
  calculation: {
    title: '禮拜時間計算',
    method: '計算方法',
    asr: '晡禮',
    highLatitude: '高緯度',
    selected: '已揀',
    explanation:
      '禮拜時間喺呢部裝置上計算，永遠唔會顯示成鐘點——佢哋只係用嚟判斷你而家喺一日嘅邊個部分。',
    highLatitudeExplanation:
      '喺大約北緯 48° 以北，一年入面有段時間宵禮嘅時間唔會出現。呢個設定決定改用咩時間。',
  },
  asr: {
    shafi: '標準',
    hanafi: '哈乃斐',
  },
  highLatitude: {
    middleofthenight: '夜半',
    seventhofthenight: '夜晚七分之一',
    twilightangle: '曙暮光角度',
  },
  method: {
    MuslimWorldLeague: '世界穆斯林聯盟',
    Egyptian: '埃及測量總局',
    Karachi: '卡拉奇伊斯蘭科學大學',
    UmmAlQura: '烏姆庫拉（麥加）',
    Dubai: '杜拜',
    MoonsightingCommittee: '觀月委員會',
    NorthAmerica: 'ISNA（北美）',
    Kuwait: '科威特',
    Qatar: '卡塔爾',
    Singapore: '新加坡',
    Tehran: '德黑蘭',
    Turkey: '土耳其',
  },
  library: {
    title: '資料庫',
    empty: '記念、祈禱詞同聖行會喺呢度列出。',
    search: '用名稱或者情況搜尋',
    noResults: '冇相符嘅結果。',
    filterAll: '全部',
    filterOnToday: '喺今日',
    filterKnown: '已識',
    onToday: '喺今日',
    known: '已識',
    emptyOnToday: '今日暫時未有項目。打開任何一個項目，再開啟佢。',
    emptyKnown: '暫時未有標記為已識嘅項目。練習一個項目，識咗就話一聲。',
    terms: '詞彙表',
    termsDetail: '聖行、常規聖行拜、記念、補禮等等，每個一句解釋。',
  },
  category: {
    adhkar: '記念',
    dhikr: '禮拜之後',
    fasting: '齋戒',
    food: '飲食',
    home: '屋企',
    masjid: '清真寺',
    prayer: '禮拜',
    sleep: '瞓覺同起身',
    travel: '出行',
  },
  item: {
    done: '完成',
    doneToday: '今日已完成',
    undo: '取消',
    counterReset: '重新開始',
    yourDay: '你嘅一日',
    onToday: '喺今日',
    onTodayDetail: '到咗佢嘅時刻就會出現',
    remind: '提醒我',
    remindWindow: '佢嘅時段開始嗰陣',
    remindLookAhead: '前一晚',
    share: '分享',
    shareText: '以文字分享',
    shareImage: '以圖片分享',
    sharedFrom: '分享自 Ihsaanly',
    transliteration: '音譯',
    translation: '譯文',
    why: '點解',
    how: '點做',
    unreviewed: '等緊審閱',
    evidence: '依據',
    note: '學者意見有分歧',
    repeat: (times: number): string => `重複 ${times} 次`,
    parts: '要念嘅內容',
    partRepeat: (times: number): string => `${times} 次`,
    gradedBy: (grader: string): string => `由${grader}評級`,
    quranReference: (surah: number, ayah: number): string => `《古蘭經》${surah}:${ayah}`,
  },
  glossary: {
    title: '詞語解釋',
  },
  ruling: {
    fard: '主命',
    wajib: '必須',
    'sunnah-muakkadah': '著重聖行',
    sunnah: '聖行',
    mustahabb: '可嘉',
    mubah: '准許',
  },
  grading: {
    sahih: '健全',
    hasan: '良好',
    "da'if": '羸弱',
    disputed: '有爭議',
  },
  more: {
    title: '更多',
    search: '搜尋設定',
    prayer: '禮拜',
    app: 'App',
    practice: '你嘅功課',
    empty: '紀錄、設定同說明會喺呢度。',
  },
  onboarding: {
    welcomeTitle: '重要嘅係時刻，唔係鐘點。',
    welcomeBody: 'Ihsaanly 會話你知黃昏記念幾時開始。永遠唔會係一個鐘點，亦永遠唔會有分數。',
    howTitle: '你標記禮拜，聖行就會出現。',
    howBody: '禮完晌禮就撳一下晌禮，跟住嘅記主就喺度等你。乜都唔會離開呢部手機。冇帳戶，冇伺服器。',
    language: '語言',
    appearance: '外觀',
    howSample: 'سُبْحَانَ اللهِ وَبِحَمْدِهِ',
    locationStep: '你喺邊度？',
    locationWhy: '喺呢部裝置上用嚟計出一日嘅各個部分。永遠唔會傳送去任何地方。',
    genderStep: '暫停記錄',
    genderWhy:
      '有啲日子禮拜記錄應該暫停，亦唔會累積任何要補嘅。呢個選擇決定 app 會唔會提供呢個功能。',
    brother: '兄弟',
    brotherDetail: '冇暫停',
    sister: '姊妹',
    sisterDetail: '提供暫停',
    skip: '唔想講',
    skipDetail: '照樣會提供暫停。',
    genderPrivacy: '只儲存喺呢部裝置。永遠唔會傳送出去，亦唔會用嚟做其他嘢。',
    remindersStep: '提醒',
    remindersWhy: '一日兩三個，夜晚永遠唔會有。之後可以喺「更多」度更改任何設定。',
    windowsDetail: '每個時段開始嗰陣',
    lookAheadDetail: '前一晚',
    startStep: '起步點',
    startWhy: '揀一個份量開始。之後隨時都可以喺資料庫加減任何項目。',
    starting: '啱啱開始',
    startingDetail: (count: number): string =>
      `${count} 樣由第一日就做得到嘅嘢：兩個時段、一個記主、兩篇祈禱詞。適合對呢一切都係新手嘅人。`,
    essentials: '基本',
    essentialsDetail: (count: number): string =>
      `${count} 個項目，合理嘅一日，而唔係完整嘅一日。適合已經有禮拜、想加上周邊聖行嘅人。`,
    everything: '全部',
    everythingDetail: (count: number): string =>
      `全部 ${count} 個項目。適合熟悉內容、想要成個日曆嘅人。`,
    skipIntro: '略過',
    skipLocation: '暫時略過',
    reminderPolicy: (perDay: number, from: number, to: number): string =>
      `每日最多 ${perDay} 個，${from}:00 至 ${to}:00 之間乜都冇。`,
    reminderCap: (perDay: number): string => `每日最多 ${perDay} 個。`,
    included: '已包括',
    andMore: (count: number): string => `仲有 ${count} 個`,
    back: '返回',
    continue: '繼續',
    allowReminders: '允許提醒',
    notNow: '遲啲先',
    done: '開始',
  },
  location: {
    title: '位置',
    notSet: '未設定',
    currentLocation: '目前位置',
    useDevice: '用我嘅位置',
    useDeviceDetail: '乜都唔會離開呢部手機。',
    locating: '搵緊你嘅位置…',
    orSearch: '或者搜尋城市',
    follows: '禮拜時段會跟隨呢個地方。',
    search: '搜尋城市',
    noResults: '冇相符嘅城市。',
    unavailable: '呢部裝置嘅定位服務已經關閉。請開啟佢，或者改為搜尋你嘅城市。',
    declined: '你拒絕咗位置存取。請改為搜尋你嘅城市——所有功能照樣用得。',
    explanation: '喺呢部裝置上用嚟計出禮拜時段，永遠唔會傳送去任何地方。',
    attribution: '城市資料來自 city-timezones（MIT）。',
  },
  textField: {
    clear: '清除',
  },
  error: {
    title: '出咗問題',
    retry: '再試一次',
  },
  notFound: {
    title: '搵唔到',
    body: '嗰個畫面唔存在。',
  },
  widgets: {
    quickDuas: '快捷祈禱詞',
    duaOfTheDay: '今日祈禱詞',
    nothingNow: '而家冇嘢要做',
    openApp: '打開 Ihsaanly 更新',
  },
}
