/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteRouteImport } from './routes/_library/route'
import { Route as MoreRouteRouteImport } from './routes/_more/route'
import { Route as TodayRouteImport } from './routes/today'
import { Route as LibraryGlossaryRouteImport } from './routes/_library/glossary'
import { Route as LibraryLibraryRouteImport } from './routes/_library/library'
import { Route as MoreAboutRouteImport } from './routes/_more/about'
import { Route as MoreAccountRouteImport } from './routes/_more/account'
import { Route as MoreAppearanceRouteImport } from './routes/_more/appearance'
import { Route as MoreCalculationRouteImport } from './routes/_more/calculation'
import { Route as MoreDataRouteImport } from './routes/_more/data'
import { Route as MoreDiagnosticsRouteImport } from './routes/_more/diagnostics'
import { Route as MoreEventsRouteImport } from './routes/_more/events'
import { Route as MoreFeedbackRouteImport } from './routes/_more/feedback'
import { Route as MoreHijriRouteImport } from './routes/_more/hijri'
import { Route as MoreHistoryRouteImport } from './routes/_more/history'
import { Route as MoreLanguageRouteImport } from './routes/_more/language'
import { Route as MoreLocationRouteImport } from './routes/_more/location'
import { Route as MoreMoreRouteImport } from './routes/_more/more'
import { Route as MoreNotificationsRouteImport } from './routes/_more/notifications'
import { Route as MoreQadaRouteImport } from './routes/_more/qada'
import { Route as MoreTrackingRouteImport } from './routes/_more/tracking'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingStepRouteImport } from './routes/onboarding/$step'
import { Route as LibraryItemIdRouteImport } from './routes/_library/item/$id'
import { Route as LibraryItemMemoriseIdRouteImport } from './routes/_library/item/memorise/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRouteRoute = LibraryRouteRouteImport.update({
  id: '/_library',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRouteRoute = MoreRouteRouteImport.update({
  id: '/_more',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryGlossaryRoute = LibraryGlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => LibraryRouteRoute,
} as any)
const LibraryLibraryRoute = LibraryLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => LibraryRouteRoute,
} as any)
const MoreAboutRoute = MoreAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MoreRouteRoute,
} as any)
const MoreAccountRoute = MoreAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => MoreRouteRoute,
} as any)
const MoreAppearanceRoute = MoreAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => MoreRouteRoute,
} as any)
const MoreCalculationRoute = MoreCalculationRouteImport.update({
  id: '/calculation',
  path: '/calculation',
  getParentRoute: () => MoreRouteRoute,
} as any)
const MoreDataRoute = MoreDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => MoreRouteRoute,
} as any)
const MoreDiagnosticsRoute = MoreDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => MoreRouteRoute,
} as any)
const MoreEventsRoute = MoreEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => MoreRouteRoute,
} as any)
const MoreFeedbackRoute = MoreFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => MoreRouteRoute,
} as any)
const MoreHijriRoute = MoreHijriRouteImport.update({
  id: '/hijri',
  path: '/hijri',
  getParentRoute: () => MoreRouteRoute,
} as any)
const MoreHistoryRoute = MoreHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => MoreRouteRoute,
} as any)
const MoreLanguageRoute = MoreLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => MoreRouteRoute,
} as any)
const MoreLocationRoute = MoreLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => MoreRouteRoute,
} as any)
const MoreMoreRoute = MoreMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => MoreRouteRoute,
} as any)
const MoreNotificationsRoute = MoreNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MoreRouteRoute,
} as any)
const MoreQadaRoute = MoreQadaRouteImport.update({
  id: '/qada',
  path: '/qada',
  getParentRoute: () => MoreRouteRoute,
} as any)
const MoreTrackingRoute = MoreTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => MoreRouteRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/onboarding/$step',
  path: '/onboarding/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryItemIdRoute = LibraryItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => LibraryRouteRoute,
} as any)
const LibraryItemMemoriseIdRoute = LibraryItemMemoriseIdRouteImport.update({
  id: '/item/memorise/$id',
  path: '/item/memorise/$id',
  getParentRoute: () => LibraryRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/today': typeof TodayRoute
  '/glossary': typeof LibraryGlossaryRoute
  '/library': typeof LibraryLibraryRoute
  '/about': typeof MoreAboutRoute
  '/account': typeof MoreAccountRoute
  '/appearance': typeof MoreAppearanceRoute
  '/calculation': typeof MoreCalculationRoute
  '/data': typeof MoreDataRoute
  '/diagnostics': typeof MoreDiagnosticsRoute
  '/events': typeof MoreEventsRoute
  '/feedback': typeof MoreFeedbackRoute
  '/hijri': typeof MoreHijriRoute
  '/history': typeof MoreHistoryRoute
  '/language': typeof MoreLanguageRoute
  '/location': typeof MoreLocationRoute
  '/more': typeof MoreMoreRoute
  '/notifications': typeof MoreNotificationsRoute
  '/qada': typeof MoreQadaRoute
  '/tracking': typeof MoreTrackingRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/item/$id': typeof LibraryItemIdRoute
  '/item/memorise/$id': typeof LibraryItemMemoriseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/today': typeof TodayRoute
  '/glossary': typeof LibraryGlossaryRoute
  '/library': typeof LibraryLibraryRoute
  '/about': typeof MoreAboutRoute
  '/account': typeof MoreAccountRoute
  '/appearance': typeof MoreAppearanceRoute
  '/calculation': typeof MoreCalculationRoute
  '/data': typeof MoreDataRoute
  '/diagnostics': typeof MoreDiagnosticsRoute
  '/events': typeof MoreEventsRoute
  '/feedback': typeof MoreFeedbackRoute
  '/hijri': typeof MoreHijriRoute
  '/history': typeof MoreHistoryRoute
  '/language': typeof MoreLanguageRoute
  '/location': typeof MoreLocationRoute
  '/more': typeof MoreMoreRoute
  '/notifications': typeof MoreNotificationsRoute
  '/qada': typeof MoreQadaRoute
  '/tracking': typeof MoreTrackingRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/item/$id': typeof LibraryItemIdRoute
  '/item/memorise/$id': typeof LibraryItemMemoriseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_library': typeof LibraryRouteRouteWithChildren
  '/_more': typeof MoreRouteRouteWithChildren
  '/today': typeof TodayRoute
  '/_library/glossary': typeof LibraryGlossaryRoute
  '/_library/library': typeof LibraryLibraryRoute
  '/_more/about': typeof MoreAboutRoute
  '/_more/account': typeof MoreAccountRoute
  '/_more/appearance': typeof MoreAppearanceRoute
  '/_more/calculation': typeof MoreCalculationRoute
  '/_more/data': typeof MoreDataRoute
  '/_more/diagnostics': typeof MoreDiagnosticsRoute
  '/_more/events': typeof MoreEventsRoute
  '/_more/feedback': typeof MoreFeedbackRoute
  '/_more/hijri': typeof MoreHijriRoute
  '/_more/history': typeof MoreHistoryRoute
  '/_more/language': typeof MoreLanguageRoute
  '/_more/location': typeof MoreLocationRoute
  '/_more/more': typeof MoreMoreRoute
  '/_more/notifications': typeof MoreNotificationsRoute
  '/_more/qada': typeof MoreQadaRoute
  '/_more/tracking': typeof MoreTrackingRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_library/item/$id': typeof LibraryItemIdRoute
  '/_library/item/memorise/$id': typeof LibraryItemMemoriseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/today'
    | '/glossary'
    | '/library'
    | '/about'
    | '/account'
    | '/appearance'
    | '/calculation'
    | '/data'
    | '/diagnostics'
    | '/events'
    | '/feedback'
    | '/hijri'
    | '/history'
    | '/language'
    | '/location'
    | '/more'
    | '/notifications'
    | '/qada'
    | '/tracking'
    | '/onboarding/$step'
    | '/onboarding/'
    | '/item/$id'
    | '/item/memorise/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/today'
    | '/glossary'
    | '/library'
    | '/about'
    | '/account'
    | '/appearance'
    | '/calculation'
    | '/data'
    | '/diagnostics'
    | '/events'
    | '/feedback'
    | '/hijri'
    | '/history'
    | '/language'
    | '/location'
    | '/more'
    | '/notifications'
    | '/qada'
    | '/tracking'
    | '/onboarding/$step'
    | '/onboarding'
    | '/item/$id'
    | '/item/memorise/$id'
  id:
    | '__root__'
    | '/'
    | '/_library'
    | '/_more'
    | '/today'
    | '/_library/glossary'
    | '/_library/library'
    | '/_more/about'
    | '/_more/account'
    | '/_more/appearance'
    | '/_more/calculation'
    | '/_more/data'
    | '/_more/diagnostics'
    | '/_more/events'
    | '/_more/feedback'
    | '/_more/hijri'
    | '/_more/history'
    | '/_more/language'
    | '/_more/location'
    | '/_more/more'
    | '/_more/notifications'
    | '/_more/qada'
    | '/_more/tracking'
    | '/onboarding/$step'
    | '/onboarding/'
    | '/_library/item/$id'
    | '/_library/item/memorise/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRouteRoute: typeof LibraryRouteRouteWithChildren
  MoreRouteRoute: typeof MoreRouteRouteWithChildren
  TodayRoute: typeof TodayRoute
  OnboardingStepRoute: typeof OnboardingStepRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_library': {
      id: '/_library'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LibraryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_more': {
      id: '/_more'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MoreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_library/glossary': {
      id: '/_library/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof LibraryGlossaryRouteImport
      parentRoute: typeof LibraryRouteRoute
    }
    '/_library/library': {
      id: '/_library/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryLibraryRouteImport
      parentRoute: typeof LibraryRouteRoute
    }
    '/_more/about': {
      id: '/_more/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MoreAboutRouteImport
      parentRoute: typeof MoreRouteRoute
    }
    '/_more/account': {
      id: '/_more/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof MoreAccountRouteImport
      parentRoute: typeof MoreRouteRoute
    }
    '/_more/appearance': {
      id: '/_more/appearance'
      path: '/appearance'
      fullPath: '/appearance'
      preLoaderRoute: typeof MoreAppearanceRouteImport
      parentRoute: typeof MoreRouteRoute
    }
    '/_more/calculation': {
      id: '/_more/calculation'
      path: '/calculation'
      fullPath: '/calculation'
      preLoaderRoute: typeof MoreCalculationRouteImport
      parentRoute: typeof MoreRouteRoute
    }
    '/_more/data': {
      id: '/_more/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof MoreDataRouteImport
      parentRoute: typeof MoreRouteRoute
    }
    '/_more/diagnostics': {
      id: '/_more/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof MoreDiagnosticsRouteImport
      parentRoute: typeof MoreRouteRoute
    }
    '/_more/events': {
      id: '/_more/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof MoreEventsRouteImport
      parentRoute: typeof MoreRouteRoute
    }
    '/_more/feedback': {
      id: '/_more/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof MoreFeedbackRouteImport
      parentRoute: typeof MoreRouteRoute
    }
    '/_more/hijri': {
      id: '/_more/hijri'
      path: '/hijri'
      fullPath: '/hijri'
      preLoaderRoute: typeof MoreHijriRouteImport
      parentRoute: typeof MoreRouteRoute
    }
    '/_more/history': {
      id: '/_more/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof MoreHistoryRouteImport
      parentRoute: typeof MoreRouteRoute
    }
    '/_more/language': {
      id: '/_more/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof MoreLanguageRouteImport
      parentRoute: typeof MoreRouteRoute
    }
    '/_more/location': {
      id: '/_more/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof MoreLocationRouteImport
      parentRoute: typeof MoreRouteRoute
    }
    '/_more/more': {
      id: '/_more/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreMoreRouteImport
      parentRoute: typeof MoreRouteRoute
    }
    '/_more/notifications': {
      id: '/_more/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof MoreNotificationsRouteImport
      parentRoute: typeof MoreRouteRoute
    }
    '/_more/qada': {
      id: '/_more/qada'
      path: '/qada'
      fullPath: '/qada'
      preLoaderRoute: typeof MoreQadaRouteImport
      parentRoute: typeof MoreRouteRoute
    }
    '/_more/tracking': {
      id: '/_more/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof MoreTrackingRouteImport
      parentRoute: typeof MoreRouteRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/onboarding/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_library/item/$id': {
      id: '/_library/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof LibraryItemIdRouteImport
      parentRoute: typeof LibraryRouteRoute
    }
    '/_library/item/memorise/$id': {
      id: '/_library/item/memorise/$id'
      path: '/item/memorise/$id'
      fullPath: '/item/memorise/$id'
      preLoaderRoute: typeof LibraryItemMemoriseIdRouteImport
      parentRoute: typeof LibraryRouteRoute
    }
  }
}

interface LibraryRouteRouteChildren {
  LibraryGlossaryRoute: typeof LibraryGlossaryRoute
  LibraryLibraryRoute: typeof LibraryLibraryRoute
  LibraryItemIdRoute: typeof LibraryItemIdRoute
  LibraryItemMemoriseIdRoute: typeof LibraryItemMemoriseIdRoute
}

const LibraryRouteRouteChildren: LibraryRouteRouteChildren = {
  LibraryGlossaryRoute: LibraryGlossaryRoute,
  LibraryLibraryRoute: LibraryLibraryRoute,
  LibraryItemIdRoute: LibraryItemIdRoute,
  LibraryItemMemoriseIdRoute: LibraryItemMemoriseIdRoute,
}

const LibraryRouteRouteWithChildren = LibraryRouteRoute._addFileChildren(
  LibraryRouteRouteChildren,
)

interface MoreRouteRouteChildren {
  MoreAboutRoute: typeof MoreAboutRoute
  MoreAccountRoute: typeof MoreAccountRoute
  MoreAppearanceRoute: typeof MoreAppearanceRoute
  MoreCalculationRoute: typeof MoreCalculationRoute
  MoreDataRoute: typeof MoreDataRoute
  MoreDiagnosticsRoute: typeof MoreDiagnosticsRoute
  MoreEventsRoute: typeof MoreEventsRoute
  MoreFeedbackRoute: typeof MoreFeedbackRoute
  MoreHijriRoute: typeof MoreHijriRoute
  MoreHistoryRoute: typeof MoreHistoryRoute
  MoreLanguageRoute: typeof MoreLanguageRoute
  MoreLocationRoute: typeof MoreLocationRoute
  MoreMoreRoute: typeof MoreMoreRoute
  MoreNotificationsRoute: typeof MoreNotificationsRoute
  MoreQadaRoute: typeof MoreQadaRoute
  MoreTrackingRoute: typeof MoreTrackingRoute
}

const MoreRouteRouteChildren: MoreRouteRouteChildren = {
  MoreAboutRoute: MoreAboutRoute,
  MoreAccountRoute: MoreAccountRoute,
  MoreAppearanceRoute: MoreAppearanceRoute,
  MoreCalculationRoute: MoreCalculationRoute,
  MoreDataRoute: MoreDataRoute,
  MoreDiagnosticsRoute: MoreDiagnosticsRoute,
  MoreEventsRoute: MoreEventsRoute,
  MoreFeedbackRoute: MoreFeedbackRoute,
  MoreHijriRoute: MoreHijriRoute,
  MoreHistoryRoute: MoreHistoryRoute,
  MoreLanguageRoute: MoreLanguageRoute,
  MoreLocationRoute: MoreLocationRoute,
  MoreMoreRoute: MoreMoreRoute,
  MoreNotificationsRoute: MoreNotificationsRoute,
  MoreQadaRoute: MoreQadaRoute,
  MoreTrackingRoute: MoreTrackingRoute,
}

const MoreRouteRouteWithChildren = MoreRouteRoute._addFileChildren(
  MoreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRouteRoute: LibraryRouteRouteWithChildren,
  MoreRouteRoute: MoreRouteRouteWithChildren,
  TodayRoute: TodayRoute,
  OnboardingStepRoute: OnboardingStepRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
