import type { Strings } from './en'

/**
 * Arabic interface copy. A complete draft, written in one pass and not yet
 * reviewed by a qualified speaker; the review is a release condition, not a
 * nicety. Content text (adhkar, duas, evidence) does not live here.
 */

/** Arabic counts: singular, dual, 3 to 10 take the plural, 11 and up the singular accusative. */
function count(n: number, one: string, two: string, few: string, many: string): string {
  if (n === 1) return one
  if (n === 2) return two
  if (n >= 3 && n <= 10) return `${n} ${few}`
  return `${n} ${many}`
}

export const ar: Strings = {
  tabs: {
    today: 'اليوم',
    library: 'المكتبة',
    more: 'المزيد',
  },
  today: {
    title: 'اليوم',
    nothingElse:
      '\u0644\u0627 \u0634\u064a\u0621 \u0622\u062e\u0631 \u0645\u0637\u0644\u0648\u0628 \u0645\u0646\u0643 \u0627\u0644\u064a\u0648\u0645.',
    empty: 'لا شيء هنا بعد.',
    needsLocationTitle: 'أين أنت؟',
    needsLocation:
      'أوقات الصلاة والتاريخ الهجري وكل ما يطلبه اليوم منك تتبع موقعًا تقريبيًا. يُحسب على هذا الجهاز ويبقى عليه ما لم تسجّل الدخول للمزامنة.',
    chooseCity: 'اختر مدينة بدلًا من ذلك',
    chooseCityDetail: 'لا يحتاج إذنًا. كل شيء يعمل كما هو.',
    prayerHint: 'انقر على الصلاة بعد أن تصليها',
    markDone: (name: string): string => `وضع علامة «تم» على ${name}`,
    unmark: (name: string): string => `إزالة علامة ${name}`,
    countItem: (name: string, count: number, target: number): string =>
      `عدّ ${name}، ${count} من ${target}`,
    partsItem: (name: string, done: number, total: number): string =>
      `أجزاء ${name}، أُنجز ${done} من ${total}`,
    open: (name: string): string => `فتح ${name}`,
    doneToday: (count: number): string => `أُنجز اليوم (${count})`,
    markedDone: 'تم التسجيل',
    undo: 'تراجع',
    undoItem: (name: string): string => `التراجع عن ${name}`,
    paused: 'تتبع الصلاة متوقف',
    pausedFasting: 'يعود الصيام بعد انتهاء الإيقاف',
    checkInTitle: 'هل أنت مستعد لاستئناف تتبع الصلاة؟',
    resume: 'استئناف',
    notYet: 'ليس بعد',
  },
  tour: {
    prayer: 'انقر على الدائرة لتسجيل صلاة',
    sunnah: 'انقر على الدائرة بجانب السنة بعد أن تؤديها',
    card: 'انقر على البطاقة لتتعرّف عليها: الألفاظ والمعنى والمصدر',
    step: (step: number, total: number): string => `${step} من ${total}`,
    skip: 'تخطّي',
    next: 'التالي',
    done: 'فهمت',
  },
  plan: {
    rightNow: 'الآن',
    tryOneMore: 'جرّب واحدًا آخر',
    add: 'أضِف',
    notNow: 'ليس الآن',
    alsoNow: 'أيضًا الآن',
    upNext: 'التالي',
    before: 'قبلها',
    after: 'بعدها',
    soon: 'قريبًا',
    inAboutAnHour: 'بعد نحو ساعة',
    inAboutHours: (hours: number): string =>
      `بعد نحو ${count(hours, 'ساعة', 'ساعتين', 'ساعات', 'ساعة')}`,
    context: 'حيث أنت',
    comingUp: 'لاحقًا هذا الأسبوع',
    alsoToday: 'أيضًا اليوم',
    tomorrow: 'غدًا',
    inDays: (days: number): string => `بعد ${count(days, 'يوم', 'يومين', 'أيام', 'يومًا')}`,
    prayers: 'الصلوات',
    optional: 'اختياري',
    expected: 'متوقَّع',
    confirmLocally: 'تأكد من جهتك المحلية',
    prayed: 'صُلّيت',
    makeUp: 'للقضاء',
    outstanding: (n: number): string =>
      `${count(n, 'صلاة واحدة', 'صلاتان', 'صلوات', 'صلاةً')} للقضاء`,
  },
  prayer: {
    fajr: 'الفجر',
    dhuhr: 'الظهر',
    asr: 'العصر',
    maghrib: 'المغرب',
    isha: 'العشاء',
    jumuah: 'الجمعة',
  },
  window: {
    fajr: 'الفجر',
    sunrise: 'الصباح',
    dhuhr: 'بعد الظهر',
    asr: 'المساء',
    maghrib: 'بعد المغرب',
    isha: 'الليل',
    jumuah: 'بعد الجمعة',
  },
  notifications: {
    title: 'التنبيهات',
    windows: 'أذكار الصباح والمساء',
    lookAhead: 'أيام الصيام القادمة',
    prayers: 'تنبيهات الصلاة',
    prayersDetail: 'معطَّلة افتراضيًا — تطبيق الأذان لديك يقوم بذلك.',
    quietHours: 'ساعات الهدوء',
    quietHoursDetail: (from: number, to: number): string => `من ${from}:00 إلى ${to}:00`,
    quietHoursOff: 'معطَّل',
    perDay: 'الحد اليومي',
    permission: 'الإذن',
    permissionGranted: 'مسموح',
    permissionDenied: 'معطَّل من إعدادات النظام',
    permissionUndetermined: 'لم يُطلب بعد',
    permissionUnavailable: 'غير متاح على هذا الجهاز',
    openSettings: 'افتح إعدادات النظام',
    whichItems: 'أي العناصر',
    whichItemsDetail: 'تظهر هنا العناصر التي لها وقت يمكن التذكير به فقط.',
    sendTest: 'أرسل تنبيهًا تجريبيًا',
    sendTestDetail: 'يصل خلال ثوانٍ.',
    announcements: 'الإعلانات',
    announcementsDetail:
      'رسائل متفرقة من إحسانلي، مثل بداية رمضان. تذكيراتك اليومية لا تحتاج إلى هذا.',
    testTitle: 'تنبيه تجريبي',
    testBody: 'هكذا يبدو التنبيه من إحسانلي.',
    pausedRemembrance: 'حان وقت الذكر',
    checkIn: 'اطمئنان سريع من إحسانلي',
    action: {
      done: 'تم',
      later: 'لاحقًا',
    },
    body: {
      window: 'الآن، حتى ينتهي الوقت.',
      windowUntil: (closes: string): string => `مفتوح حتى ${closes}.`,
      tomorrow: 'غدًا.',
      prayerWindow: 'دخل الوقت. تبقى النافذة مفتوحة حتى الصلاة التالية.',
    },
  },
  event: {
    ascending: 'الصعود',
    descending: 'النزول',
    driving: 'القيادة',
    travel: 'السفر',
    'leaving-home': 'الخروج من المنزل',
    'entering-home': 'العودة إلى المنزل',
  },
  events: {
    title: 'أين أنت',
    explanation:
      'أكثر هذه اللحظات لا يستطيع الهاتف رصدها أصلًا — مصعد، أو تلّ، أو درج. أدعيتها على بُعد نقرة في المكتبة وعلى الأداة.',
    detectHome: 'لاحظ خروجي من المنزل',
    detectHomeDetail:
      'تقريبي. يلاحظ الهاتف على بُعد نحو مئة متر من الباب وبتأخير يصل إلى دقيقة، فاعتبره تذكيرًا لا اللحظة نفسها.',
    setHome: 'اجعل مكاني الحالي هو المنزل',
    homeUnset: 'غير محدد',
    homeNeeded:
      '\u0644\u0627 \u0634\u064a\u0621 \u062a\u062d\u062a \u0627\u0644\u0645\u0631\u0627\u0642\u0628\u0629 \u0628\u0639\u062f \u2014 \u062d\u062f\u0651\u062f \u0627\u0644\u0645\u0646\u0632\u0644 \u0623\u062f\u0646\u0627\u0647.',
    noPlaceYet:
      '\u062d\u062f\u0651\u062f \u0645\u0643\u0627\u0646\u0643 \u0623\u0648\u0644\u0627\u064b',
    manual: 'أخبر التطبيق بنفسك',
    manualDetail: 'أعلن الحالة بنفسك حين لا يجدها أي مستشعر.',
  },
  qada: {
    title: 'القضاء',
    intro:
      'صلوات عليك من قبل أن تبدأ المتابعة، وما تراكم بعدها. عدد لا قائمة. يبدأ الحساب من أول صلاة تسجّلها.',
    owed: 'عليك من قبل',
    madeUp: 'قضيتها الآن',
    record: (n: number): string => `سجّل ${count(n, 'واحدة', 'اثنتين', 'صلوات', 'صلاة')}`,
    outstanding: (n: number): string => `${count(n, 'صلاة واحدة', 'صلاتان', 'صلوات', 'صلاة')} عليك`,
    none: 'لا شيء عليك',
    summary: (n: number): string => `${count(n, 'صلاة واحدة', 'صلاتان', 'صلوات', 'صلاة')} عليك`,
    manage: 'عدّل ما عليك',
    manageDetail: 'حدّد ما تحمله من قبل وسجّل القضاء دفعة واحدة.',
  },
  fasting: {
    title: 'الصيام',
    intro: 'أيام من رمضان لم تصمها، وما عليك من قبل. عدد لا قائمة.',
    notFastingToday: 'لست صائمًا اليوم',
    notFastingTodayDetail: 'يُحفظ يوم واحد تقضيه لاحقًا.',
    recordedToday: 'سُجّل: لست صائمًا اليوم',
    undo: 'اضغط للتراجع',
    summary: (n: number): string => `صيام ${count(n, 'يوم واحد', 'يومين', 'أيام', 'يومًا')} للقضاء`,
    outstanding: (n: number): string => `${count(n, 'يوم واحد', 'يومان', 'أيام', 'يومًا')} عليك`,
    none: 'لا شيء عليك',
    owed: 'عليك من قبل',
    recordMadeUp: 'سجّل يومًا قضيته',
  },
  history: {
    title: 'السجل',
    empty: 'لم يُسجَّل شيء بعد.',
    firstWeek:
      'كل يوم تسجّل فيه صلاة أو تُتمّ عملًا يُحفظ هنا. بعد أسبوع سترى أي الصلوات تصليها مبكرًا وأي الأعمال تداوم عليها.',
    daysActive: (days: number): string =>
      count(days, 'يوم واحد مسجَّل', 'يومان مسجَّلان', 'أيام مسجَّلة', 'يومًا مسجَّلًا'),
    prayers: 'الصلوات',
    completed: 'المُنجَز',
    times: (n: number): string => count(n, 'مرة واحدة', 'مرتان', 'مرات', 'مرة'),
    early: (minutes: number): string =>
      `عادةً بعد نحو ${count(minutes, 'دقيقة', 'دقيقتين', 'دقائق', 'دقيقة')} من بداية الوقت`,
    late: (minutes: number): string =>
      `عادةً قبل نحو ${count(minutes, 'دقيقة', 'دقيقتين', 'دقائق', 'دقيقة')} من انتهائه`,
  },
  account: {
    title: 'الحساب',
    notSignedIn: 'لم تسجّل الدخول',
    explanation:
      'اختياري. تبقى بياناتك على هذا الجهاز ما لم تسجّل الدخول. تسجيل الدخول يُبقي سجلّك وتقدّمك وإعداداتك، ومنها موقعك، متزامنة بين أجهزتك.',
    continueWithApple: 'المتابعة باستخدام Apple',
    continueWithGoogle: 'المتابعة باستخدام Google',
    signInWithApple: 'تسجيل الدخول باستخدام Apple',
    signInWithGoogle: 'تسجيل الدخول باستخدام Google',
    agreement: 'بالمتابعة، أنت توافق على {terms} و{privacy}.',
    terms: 'الشروط',
    privacy: 'سياسة الخصوصية',
    notice:
      'يُخزَّن سجل ممارستك وإعداداتك وموقعك التقريبي لدى Google Firebase (الولايات المتحدة) لتتم مزامنتها، مع اسمك وبريدك الإلكتروني من Apple أو Google. يجب أن يكون عمرك 13 عامًا أو أكثر، أو السن التي يشترطها بلدك (حتى 16 عامًا). يمكنك حذف حسابك في أي وقت.',
    signingIn: 'جارٍ تسجيل الدخول…',
    signInFailed: 'لم يكتمل تسجيل الدخول. لم يتغيّر شيء على هذا الجهاز.',
    errors: {
      network: 'تعذّر الاتصال. تحقّق من اتصالك وحاول مجددًا.',
      auth: 'لم يُقبل تسجيل الدخول. حاول مجددًا.',
      sync: 'تعذّرت مزامنة بياناتك هذه المرة. ستُعاد المحاولة.',
      unknown: 'حدث خطأ ما. حاول مجددًا.',
      'remove-blocked': 'تعذّر الوصول إلى حسابك، لذا لم يُحذف شيء.',
      'link-conflict':
        'هذا الحساب مرتبط بالفعل بحساب إحسانلي آخر، لذا لم يتم ربطه. لاستخدامه هنا، صدّر ما تريد الاحتفاظ به من الحساب الآخر، ثم احذف ذلك الحساب، ثم اربطه من جديد، أو تواصل مع الدعم.',
      'reauth-unavailable':
        'يتطلب الحذف تسجيل الدخول مرة أخرى باستخدام Apple، وهذا غير متاح هنا. احذف حسابك من تطبيق إحسانلي أو من companion.ihsaanly.app.',
    },
    signedInWith: { apple: 'تم تسجيل الدخول عبر Apple', google: 'تم تسجيل الدخول عبر Google' },
    lastSynced: (when: string): string => `آخر مزامنة: ${when}`,
    neverSynced: 'لم تتم المزامنة بعد',
    justNow: 'الآن',
    minutesAgo: (n: number): string => `قبل ${n} د`,
    hoursAgo: (n: number): string => `قبل ${n} س`,
    daysAgo: (n: number): string => `قبل ${n} ي`,
    syncing: 'جارٍ المزامنة…',
    upToDate: 'محدَّث',
    syncFailed: 'لم تكتمل آخر مزامنة. ستُعاد المحاولة.',
    syncNow: 'زامِن الآن',
    signOut: 'تسجيل الخروج',
    signOutDetail: 'يوقف المزامنة على هذا الجهاز. يحتفظ حسابك بنسخته.',
    signOutTitle: 'تسجيل الخروج؟',
    signOutBody: 'يحتفظ حسابك بكل ما تمت مزامنته. اختر ما يحدث للنسخة الموجودة على هذا الجهاز.',
    keepData: 'إبقاء البيانات على هذا الجهاز',
    removeData: 'إزالتها من هذا الجهاز',
    deleteAccount: 'حذف الحساب',
    deleteAccountDetail: 'يمحو حسابك وكل ما تمت مزامنته معه.',
    deleteTitle: 'حذف حسابك؟',
    deleteBody: 'يُحذف حسابك وكل البيانات المتزامنة معه نهائيًا من السحابة. لا يمكن التراجع عن ذلك.',
    deleteConfirm: 'حذف الحساب',
    deleteChoiceTitle: 'وماذا عن البيانات على هذا الجهاز؟',
    deleteChoiceBody: 'أبقِها لتواصل استخدام التطبيق دون حساب، أو أزلها ليبدأ التطبيق من جديد.',
    mismatchTitle: 'على هذا الجهاز بيانات من حساب آخر',
    mismatchBody:
      'ادمجها في الحساب الذي سجّلت الدخول إليه الآن، أو امسح هذا الجهاز وخذ بيانات هذا الحساب بدلًا منها.',
    merge: 'دمج في هذا الحساب',
    fresh: 'البدء من جديد على هذا الجهاز',
    cancel: 'إلغاء',
    linkTitle: 'لديك حساب بالفعل',
    linkBody: (existing: string, attempted: string): string =>
      `يوجد بالفعل حساب إحسانلي بهذا البريد الإلكتروني يستخدم ${existing}. تابع باستخدام ${existing} لفتحه، وسيتم ربط ${attempted} به، فيعمل أيٌّ منهما من الآن فصاعدًا.`,
    linkUnavailable:
      'يستخدم هذا الحساب تسجيل الدخول باستخدام Apple، وهو غير متاح هنا. سجّل الدخول من تطبيق إحسانلي أو companion.ihsaanly.app، واربط Google من الحساب → طرق تسجيل الدخول، ثم عد إلى هنا.',
    methodsTitle: 'طرق تسجيل الدخول',
    methodLinked: (provider: string): string => `${provider}، مرتبط`,
    linkProvider: (provider: string): string => `ربط ${provider}`,
    methodsHint:
      'إذا استخدمت «إخفاء بريدي الإلكتروني» مع Apple، فاربط Google هنا ليفتح كلاهما الحساب نفسه.',
    restore: {
      backToSetup: 'العودة إلى الإعداد',
      intro: 'سجّل الدخول بالحساب الذي تستخدمه. تعود إعداداتك وموقعك وسجلّك مع أول مزامنة.',
      restoring: 'جارٍ استعادة بياناتك…',
      restored: 'عادت بياناتك.',
      needsSetupTitle: 'لا شيء لاستعادته بعد',
      needsSetupBody:
        'لم يُعدّ هذا الحساب بعد. تابع الإعداد، فستبقى مسجّل الدخول، وتُزامَن اختياراتك أولًا بأول.',
      continueSetup: 'متابعة الإعداد',
      remindersTitle: 'تنبيهاتك مفعّلة',
      remindersBody: 'التنبيهات مفعّلة في حسابك. اسمح بالإشعارات هنا لتصلك على هذا الجهاز أيضًا.',
    },
  },
  data: {
    title: 'بياناتك',
    explanation:
      'كل ما هنا يبقى على هذا الجهاز. لا يخرج منه شيء إلا إن أرسلته أنت من هذه الشاشة، أو سجّلت الدخول للمزامنة من «الحساب».',
    export: 'تصدير بياناتي',
    exportDetail: 'نص مقروء تحتفظ به أو تنقله إلى جهاز آخر.',
    importing: 'استيراد من ملف',
    importDetail: 'يُدمج ولا يستبدل. استيراد الملف نفسه مرتين لا يغيّر شيئًا.',
    diagnostics: 'إرسال تقرير تشخيصي',
    diagnosticsDetail:
      'لإصلاح مشكلة. يحوي إعداداتك وسجل ممارستك وإحداثياتك التقريبية والأخطاء الأخيرة. ستراه قبل إرساله.',
    imported: (n: number): string =>
      n >= 3 && n <= 10
        ? `أُضيفت ${n} مدخلات.`
        : `أُضيف ${count(n, 'مدخل واحد', 'مدخلان', 'مدخلات', 'مدخلًا')}.`,
    importFailed: 'تعذّرت قراءة هذا الملف.',
    crashReports: 'مشاركة تقارير الأعطال',
    crashReportsDetail:
      'أرسل تقارير الأعطال والأخطاء للمساعدة في إصلاح المشكلات. تتضمن طراز جهازك وإصدار التطبيق، ولا تتضمن أبدًا عباداتك أو حسابك.',
    delete: 'احذف بياناتي',
    deleteDetail: 'كل ما على هذا الجهاز: الإعدادات وسجل ممارستك. يبدأ التطبيق من جديد.',
    deleteConfirmTitle: 'حذف كل شيء؟',
    deleteConfirmBody:
      'تُزال إعداداتك وسجل ممارستك من هذا الجهاز. لا توجد نسخة في أي مكان آخر إلا إن صدّرتها أو زامنتها مع حساب.',
    deleteConfirmBodySignedIn:
      'يزيل هذا إعداداتك وسجل ممارستك من هذا الجهاز فقط. يحتفظ حسابك بنسخته المتزامنة. لحذفها أيضًا، اذهب إلى «الحساب» ثم «حذف الحساب».',
    deleteConfirm: 'احذف',
    cancel: 'إلغاء',
    shareFailed: 'المشاركة غير متاحة على هذا الجهاز.',
  },
  memorise: {
    title: 'احفظه',
    start: 'تدرَّب',
    hide: 'أخفِ سطرًا آخر',
    known: 'أعرف هذا',
    knownDetail: 'يبقى في المكتبة ويتوقف عن الظهور في التنبيهات.',
    notKnown: 'ما زلت أتعلم',
    noAudio: 'لا تلاوة لهذا بعد.',
    play: 'تشغيل',
    stop: 'إيقاف',
    loop: 'تكرار',
  },
  language: {
    title: 'اللغة',
    restart:
      'العربية والأردية تُقرآن من اليمين إلى اليسار. التبديل إليهما أو منهما يعيد تشغيل التطبيق أو يطلب منك إعادة فتحه.',
    incomplete: 'الإنجليزية هي الأصل. كل لغة أخرى مسودة ما زالت تنتظر مراجعة متحدث مؤهل.',
    reopenTitle: 'أعد فتح إحسانلي',
    reopenBody:
      'هذه اللغة تُقرأ من اليمين إلى اليسار. أغلق إحسانلي ثم افتحه من جديد ليكتمل التغيير.',
    names: {
      en: 'English',
      ar: 'العربية',
      fr: 'Français',
      it: 'Italiano',
      ja: '日本語',
      hi: 'हिन्दी',
      ur: 'اردو',
      so: 'Soomaali',
      zh: '中文（普通话）',
      yue: '廣東話',
    },
  },
  appearance: {
    title: 'المظهر',
    system: 'النظام',
    light: 'فاتح',
    dark: 'داكن',
    note: 'الألوان تأتي من النظام على أي حال، فتنطبق إعدادات التباين فيه.',
  },
  diagnostics: {
    title: 'تقرير تشخيصي',
    explanation: 'هذا ما يحويه التقرير. لا يُرسل شيء حتى تختار إرساله، وأنت من يحدّد وجهته.',
    version: 'إصدار التطبيق',
    device: 'الجهاز',
    coordinates: 'إحداثيات تقريبية',
    noCoordinates: 'غير محفوظة',
    records: 'سجلات الممارسة',
    settings: 'الإعدادات المحفوظة',
    failures: 'إخفاقات مسجّلة',
    failuresDetail: (count: number): string => `${count} عالجها التطبيق دون إخبارك`,
    reminders: 'التذكيرات',
    remindersDetail: (permission: string, pending: number): string =>
      `${permission} · ${count(pending, 'مجدول واحد', 'مجدولان', 'مجدولة', 'مجدولة')}`,
    error: 'خطأ أخير',
    errorIncluded: 'مرفق واحد',
    showRaw: 'إظهار التقرير كاملًا',
    hideRaw: 'إخفاء التقرير كاملًا',
    send: 'أرسله',
    cancel: 'ليس الآن',
    reportProblem: 'الإبلاغ عن هذه المشكلة',
  },
  feedback: {
    title: 'إرسال ملاحظات',
    explanation:
      'أخبرنا بما حدث من خلل، أو بما يجعل Ihsaanly أفضل. لا يُرسل شيء حتى تضغط على إرسال.',
    signedOut:
      'تُرسل الملاحظات مع حسابك حتى نتمكن من الرد عليك وإبعاد الرسائل المزعجة. تسجيل الدخول اختياري لكل ما عدا ذلك في التطبيق.',
    signIn: 'سجّل الدخول لإرسال ملاحظاتك',
    emailFallback: 'تفضّل البريد الإلكتروني؟ راسلنا على {email}.',
    kindLabel: 'ما موضوع رسالتك؟',
    kinds: {
      bug: 'الإبلاغ عن مشكلة',
      idea: 'اقتراح فكرة',
      other: 'شيء آخر',
    },
    messageLabel: 'رسالتك',
    messagePlaceholder: 'ماذا حدث، أو ما الذي قد يفيد؟',
    counter: (used: number, max: number): string => `${used} / ${max}`,
    contactLabel: 'البريد الإلكتروني للتواصل',
    contactHint: 'اختياري. فقط إن أردت ردًّا.',
    contactPlaceholder: 'name@example.com',
    fillAccountEmail: (email: string): string => `استخدام ${email}`,
    includeDiagnostics: 'تضمين معلومات التشخيص',
    includeDiagnosticsDetail:
      'اختياري. إصدار التطبيق والجهاز والموقع التقريبي وعدد المشكلات. متوقف ما لم تفعّله.',
    showIncluded: 'اطّلع على ما سيُضمَّن',
    hideIncluded: 'إخفاء ما سيُضمَّن',
    privacy:
      'تُرسل إلى Moh’d Inc. مع حسابك لنتمكن من المتابعة معك. تُحفظ مدة تصل إلى سنتين. {privacy}',
    privacyLink: 'اقرأ سياسة الخصوصية',
    send: 'إرسال',
    sending: 'جارٍ الإرسال…',
    queuedTitle: 'حُفظت لوقت لاحق',
    queued: 'أنت غير متصل بالإنترنت. حُفظت ملاحظاتك على هذا الجهاز وستُرسل عند عودة الاتصال.',
    sentTitle: 'شكرًا لك',
    sent: 'أُرسلت ملاحظاتك.',
    done: 'تم',
    sendAnother: 'إرسال ملاحظات أخرى',
    errors: {
      'rate-limited': 'أرسلت ملاحظات قبل لحظات. انتظر دقيقة ثم حاول مجددًا.',
      network: 'تعذّر الاتصال. رسالتك ما زالت هنا. تحقق من اتصالك وحاول مجددًا.',
      'signed-out': 'حُفظت على هذا الجهاز وستُرسل بعد تسجيل الدخول.',
      invalid: 'تحقق من رسالتك وبريد التواصل الإلكتروني، ثم أرسل مجددًا.',
      unknown: 'حدث خطأ ما. رسالتك ما زالت هنا. حاول مرة أخرى.',
    },
  },
  about: {
    title: 'عن التطبيق',
    version: 'الإصدار',
    content: 'المحتوى',
    contentUnreviewed: (n: number): string =>
      `${count(n, 'عنصر واحد', 'عنصران', 'عناصر', 'عنصرًا')}، مسوّدة بانتظار مراجعة عالم مسمّى.`,
    contentReviewedBy: (name: string, n: number): string =>
      `${count(n, 'عنصر واحد', 'عنصران', 'عناصر', 'عنصرًا')}، راجعها ${name}.`,
    donate: 'تبرَّع',
    donateBody: 'اختياري، ولا يفتح شيئًا. كل ما في التطبيق مجاني ويبقى مجانيًا. يُفتح في المتصفح.',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfUse: 'شروط الاستخدام',
    privacyTitle: 'بياناتك تبقى على هذا الجهاز',
    privacyBody:
      'لا تحليلات ولا إعلانات. يُستخدم موقعك على هذا الجهاز لحساب أوقات الصلاة، ويُحفظ سجل ممارستك وإعداداتك هنا. يتحقق التطبيق من ihsaanly.app بحثًا عن تحديثات المحتوى، دون إرسال أي شيء عنك. وفيما عدا ذلك لا يخرج شيء من هذا الجهاز إلا باختيارك: التصدير أو المشاركة، أو إرسال ملاحظاتك، أو تفعيل تقارير الأعطال أو الإعلانات (في تطبيق iOS وAndroid)، أو تسجيل الدخول للمزامنة. تسجيل الدخول باستخدام Apple أو Google اختياري: عندها يُخزَّن اسمك وبريدك الإلكتروني وسجل ممارستك وتقدّمك وإعداداتك وموقعك التقريبي (بدقة نحو كيلومتر واحد) لدى Google Firebase في الولايات المتحدة، لتتزامن بين أجهزتك. يمكنك حذف حسابك في أي وقت من «الحساب». على Android، زر التبرّع يفتح متصفحك، وتلك الصفحة ليست جزءًا من إحسانلي.',
    licences: 'بُني بـ',
    licencesBody:
      'Expo وReact Native، ومكتبة adhan لأوقات الصلاة، وجداول تقويم أم القرى، وبيانات المدن من city-timezones (المبنية على GeoNames)، وNatural Earth للخريطة. كلٌّ برخصته المفتوحة، مذكورة في مستودع المصدر.',
    geonames: 'بيانات المدن © GeoNames (CC BY 4.0)',
  },
  moonSighting: {
    title: 'رؤية الهلال',
    explanation:
      'التواريخ في هذا التطبيق محسوبة. تختلف المجتمعات بين اتباع الحساب والرؤية المحلية، وكثيرًا ما يتفاوت الاثنان بيوم. اتبع من يتبعه مجتمعك، وعدّل التاريخ في الإعدادات ليوافقهم التطبيق.',
    disclaimer: 'هذه مذكورة لتجد جهتك بينها. التطبيق لا يتبنّى أيًّا منها.',
  },
  tracking: {
    title: 'التتبع',
    active: '\u0645\u0641\u0639\u0651\u0644',
    travelling: 'مسافر',
    travellingDetail: 'يُتاح القصر، وتتنحّى السنن الرواتب، ويُعرض الصيام ولا يُنتظر.',
    paused: 'إيقاف تتبع الصلاة',
    pausedDetail: 'لا تُسجَّل الصلوات ولا يتراكم قضاء. يبقى متوقفًا حتى تعيد تشغيله.',
    jumuah: 'صلاة الجمعة',
    jumuahChoice: {
      auto: 'تلقائي',
      attend: 'أحضر صلاة الجمعة',
      dhuhr: 'أصلي الظهر',
    },
    jumuahAutoDetail: 'الجمعة يوم الجمعة، إلا إن كنت مسافرًا أو اخترت «أخت».',
    checkIn: 'ذكّرني بالمراجعة',
    checkInAfter: (days: number): string =>
      `ذكّرني بعد نحو ${count(days, 'يوم', 'يومين', 'أيام', 'يومًا')}`,
    checkInOff: 'بلا تذكير. أعد تشغيل التتبع متى شئت.',
    checkInDays: 'الأيام',
  },
  hijri: {
    title: 'التاريخ الهجري',
    offset: 'تعديل التاريخ',
    approximate: 'محسوب — تأكد من الجهة التي يتبعها مجتمعك.',
    explanation:
      'كثيرًا ما يختلف التقويم المحسوب عن الرؤية المحلية بيوم أو يومين. حرّك التاريخ هنا ليوافق التطبيق مجتمعك. تُعرض تواريخ الصيام دائمًا على أنها متوقعة، لا مؤكدة.',
    offsetLabel: (days: number): string =>
      days === 0
        ? 'بلا تغيير'
        : `${days > 0 ? 'زيادة' : 'نقصان'} ${count(Math.abs(days), 'يوم', 'يومين', 'أيام', 'يومًا')}`,
    format: (day: number, month: string, year: number): string => `${day} ${month} ${year}`,
  },
  hijriMonth: {
    1: 'محرّم',
    2: 'صفر',
    3: 'ربيع الأول',
    4: 'ربيع الآخر',
    5: 'جمادى الأولى',
    6: 'جمادى الآخرة',
    7: 'رجب',
    8: 'شعبان',
    9: 'رمضان',
    10: 'شوّال',
    11: 'ذو القعدة',
    12: 'ذو الحجة',
  },
  calculation: {
    title: 'حساب مواقيت الصلاة',
    method: 'الطريقة',
    asr: 'العصر',
    highLatitude: 'العروض العليا',
    selected: 'مُحدَّد',
    explanation:
      'تُحسب المواقيت على هذا الجهاز ولا تُعرض أبدًا كأوقات بالساعة — إنما تحدد في أي جزء من اليوم أنت.',
    highLatitudeExplanation:
      'فوق نحو 48° شمالًا لا يقع وقت العشاء في جزء من السنة. هذا يحدد ما يُستخدم بدلًا منه.',
  },
  asr: {
    shafi: 'الجمهور',
    hanafi: 'الحنفي',
  },
  highLatitude: {
    middleofthenight: 'منتصف الليل',
    seventhofthenight: 'سُبع الليل',
    twilightangle: 'زاوية الشفق',
  },
  method: {
    MuslimWorldLeague: 'رابطة العالم الإسلامي',
    Egyptian: 'الهيئة المصرية العامة للمساحة',
    Karachi: 'جامعة العلوم الإسلامية، كراتشي',
    UmmAlQura: 'أم القرى، مكة',
    Dubai: 'دبي',
    MoonsightingCommittee: 'لجنة رؤية الهلال',
    NorthAmerica: 'الجمعية الإسلامية لأمريكا الشمالية',
    Kuwait: 'الكويت',
    Qatar: 'قطر',
    Singapore: 'سنغافورة',
    Tehran: 'طهران',
    Turkey: 'تركيا',
  },
  library: {
    title: 'المكتبة',
    empty: 'ستُدرج هنا الأذكار والأدعية والأعمال المسنونة.',
    search: 'ابحث بالاسم أو الموقف',
    searchLabel: 'البحث في المكتبة',
    noResults: 'لا شيء يطابق ذلك.',
    filterAll: 'الكل',
    filterOnToday: 'في «اليوم»',
    filterKnown: 'محفوظ',
    onToday: 'في «اليوم»',
    known: 'محفوظ',
    emptyOnToday: 'لا شيء في «اليوم» بعد. افتح أي عنصر وفعّله.',
    emptyKnown: 'لم تحدد شيئًا كمحفوظ بعد. تدرّب على عنصر ثم قل إنك حفظته.',
    terms: 'المصطلحات',
    termsDetail: 'السنة والرواتب والأذكار والقضاء وغيرها، في جملة لكل منها.',
  },
  category: {
    adhkar: 'الأذكار',
    dhikr: 'بعد الصلاة',
    fasting: 'الصيام',
    food: 'الطعام',
    home: 'المنزل',
    masjid: 'المسجد',
    prayer: 'الصلاة',
    quran: 'القرآن',
    charity: 'الصدقة',
    sleep: 'النوم والاستيقاظ',
    travel: 'السفر',
  },
  item: {
    done: 'تم',
    doneToday: 'أُنجز اليوم',
    undo: 'تراجع',
    counterReset: 'ابدأ من جديد',
    yourDay: 'يومك',
    onToday: 'في «اليوم»',
    onTodayDetail: 'يظهر حين يأتي وقته',
    remind: 'ذكّرني',
    remindWindow: 'عند دخول وقته',
    remindLookAhead: 'في المساء السابق',
    share: 'مشاركة',
    shareText: 'مشاركة كنص',
    shareImage: 'مشاركة كصورة',
    sharedFrom: 'من تطبيق إحسانلي',
    transliteration: 'النقل الصوتي',
    translation: 'الترجمة',
    why: 'لماذا',
    how: 'كيف',
    unreviewed: 'بانتظار المراجعة',
    evidence: 'الدليل',
    note: 'اختلف العلماء',
    repeat: (times: number): string => `كرِّر ${count(times, 'مرة واحدة', 'مرتين', 'مرات', 'مرة')}`,
    parts: 'ما تقوله',
    partRepeat: (times: number): string => count(times, 'مرة واحدة', 'مرتين', 'مرات', 'مرة'),
    gradedBy: (grader: string): string => `حكم عليه ${grader}`,
    quranReference: (surah: number, ayah: number): string => `القرآن ${surah}:${ayah}`,
  },
  glossary: {
    title: 'معاني الكلمات',
  },
  ruling: {
    fard: 'فرض',
    wajib: 'واجب',
    'sunnah-muakkadah': 'سنة مؤكدة',
    sunnah: 'سنة',
    mustahabb: 'مستحب',
    mubah: 'مباح',
  },
  grading: {
    sahih: 'صحيح',
    hasan: 'حسن',
    "da'if": 'ضعيف',
    disputed: 'مختلَف فيه',
  },
  more: {
    title: 'المزيد',
    search: 'ابحث في الإعدادات',
    searchLabel: 'البحث في «المزيد»',
    prayer: 'الصلاة',
    app: 'التطبيق',
    practice: 'ممارستك',
    empty: 'هنا سيكون السجل والإعدادات والمساعدة.',
    help: 'المساعدة',
    showMeAround: 'جولة تعريفية',
  },
  onboarding: {
    welcomeTitle: 'اللحظة، لا الساعة.',
    welcomeBody: 'يخبرك إحسانلي حين يحين وقت أذكار المساء. لا وقتًا بالساعة، ولا درجات.',
    howTitle: 'يعرض إحسانلي ما يناسب اللحظة. انقر على الدائرة حين تؤدّيه.',
    language: 'اللغة',
    appearance: 'المظهر',
    locationStep: 'أين أنت؟',
    locationWhy: 'يُستخدم على هذا الجهاز لتحديد أجزاء اليوم. يبقى عليه ما لم تسجّل الدخول للمزامنة.',
    genderStep: 'إيقاف التتبع',
    genderWhy:
      'في بعض الأيام ينبغي أن يتوقف تتبع الصلاة دون أن يتراكم قضاء. هذا يحدد إن كان التطبيق يعرض ذلك.',
    brother: 'أخ',
    brotherDetail: 'لا يُعرض الإيقاف',
    sister: 'أخت',
    sisterDetail: 'يُعرض الإيقاف',
    skip: 'أفضّل عدم الإجابة',
    skipDetail: 'يُعرض الإيقاف على أي حال.',
    genderPrivacy: 'يُحفظ على هذا الجهاز، ولا يُزامَن إلا إن سجّلت الدخول. ولا يُستخدم لغير ذلك.',
    remindersStep: 'الإشعارات',
    remindersWhy: 'اختر ما يصلك من إحسانلي. يمكنك تغيير أيٍّ منهما لاحقًا من «المزيد».',
    dailyReminders: 'التذكيرات اليومية',
    dailyRemindersDetail: 'أذكار الصباح والمساء وأيام الصيام القادمة، تُضبط على هذا الجهاز.',
    announcementsChoice: 'إعلانات من إحسانلي',
    announcementsChoiceDetail: 'أخبار متفرقة نرسلها نحن، مثل بداية رمضان. تبقى مُطفأة حتى تفعّلها.',
    startStep: 'نقطة بداية',
    startWhy: 'اختر حجمًا تبدأ به. أضِف أو أزِل ما تشاء من المكتبة في أي وقت.',
    starting: 'بداية فقط',
    startingDetail: (n: number): string =>
      `${count(n, 'شيء واحد', 'شيئان', 'أشياء', 'شيئًا')} تحملها من أول يوم: وقتان، وذكر، ودعاءان. لمن هذا كله جديد عليه.`,
    essentials: 'الأساسيات',
    essentialsDetail: (n: number): string =>
      `${count(n, 'عنصر واحد', 'عنصران', 'عناصر', 'عنصرًا')}، يوم معقول لا كامل. لمن يصلي ويريد السنن حول صلاته.`,
    everything: 'الكل',
    everythingDetail: (n: number): string =>
      `جميع العناصر، ${count(n, 'عنصر', 'عنصران', 'عناصر', 'عنصرًا')}. لمن يعرف المحتوى ويريد التقويم كله.`,
    skipIntro: 'تخطّي',
    skipLocation: 'تخطّي الآن',
    reminderPolicy: (perDay: number, from: number, to: number): string =>
      `${count(perDay, 'تنبيه واحد', 'تنبيهان', 'تنبيهات', 'تنبيهًا')} في اليوم على الأكثر، ولا شيء بين ${from}:00 و${to}:00.`,
    reminderCap: (perDay: number): string =>
      `${count(perDay, 'تنبيه واحد', 'تنبيهان', 'تنبيهات', 'تنبيهًا')} في اليوم على الأكثر.`,
    included: 'المتضمَّن',
    andMore: (n: number): string =>
      `و${count(n, 'عنصر آخر', 'عنصران آخران', 'عناصر أخرى', 'عنصرًا آخر')}`,
    back: 'رجوع',
    continue: 'متابعة',
    allowReminders: 'السماح بالتنبيهات',
    allowNotifications: 'السماح بالإشعارات',
    notNow: 'ليس الآن',
    done: 'ابدأ',
    restore: 'تستخدم Ihsaanly من قبل؟ سجّل الدخول لاستعادة بياناتك',
  },
  location: {
    title: 'الموقع',
    notSet: 'غير محدد',
    currentLocation: 'الموقع الحالي',
    useDevice: 'استخدم موقعي',
    useDeviceDetail: 'يبقى على هذا الجهاز ما لم تسجّل الدخول للمزامنة.',
    locating: 'جارٍ تحديد موقعك…',
    orSearch: 'أو ابحث عن مدينة',
    follows: 'ستتبع أوقات الصلاة هذا المكان.',
    search: 'ابحث عن مدينة',
    searchLabel: 'البحث عن المدن',
    noResults: 'لا مدن تطابق ذلك.',
    unavailable: 'خدمات الموقع معطّلة على هذا الجهاز. فعّلها، أو ابحث عن مدينتك بدلًا من ذلك.',
    declined: 'رُفض الوصول إلى الموقع. ابحث عن مدينتك بدلًا من ذلك — كل شيء يعمل كما هو.',
    explanation: 'يُستخدم على هذا الجهاز لتحديد أوقات الصلاة. يبقى عليه ما لم تسجّل الدخول للمزامنة.',
    attribution: 'بيانات المدن من city-timezones (MIT).',
  },
  textField: {
    clear: 'مسح',
  },
  error: {
    title: 'حدث خطأ ما',
    retry: 'أعد المحاولة',
  },
  notFound: {
    title: 'غير موجود',
    body: 'هذه الشاشة غير موجودة.',
  },
  widgets: {
    quickDuas: 'أدعية سريعة',
    duaOfTheDay: 'دعاء اليوم',
    nothingNow: 'لا شيء مطلوب منك الآن',
    openApp: 'افتح إحسانلي لتحديث هذا',
  },
  web: {
    remindersUnavailable:
      'التذكيرات تحتاج تطبيق الهاتف. المتصفح لا يستطيع تذكيرك عندما تُغلق الصفحة.',
    homeDetectionUnavailable: 'ملاحظة الوصول إلى المنزل تحتاج تطبيق الهاتف.',
    storageAtRisk: 'هذا المتصفح لا يحفظ بياناتك بشكل موثوق. صدّر نسخة احتياطية من البيانات.',
    openInApp: 'افتح في التطبيق',
    getApp: 'احصل على التطبيق',
    updateReady: 'يوجد إصدار جديد جاهز.',
    reload: 'إعادة التحميل',
    remindersThrough: (date: string): string =>
      `التذكيرات مضبوطة حتى ${date}. افتح إحسانلي قبل ذلك لتستمر.`,
    dismiss: 'تجاهل',
  },
  panel: {
    close: 'إغلاق',
    markAll: 'تسجيل الكل كمكتمل',
    progress: (count: number, target: number): string => `${count} من ${target}`,
    tapToCount: 'انقر للعد',
  },
}
