import type { SupportedLanguage } from '../i18n/locale'

/** The English table. Every other language must match its shape; see Strings. */
export const en = {
  tabs: {
    today: 'Today',
    library: 'Library',
    more: 'More',
  },
  today: {
    title: 'Today',
    nothingElse: 'Nothing else is asked of you today.',
    empty: 'Nothing here yet.',
    needsLocationTitle: 'Where are you?',
    needsLocation:
      'Prayer windows, the Hijri date and everything the day asks of you follow from a rough location. It is worked out on this device and stays there unless you sign in to sync.',
    chooseCity: 'Choose a city instead',
    chooseCityDetail: 'No permission needed. Everything still works.',
    prayerHint: "Tap a prayer when you've prayed it",
    markDone: (name: string): string => `Mark ${name} done`,
    unmark: (name: string): string => `Unmark ${name}`,
    countItem: (name: string, count: number, target: number): string =>
      `Count ${name}, ${count} of ${target}`,
    partsItem: (name: string, done: number, total: number): string =>
      `Parts of ${name}, ${done} of ${total} done`,
    open: (name: string): string => `Open ${name}`,
    doneToday: (count: number): string => `Done today (${count})`,
    markedDone: 'Marked done',
    undo: 'Undo',
    undoItem: (name: string): string => `Undo ${name}`,
    paused: 'Prayer tracking is paused',
    pausedFasting: 'Fasting resumes after your pause',
    checkInTitle: 'Ready to resume prayer tracking?',
    resume: 'Resume',
    notYet: 'Not yet',
  },
  tour: {
    prayer: 'Tap a circle to mark a prayer',
    sunnah: "Tap the circle beside a sunnah when you've done it",
    card: 'Tap the card to learn it: the words, meaning and source',
    step: (step: number, total: number): string => `${step} of ${total}`,
    skip: 'Skip',
    next: 'Next',
    done: 'Got it',
  },
  plan: {
    rightNow: 'Right now',
    tryOneMore: 'Try one more',
    add: 'Add',
    notNow: 'Not now',
    alsoNow: 'Also now',
    upNext: 'Up next',
    before: 'Before',
    after: 'After',
    soon: 'Soon',
    inAboutAnHour: 'In about an hour',
    inAboutHours: (hours: number): string => `In about ${hours} hours`,
    context: 'Where you are',
    comingUp: 'Later this week',
    alsoToday: 'Also today',
    tomorrow: 'Tomorrow',
    inDays: (days: number): string => `In ${days} days`,
    prayers: 'Prayers',
    optional: 'Optional',
    expected: 'Expected',
    confirmLocally: 'Confirm with your local authority',
    prayed: 'Prayed',
    makeUp: 'To make up',
    outstanding: (count: number): string => `${count} to make up`,
  },
  prayer: {
    fajr: 'Fajr',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghrib',
    isha: 'Isha',
    jumuah: "Jumu'ah",
  },
  window: {
    fajr: 'Fajr',
    sunrise: 'Morning',
    dhuhr: 'After Dhuhr',
    asr: 'Evening',
    maghrib: 'After Maghrib',
    isha: 'Night',
    jumuah: "After Jumu'ah",
  },
  notifications: {
    title: 'Reminders',
    windows: 'Morning and evening adhkar',
    lookAhead: 'Upcoming fasting days',
    prayers: 'Prayer reminders',
    prayersDetail: 'Off by default \u2014 your adhan app already does this.',
    quietHours: 'Quiet hours',
    quietHoursDetail: (from: number, to: number): string => `${from}:00 to ${to}:00`,
    quietHoursOff: 'Off',
    perDay: 'Daily limit',
    permission: 'Permission',
    permissionGranted: 'Allowed',
    permissionDenied: 'Turned off in system settings',
    permissionUndetermined: 'Not asked yet',
    permissionUnavailable: 'Not available on this device',
    openSettings: 'Open system settings',
    whichItems: 'Which items',
    whichItemsDetail: 'Only items that have a moment to remind you of appear here.',
    sendTest: 'Send a test reminder',
    sendTestDetail: 'Arrives in a few seconds.',
    announcements: 'Announcements',
    announcementsDetail:
      "Occasional messages from Ihsaanly, such as the start of Ramadan. Your daily reminders don't need this.",
    testTitle: 'A test reminder',
    testBody: 'This is what a reminder from Ihsaanly looks like.',
    pausedRemembrance: 'Time for remembrance',
    checkIn: 'A quick check-in from Ihsaanly',
    action: {
      done: 'Done',
      later: 'Later',
    },
    body: {
      window: 'Now, until the window closes.',
      windowUntil: (closes: string): string => `Open until ${closes}.`,
      tomorrow: 'Tomorrow.',
      prayerWindow: 'The time has entered. The window stays open until the next prayer.',
    },
  },
  event: {
    ascending: 'Going up',
    descending: 'Going down',
    driving: 'Driving',
    travel: 'Travelling',
    'leaving-home': 'Leaving home',
    'entering-home': 'Coming home',
  } as Record<string, string>,
  events: {
    title: 'Where you are',
    explanation:
      'Most of these moments cannot be detected by a phone at all \u2014 a lift, a hill, a staircase. Their duas are one tap away in the Library and on the widget instead.',
    detectHome: 'Notice when I leave home',
    detectHomeDetail:
      'Approximate. The phone notices a hundred metres or so from the door and up to a minute late, so treat it as a nudge rather than the moment.',
    setHome: 'Set home to my current place',
    homeUnset: 'Not set',
    homeNeeded: 'Nothing is being watched yet \u2014 set home below.',
    noPlaceYet: 'Set where you are first',
    manual: 'Tell the app instead',
    manualDetail: 'Raise a state yourself when no sensor can find it.',
  },
  qada: {
    title: 'To make up',
    intro:
      'Prayers owed from before you started tracking, and any owed since. A count, never a list. Counting starts from the first prayer you mark.',
    owed: 'Owed from before',
    madeUp: 'Made up now',
    record: (count: number): string => (count === 1 ? 'Record one' : `Record ${count}`),
    outstanding: (count: number): string => (count === 1 ? '1 owed' : `${count} owed`),
    none: 'Nothing owed',
    summary: (count: number): string => (count === 1 ? '1 prayer owed' : `${count} prayers owed`),
    manage: 'Adjust what you owe',
    manageDetail: 'Set what you carry over and record make-ups in one go.',
  },
  fasting: {
    title: 'Fasts',
    intro: 'Ramadan days you did not fast, and any owed from before. A count, never a list.',
    notFastingToday: 'Not fasting today',
    notFastingTodayDetail: 'Keeps one fast to make up later.',
    recordedToday: 'Noted: not fasting today',
    undo: 'Tap to undo',
    summary: (count: number): string =>
      count === 1 ? '1 fast to make up' : `${count} fasts to make up`,
    outstanding: (count: number): string => (count === 1 ? '1 owed' : `${count} owed`),
    none: 'Nothing owed',
    owed: 'Owed from before',
    recordMadeUp: 'Record one made up',
  },
  history: {
    title: 'History',
    empty: 'Nothing recorded yet.',
    firstWeek:
      'Each day you mark a prayer or finish an item is kept here. After a week you will see which prayers you tend to pray early and which items you keep.',
    daysActive: (days: number): string => `${days} ${days === 1 ? 'day' : 'days'} recorded`,
    prayers: 'Prayers',
    completed: 'Completed',
    times: (count: number): string => `${count} ${count === 1 ? 'time' : 'times'}`,
    early: (minutes: number): string => `usually about ${minutes} min into the window`,
    late: (minutes: number): string => `usually about ${minutes} min before it closes`,
  },
  account: {
    title: 'Account',
    notSignedIn: 'Not signed in',
    explanation:
      'Optional. Your data stays on this device unless you sign in. Signing in keeps your history, progress and settings — including your location — in sync across your devices.',
    continueWithApple: 'Continue with Apple',
    continueWithGoogle: 'Continue with Google',
    signInWithApple: 'Sign in with Apple',
    signInWithGoogle: 'Sign in with Google',
    agreement: 'By continuing, you agree to the {terms} and the {privacy}.',
    terms: 'Terms',
    privacy: 'Privacy Policy',
    notice:
      'Your practice record, settings and approximate location are stored with Google Firebase (US) so they sync, together with your name and email from Apple or Google. You must be 13 or older. Delete your account at any time.',
    signingIn: 'Signing in…',
    signInFailed: 'Sign-in did not finish. Nothing on this device has changed.',
    errors: {
      network: 'Could not connect. Check your connection and try again.',
      auth: 'The sign-in was not accepted. Try again.',
      sync: 'Your data could not be synced this time. It will try again.',
      unknown: 'Something went wrong. Try again.',
      'remove-blocked': 'Could not reach your account, so nothing was removed.',
      'link-conflict':
        'That sign-in already belongs to a different Ihsaanly account, so it was not linked. To use it here, export anything you want to keep from the other account, delete that account, then link again — or contact support.',
      'reauth-unavailable':
        'Deleting needs you to sign in again with Apple, which is not available here. Delete your account from the Ihsaanly app or companion.ihsaanly.app.',
    },
    signedInWith: { apple: 'Signed in with Apple', google: 'Signed in with Google' },
    lastSynced: (when: string): string => `Last synced ${when}`,
    neverSynced: 'Not synced yet',
    justNow: 'just now',
    minutesAgo: (n: number): string => `${n} min ago`,
    hoursAgo: (n: number): string => `${n} h ago`,
    daysAgo: (n: number): string => `${n} d ago`,
    syncing: 'Syncing…',
    upToDate: 'Up to date',
    syncFailed: 'The last sync did not finish. It will try again.',
    syncNow: 'Sync now',
    signOut: 'Sign out',
    signOutDetail: 'Stops syncing this device. Your account keeps its copy.',
    signOutTitle: 'Sign out?',
    signOutBody:
      'Your account keeps everything already synced. Choose what happens to the copy on this device.',
    keepData: 'Keep data on this device',
    removeData: 'Remove from this device',
    deleteAccount: 'Delete account',
    deleteAccountDetail: 'Erases your account and everything synced to it.',
    deleteTitle: 'Delete your account?',
    deleteBody:
      'Your account and all the data synced to it are permanently deleted from the cloud. This cannot be undone.',
    deleteConfirm: 'Delete account',
    deleteChoiceTitle: 'And the data on this device?',
    deleteChoiceBody:
      'Keep it to go on using the app without an account, or remove it so the app starts over.',
    mismatchTitle: 'This device has data from another account',
    mismatchBody:
      'Merge it into the account you are signed in to now, or clear this device and take this account’s data instead.',
    merge: 'Merge into this account',
    fresh: 'Start fresh on this device',
    cancel: 'Cancel',
    linkTitle: 'You already have an account',
    linkBody: (existing: string, attempted: string): string =>
      `This email already has an Ihsaanly account that uses ${existing}. Continue with ${existing} to open it — ${attempted} will be linked, so either works from now on.`,
    linkUnavailable:
      'This account uses Sign in with Apple, which is not offered here. Sign in on the Ihsaanly app or companion.ihsaanly.app, link Google under Account → Sign-in methods, then come back.',
    methodsTitle: 'Sign-in methods',
    methodLinked: (provider: string): string => `${provider}, linked`,
    linkProvider: (provider: string): string => `Link ${provider}`,
    methodsHint:
      'If you used Hide My Email with Apple, link Google here so both open the same account.',
    restore: {
      backToSetup: 'Back to setup',
      intro:
        'Sign in with the account you already use. Your settings, location and history come back with the first sync.',
      restoring: 'Restoring your data…',
      restored: 'Your data is back.',
      needsSetupTitle: 'Nothing to restore yet',
      needsSetupBody:
        'This account has not been set up. Carry on with setup — you stay signed in, and your choices sync as you go.',
      continueSetup: 'Continue setup',
      remindersTitle: 'Your reminders are on',
      remindersBody:
        'Your account has reminders turned on. Allow notifications here so they can arrive on this device too.',
    },
  },
  data: {
    title: 'Your data',
    explanation:
      'Everything here lives on this device. Nothing leaves it unless you send it yourself from this screen, or sign in to sync from Account.',
    export: 'Export my data',
    exportDetail: 'Readable text you can keep, or carry to another device.',
    importing: 'Import from a file',
    importDetail: 'Merges rather than replaces. Importing the same file twice changes nothing.',
    diagnostics: 'Send a diagnostic report',
    diagnosticsDetail:
      'For fixing a problem. Contains your settings, your practice record, your approximate coordinates and recent errors. You will see it before it is sent.',
    imported: (count: number): string => `Added ${count} ${count === 1 ? 'entry' : 'entries'}.`,
    importFailed: 'That file could not be read.',
    shareFailed: 'Sharing is not available on this device.',
    crashReports: 'Share crash reports',
    crashReportsDetail:
      'Send crash reports and errors to help fix problems. They include your device model and app version, never your practice or account.',
    delete: 'Delete my data',
    deleteDetail:
      'Everything on this device: settings and your practice record. The app starts over.',
    deleteConfirmTitle: 'Delete everything?',
    deleteConfirmBody:
      'Your settings and your practice record are removed from this device. Unless you exported them or synced them to an account, there is no copy anywhere else.',
    deleteConfirmBodySignedIn:
      'This removes your settings and practice record from this device only. Your account keeps its synced copy. To delete that too, go to Account → Delete account.',
    deleteConfirm: 'Delete',
    cancel: 'Cancel',
  },
  diagnostics: {
    title: 'Diagnostic report',
    explanation:
      'This is what the report contains. Nothing is sent until you choose to send it, and you pick where it goes.',
    version: 'App version',
    device: 'Device',
    coordinates: 'Approximate coordinates',
    noCoordinates: 'None stored',
    records: 'Practice records',
    settings: 'Settings stored',
    failures: 'Recorded failures',
    failuresDetail: (count: number): string => `${count} the app handled without telling you`,
    reminders: 'Reminders',
    remindersDetail: (permission: string, pending: number): string =>
      `${permission} · ${pending} queued`,
    error: 'Recent error',
    errorIncluded: 'One is included',
    showRaw: 'Show the whole report',
    hideRaw: 'Hide the whole report',
    send: 'Send it',
    cancel: 'Not now',
    reportProblem: 'Report this problem',
  },
  feedback: {
    title: 'Send feedback',
    explanation:
      'Tell us what went wrong, or what would make Ihsaanly better. Nothing is sent until you press Send.',
    signedOut:
      'Feedback is sent with your account, so we can follow up and keep spam out. Signing in is optional for everything else in the app.',
    signIn: 'Sign in to send feedback',
    emailFallback: 'Prefer email? Write to {email}.',
    kindLabel: 'What is it about?',
    kinds: {
      bug: 'Report a problem',
      idea: 'Suggest an idea',
      other: 'Something else',
    },
    messageLabel: 'Your message',
    messagePlaceholder: 'What happened, or what would help?',
    counter: (used: number, max: number): string => `${used} / ${max}`,
    contactLabel: 'Contact email',
    contactHint: 'Optional. Only if you would like a reply.',
    contactPlaceholder: 'name@example.com',
    fillAccountEmail: (email: string): string => `Use ${email}`,
    includeDiagnostics: 'Include diagnostic info',
    includeDiagnosticsDetail:
      'Optional. App version, device, approximate location and problem counts. Off unless you turn it on.',
    showIncluded: 'See what’s included',
    hideIncluded: 'Hide what’s included',
    privacy:
      'Sent to Mohd Inc. with your account so we can follow up. Kept for up to 2 years. {privacy}',
    privacyLink: 'Read the Privacy Policy',
    send: 'Send',
    sending: 'Sending…',
    queuedTitle: 'Saved for later',
    queued:
      'You are offline. Your feedback is saved on this device and will be sent when you are back online.',
    sentTitle: 'Thank you',
    sent: 'Your feedback was sent.',
    done: 'Done',
    sendAnother: 'Send another',
    errors: {
      'rate-limited': 'You sent feedback a moment ago. Wait a minute, then try again.',
      network:
        'Could not connect. Your message is still here. Check your connection and try again.',
      'signed-out': 'Saved on this device. It will be sent after you sign in.',
      invalid: 'Check your message and contact email, then send again.',
      unknown: 'Something went wrong. Your message is still here. Try again.',
    },
  },
  about: {
    title: 'About',
    version: 'Version',
    content: 'Content',
    contentUnreviewed: (count: number): string =>
      `${count} items, drafted and awaiting review by a named scholar.`,
    contentReviewedBy: (name: string, count: number): string =>
      `${count} items, reviewed by ${name}.`,
    donate: 'Donate',
    donateBody:
      'Optional, and it unlocks nothing. Every part of the app is free and stays free. Opens in your browser.',
    privacyPolicy: 'Privacy policy',
    termsOfUse: 'Terms of use',
    privacyTitle: 'Your data stays on this device',
    privacyBody:
      'No analytics and no ads. Your location is used on this device to work out prayer times, and your practice record and settings are kept here. Nothing leaves this device unless you export or share it yourself, or sign in to sync. Signing in with Apple or Google is optional: your name and email, practice record, progress, settings and approximate location (to about 1 km) are then stored with Google Firebase in the US, so they sync across your devices. Delete your account at any time from Account. Donate opens your browser, and that page is not part of Ihsaanly.',
    licences: 'Built with',
    licencesBody:
      'Expo and React Native, the adhan library for prayer times, Umm al-Qura calendar tables, city data from city-timezones (built on GeoNames), and Natural Earth for the map. Each is used under its own open licence, listed in the source repository.',
    geonames: 'City data © GeoNames (CC BY 4.0)',
  },
  memorise: {
    title: 'Learn it',
    start: 'Practise',
    hide: 'Hide one more',
    known: 'I know this',
    knownDetail: 'It stays in the Library. It stops appearing in reminders.',
    notKnown: 'Still learning',
    noAudio: 'No recitation yet for this one.',
    play: 'Play',
    stop: 'Stop',
    loop: 'Repeat',
  },
  language: {
    title: 'Language',
    restart:
      'Arabic and Urdu read right to left. Switching to or from them restarts the app, or asks you to reopen it.',
    incomplete:
      'English is the original. Every other language is a draft still awaiting review by a qualified speaker.',
    reopenTitle: 'Reopen Ihsaanly',
    reopenBody:
      'This language reads right to left. Close Ihsaanly and open it again for the change to finish.',
    names: {
      en: 'English',
      ar: 'العربية',
      fr: 'Français',
      it: 'Italiano',
      ja: '日本語',
      hi: 'हिन्दी',
      ur: 'اردو',
      so: 'Soomaali',
      zh: '中文（普通话）',
      yue: '廣東話',
    } as Record<SupportedLanguage, string>,
  },
  appearance: {
    title: 'Appearance',
    system: 'System',
    light: 'Light',
    dark: 'Dark',
    note: 'Colours still come from the system, so its contrast settings apply either way.',
  },
  moonSighting: {
    title: 'Moon sighting',
    explanation:
      'Dates in this app are calculated. Communities differ over whether to follow calculation or local sighting, and the two often disagree by a day. Follow whoever your own community follows, and adjust the date in settings so the app agrees with them.',
    disclaimer: 'These are listed so you can find yours. This app endorses none of them.',
  },
  tracking: {
    title: 'Tracking',
    active: 'Active',
    travelling: 'Travelling',
    travellingDetail:
      'Shortening is offered, the regular sunnah prayers step aside, and fasting is offered rather than expected.',
    paused: 'Pause prayer tracking',
    pausedDetail:
      'Prayers are not recorded and nothing accrues to make up. It stays off until you turn it back on.',
    jumuah: "Jumu'ah on Fridays",
    jumuahChoice: {
      auto: 'Automatic',
      attend: "I attend Jumu'ah",
      dhuhr: 'I pray Dhuhr',
    },
    jumuahAutoDetail: "Jumu'ah on Fridays unless you're travelling or chose Sister.",
    checkIn: 'Remind me to check in',
    checkInAfter: (days: number): string => `Remind me in about ${days} days`,
    checkInOff: 'No reminder. Turn tracking back on whenever you like.',
    checkInDays: 'Days',
  },
  hijri: {
    title: 'Hijri date',
    offset: 'Adjust the date',
    approximate: 'Calculated \u2014 confirm with the authority your community follows.',
    explanation:
      'A calculated calendar and local moon sighting often differ by a day or two. Shift the date here so the app agrees with your community. Dates for fasting days are always shown as expected, never as certain.',
    offsetLabel: (days: number): string =>
      days === 0
        ? 'No change'
        : `${days > 0 ? '+' : ''}${days} day${Math.abs(days) === 1 ? '' : 's'}`,
    format: (day: number, month: string, year: number): string => `${day} ${month} ${year}`,
  },
  hijriMonth: {
    1: 'Muharram',
    2: 'Safar',
    3: 'Rabi\u2019 al-Awwal',
    4: 'Rabi\u2019 ath-Thani',
    5: 'Jumada al-Ula',
    6: 'Jumada al-Akhirah',
    7: 'Rajab',
    8: 'Sha\u2019ban',
    9: 'Ramadan',
    10: 'Shawwal',
    11: 'Dhu al-Qa\u2019dah',
    12: 'Dhu al-Hijjah',
  } as Record<number, string>,
  calculation: {
    title: 'Prayer calculation',
    method: 'Method',
    asr: 'Asr',
    highLatitude: 'High latitude',
    selected: 'Selected',
    explanation:
      'Prayer times are computed on this device and never shown as clock times \u2014 they only decide which part of the day you are in.',
    highLatitudeExplanation:
      'Above roughly 48\u00b0 north, Isha does not occur for part of the year. This decides what is used instead.',
  },
  asr: {
    shafi: 'Standard',
    hanafi: 'Hanafi',
  },
  highLatitude: {
    middleofthenight: 'Middle of the night',
    seventhofthenight: 'Seventh of the night',
    twilightangle: 'Twilight angle',
  },
  method: {
    MuslimWorldLeague: 'Muslim World League',
    Egyptian: 'Egyptian General Authority',
    Karachi: 'University of Islamic Sciences, Karachi',
    UmmAlQura: 'Umm al-Qura, Makkah',
    Dubai: 'Dubai',
    MoonsightingCommittee: 'Moonsighting Committee',
    NorthAmerica: 'ISNA, North America',
    Kuwait: 'Kuwait',
    Qatar: 'Qatar',
    Singapore: 'Singapore',
    Tehran: 'Tehran',
    Turkey: 'Turkey',
  },
  library: {
    title: 'Library',
    empty: 'Adhkar, duas and sunnah actions will be listed here.',
    search: 'Search by name or situation',
    noResults: 'Nothing matches that.',
    filterAll: 'All',
    filterOnToday: 'On Today',
    filterKnown: 'Known',
    onToday: 'On Today',
    known: 'Known',
    emptyOnToday: 'Nothing is on Today yet. Open any item and turn it on.',
    emptyKnown: 'Nothing marked known yet. Practise an item and say when you have it.',
    terms: 'Glossary',
    termsDetail: 'Sunnah, rawatib, adhkar, qada and the rest, in a sentence each.',
  },
  category: {
    adhkar: 'Adhkar',
    dhikr: 'After prayer',
    fasting: 'Fasting',
    food: 'Eating',
    home: 'Home',
    masjid: 'Masjid',
    prayer: 'Prayer',
    quran: 'Qur\u2019an',
    charity: 'Charity',
    sleep: 'Sleep and waking',
    travel: 'Travel',
  } as Record<string, string>,
  item: {
    done: 'Done',
    doneToday: 'Done today',
    undo: 'Undo',
    counterReset: 'Start again',
    yourDay: 'Your day',
    onToday: 'On Today',
    onTodayDetail: 'Appears when its moment comes',
    remind: 'Remind me',
    remindWindow: 'When its window opens',
    remindLookAhead: 'The evening before',
    share: 'Share',
    shareText: 'Share as text',
    shareImage: 'Share as image',
    sharedFrom: 'Shared from Ihsaanly',
    transliteration: 'Transliteration',
    translation: 'Translation',
    why: 'Why',
    how: 'How',
    unreviewed: 'Awaiting review',
    evidence: 'Evidence',
    note: 'Scholars differ',
    repeat: (times: number): string => `Repeat ${times} times`,
    parts: 'What to say',
    partRepeat: (times: number): string => `${times} times`,
    gradedBy: (grader: string): string => `graded by ${grader}`,
    quranReference: (surah: number, ayah: number): string => `Qur\u2019an ${surah}:${ayah}`,
  },
  glossary: {
    title: 'What the words mean',
  },
  ruling: {
    fard: 'Obligatory',
    wajib: 'Obligatory',
    'sunnah-muakkadah': 'Emphasised sunnah',
    sunnah: 'Sunnah',
    mustahabb: 'Recommended',
    mubah: 'Permissible',
  },
  grading: {
    sahih: 'Sahih',
    hasan: 'Hasan',
    "da'if": 'Da\u2019if',
    disputed: 'Disputed',
  },
  more: {
    title: 'More',
    search: 'Search settings',
    prayer: 'Prayer',
    app: 'App',
    practice: 'Your practice',
    empty: 'History, settings and help will live here.',
    help: 'Help',
    showMeAround: 'Show me around',
  },
  onboarding: {
    welcomeTitle: 'The moment, not the clock.',
    welcomeBody:
      'Ihsaanly tells you when the evening adhkar are open. Never a time. Never a score.',
    howTitle: "Ihsaanly shows what fits the moment. Tap a circle when you've done it.",
    language: 'Language',
    appearance: 'Appearance',
    locationStep: 'Where are you?',
    locationWhy:
      'Used on this device to work out the parts of the day. It stays there unless you sign in to sync.',
    genderStep: 'The tracking pause',
    genderWhy:
      'On some days prayer tracking should stop, with nothing accruing to make up. This tells the app whether to offer that.',
    brother: 'Brother',
    brotherDetail: 'No pause',
    sister: 'Sister',
    sisterDetail: 'Pause offered',
    skip: 'Prefer not to say',
    skipDetail: 'The pause is offered anyway.',
    genderPrivacy: 'Stored on this device, and synced only if you sign in. Used for nothing else.',
    remindersStep: 'Notifications',
    remindersWhy: 'Choose what Ihsaanly may notify you about. Change either later in More.',
    dailyReminders: 'Daily reminders',
    dailyRemindersDetail:
      'Morning and evening adhkar and upcoming fasting days, scheduled on this device.',
    announcementsChoice: 'Announcements from Ihsaanly',
    announcementsChoiceDetail:
      'Occasional news, such as the start of Ramadan, sent by us. Off until you turn them on.',
    startStep: 'A starting point',
    startWhy:
      'Choose a size to begin with. Add or remove anything in the Library whenever you like.',
    starting: 'Just starting',
    startingDetail: (count: number): string =>
      `${count} things you can carry from day one: two windows, one dhikr, two duas. For someone new to all of this.`,
    essentials: 'Essentials',
    essentialsDetail: (count: number): string =>
      `${count} items, a reasonable day rather than a complete one. For someone who already prays and wants the sunnah around it.`,
    everything: 'Everything',
    everythingDetail: (count: number): string =>
      `All ${count} items. For someone who knows the content and wants the whole calendar.`,
    skipIntro: 'Skip',
    skipLocation: 'Skip for now',
    reminderPolicy: (perDay: number, from: number, to: number): string =>
      `At most ${perDay} a day, and nothing between ${from}:00 and ${to}:00.`,
    reminderCap: (perDay: number): string => `At most ${perDay} a day.`,
    included: 'Included',
    andMore: (count: number): string => `and ${count} more`,
    back: 'Back',
    continue: 'Continue',
    allowReminders: 'Allow reminders',
    allowNotifications: 'Allow notifications',
    notNow: 'Not now',
    done: 'Start',
    restore: 'Already use Ihsaanly? Sign in to restore your data',
  },
  location: {
    title: 'Location',
    notSet: 'Not set',
    currentLocation: 'Current location',
    useDevice: 'Use my location',
    useDeviceDetail: 'Stays on this device unless you sign in to sync.',
    locating: 'Finding you\u2026',
    orSearch: 'or search for a city',
    follows: 'Prayer windows will follow this place.',
    search: 'Search for a city',
    noResults: 'No cities match that.',
    unavailable:
      'Location services are switched off on this device. Turn them on, or search for your city instead.',
    declined:
      'Location access was declined. Search for your city instead \u2014 everything still works.',
    explanation:
      'Used on this device to work out prayer windows. It stays there unless you sign in to sync.',
    attribution: 'City data from city-timezones (MIT).',
  },
  textField: {
    clear: 'Clear',
  },
  error: {
    title: 'Something went wrong',
    retry: 'Try again',
  },
  notFound: {
    title: 'Not found',
    body: 'That screen does not exist.',
  },
  widgets: {
    quickDuas: 'Quick duas',
    duaOfTheDay: 'Dua of the day',
    nothingNow: 'Nothing asked of you right now',
    openApp: 'Open Ihsaanly to bring this up to date',
  },
  web: {
    remindersUnavailable:
      "Reminders need the phone app. A browser can't remind you while this page is closed.",
    homeDetectionUnavailable: 'Noticing when you get home needs the phone app.',
    storageAtRisk: "This browser isn't saving your data reliably. Export a backup from Data.",
    openInApp: 'Open in the app',
    getApp: 'Get the app',
    updateReady: 'A new version is ready.',
    reload: 'Reload',
    remindersThrough: (date: string): string =>
      `Reminders are set through ${date}. Open Ihsaanly before then to keep them going.`,
    dismiss: 'Dismiss',
  },
  panel: {
    close: 'Close',
    markAll: 'Mark all done',
    progress: (count: number, target: number): string => `${count} of ${target}`,
    tapToCount: 'Tap to count',
  },
}

export type Strings = typeof en
