import type { Strings } from './en'

/**
 * Somali interface copy, in standard Latin orthography. A complete draft,
 * written in one pass and awaiting review by a qualified speaker; that review
 * is a release condition. Content text (adhkar, duas, evidence) does not live
 * here.
 */

/** Somali counts: "hal" plus the singular for one, the number plus the counted plural otherwise. */
function count(n: number, one: string, many: string): string {
  return n === 1 ? one : `${n} ${many}`
}

export const so: Strings = {
  tabs: {
    today: 'Maanta',
    library: 'Maktabadda',
    more: 'Dheeraad',
  },
  today: {
    title: 'Maanta',
    nothingElse: 'Maanta wax kale lagaama rabo.',
    empty: 'Weli halkan waxba ma yaallaan.',
    needsLocationTitle: 'Xaggee joogtaa?',
    needsLocation:
      'Waqtiyada salaadda, taariikhda Hijriga iyo wax kasta oo maalintu kaa rabto waxay ku xiran yihiin goob qiyaas ah. Qalabkan ayaa lagu xisaabiyaa, halkaasna way ku jirtaa ilaa aad u gasho si loo iswaafajiyo.',
    chooseCity: 'Beddelkeeda magaalo dooro',
    chooseCityDetail: 'Ogolaansho looma baahna. Wax walba sidooda ayey u shaqeynayaan.',
    prayerHint: 'Salaad markaad tukato, taabo',
    markDone: (name: string): string => `Calaamadi ${name} inay dhammaatay`,
    unmark: (name: string): string => `Ka saar calaamadda ${name}`,
    countItem: (name: string, count: number, target: number): string =>
      `Tiri ${name}, ${count} ka mid ah ${target}`,
    partsItem: (name: string, done: number, total: number): string =>
      `Qaybaha ${name}, ${done} ka mid ah ${total} waa dhammaatay`,
    open: (name: string): string => `Fur ${name}`,
    doneToday: (count: number): string => `Maanta la sameeyey (${count})`,
    markedDone: 'Waa la calaamadeeyey',
    undo: 'Dib u celi',
    undoItem: (name: string): string => `Dib u celi ${name}`,
    paused: 'Diiwaangelinta salaadda waa la hakiyey',
    pausedFasting: 'Soonka wuu soo noqonayaa hakadkaaga kadib',
    checkInTitle: 'Diyaar ma u tahay inaad sii wadato diiwaangelinta salaadda?',
    resume: 'Sii wad',
    notYet: 'Weli ma aha',
  },
  tour: {
    prayer: 'Goobo taabo si aad salaad u calaamadiso',
    sunnah: 'Markaad sunno sameyso, taabo goobada ku xigta',
    card: 'Kaarka taabo si aad u barato: erayada, macnaha iyo isha',
    step: (step: number, total: number): string => `${step} ka mid ah ${total}`,
    skip: 'Ka bood',
    next: 'Xiga',
    done: 'Waan fahmay',
  },
  plan: {
    rightNow: 'Hadda',
    tryOneMore: 'Isku day mid kale',
    add: 'Ku dar',
    notNow: 'Hadda maya',
    alsoNow: 'Sidoo kale hadda',
    upNext: 'Xiga',
    before: 'Ka hor',
    after: 'Kadib',
    soon: 'Dhawaan',
    inAboutAnHour: 'Qiyaastii saacad kadib',
    inAboutHours: (hours: number): string =>
      `Qiyaastii ${count(hours, 'saacad', 'saacadood')} kadib`,
    context: 'Halka aad joogto',
    comingUp: 'Toddobaadkan dambe',
    alsoToday: 'Sidoo kale maanta',
    tomorrow: 'Berri',
    inDays: (days: number): string => `${count(days, 'Hal maalin', 'maalmood')} kadib`,
    prayers: 'Salaadaha',
    optional: 'Ikhtiyaari',
    expected: 'La filayo',
    confirmLocally: 'Ka xaqiiji hay’adda deegaankaaga',
    prayed: 'Waa la tukaday',
    makeUp: 'Qadaa',
    outstanding: (n: number): string => `${count(n, 'Hal salaad', 'salaadood')} oo qadaa ah`,
  },
  prayer: {
    fajr: 'Subax',
    dhuhr: 'Duhur',
    asr: 'Casar',
    maghrib: 'Maqrib',
    isha: 'Cishe',
    jumuah: 'Jimce',
  },
  window: {
    fajr: 'Subax',
    sunrise: 'Barqo',
    dhuhr: 'Duhur kadib',
    asr: 'Galab',
    maghrib: 'Maqrib kadib',
    isha: 'Habeen',
    jumuah: 'Jimce kadib',
  },
  notifications: {
    title: 'Xusuusiyeyaal',
    windows: 'Adkaarta subaxa iyo galabta',
    lookAhead: 'Maalmaha soonka ee soo socda',
    prayers: 'Xusuusiyeyaasha salaadda',
    prayersDetail: 'Si caadi ah waa dansan yihiin — abka aadaanku horeba wuu kuu qabtaa.',
    quietHours: 'Saacadaha aamusnaanta',
    quietHoursDetail: (from: number, to: number): string => `${from}:00 ilaa ${to}:00`,
    quietHoursOff: 'Dansan',
    perDay: 'Xadka maalinlaha ah',
    permission: 'Ogolaansho',
    permissionGranted: 'La oggolaaday',
    permissionDenied: 'Waa laga damiyey dejinta nidaamka',
    permissionUndetermined: 'Weli lama weydiin',
    permissionUnavailable: 'Qalabkan laguma heli karo',
    openSettings: 'Fur dejinta nidaamka',
    whichItems: 'Qodobbadee',
    whichItemsDetail: 'Waxaa halkan ka muuqda oo keliya qodobbada leh waqti lagugu xusuusiyo.',
    sendTest: 'Dir xusuusiye tijaabo ah',
    sendTestDetail: 'Dhowr ilbiriqsi gudahood ayuu imanayaa.',
    announcements: 'Ogeysiisyo',
    announcementsDetail:
      'Fariimo mararka qaarkood ka yimaada Ihsaanly, sida bilowga Ramadaan. Xusuusiyeyaashaada maalinlaha ah uma baahna tan.',
    testTitle: 'Xusuusiye tijaabo ah',
    testBody: 'Sidan ayuu u eg yahay xusuusiye ka yimaada Ihsaanly.',
    pausedRemembrance: 'Waa waqtigii adkaarta',
    checkIn: 'Salaan kooban oo ka yimid Ihsaanly',
    action: {
      done: 'Waa la sameeyey',
      later: 'Goor dambe',
    },
    body: {
      window: 'Hadda, ilaa waqtigu ka dhammaanayo.',
      windowUntil: (closes: string): string => `Furan ilaa ${closes}.`,
      tomorrow: 'Berri.',
      prayerWindow: 'Waqtigii waa galay. Wuu furnaanayaa ilaa salaadda xigta.',
    },
  },
  event: {
    ascending: 'Kor u bixid',
    descending: 'Hoos u degid',
    driving: 'Gaari wadid',
    travel: 'Safar',
    'leaving-home': 'Ka bixidda guriga',
    'entering-home': 'Guriga oo la yimaado',
  },
  events: {
    title: 'Halka aad joogto',
    explanation:
      'Inta badan xilliyadan taleefan ma ogaan karo gabi ahaanba — wiish, buur, jaranjaro. Ducooyinkooda hal taabasho ayey u jiraan, Maktabadda iyo widget-ka.',
    detectHome: 'I ogeysii markaan guriga ka baxo',
    detectHomeDetail:
      'Waa qiyaas. Taleefanku wuxuu dareemaa qiyaastii boqol mitir albaabka ka dib, ilaa daqiiqad dib u dhac ah, sidaa darteed u qaado xusuusin ee ha u qaadan xilliga saxda ah.',
    setHome: 'Ka dhig guriga meesha aan hadda joogo',
    homeUnset: 'Lama dejin',
    homeNeeded: 'Weli waxba lama ilaalinayo — hoos ka deji guriga.',
    noPlaceYet: 'Marka hore deji halka aad joogto',
    manual: 'Beddelkeeda abka u sheeg',
    manualDetail: 'Adigu xaalad kici marka aanu dareeme ogaan karin.',
  },
  qada: {
    title: 'Qadaa',
    intro:
      'Salaadaha kugu dhiman intaadan diiwaangelin bilaabin, iyo kuwa kugu dhiman tan iyo markaas. Tiro keliya, marna liis maaha. Tirintu waxay ka bilaabataa salaadda ugu horreysa ee aad calaamadiso.',
    owed: 'Kuwa hore kuugu dhiman',
    madeUp: 'Kuwa hadda la qadeeyey',
    record: (n: number): string => (n === 1 ? 'Diiwaan geli mid' : `Diiwaan geli ${n}`),
    outstanding: (n: number): string => `${n === 1 ? 'Hal' : n} baa kugu dhiman`,
    none: 'Waxba kuguma dhimna',
    summary: (n: number): string => `${count(n, 'Hal salaad', 'salaadood')} baa kugu dhiman`,
    manage: 'Hagaaji waxa kugu dhiman',
    manageDetail: 'Deji waxa aad soo wadato, oo hal mar ku diiwaan geli qadaada.',
  },
  fasting: {
    title: 'Soonka',
    intro:
      'Maalmaha Ramadaan ee aadan soomin, iyo kuwii hore kugu dhimanaa. Tiro keliya, marna liis maaha.',
    notFastingToday: 'Maanta soon ma ihi',
    notFastingTodayDetail: 'Hal maalin ayuu u haynayaa qadaa goor dambe ah.',
    recordedToday: 'Waa la qoray: maanta soon ma ihid',
    undo: 'Taabo si aad uga noqoto',
    summary: (n: number): string => `Qadaa soon: ${count(n, 'hal maalin', 'maalmood')}`,
    outstanding: (n: number): string =>
      n === 1 ? 'Hal maalin baa kugu dhiman' : `${n} maalmood baa kugu dhiman`,
    none: 'Waxba kuguma dhimna',
    owed: 'Kuwa hore kuugu dhiman',
    recordMadeUp: 'Diiwaan geli mid la qadeeyey',
  },
  history: {
    title: 'Taariikhda',
    empty: 'Weli waxba lama diiwaangelin.',
    firstWeek:
      'Maalin kasta oo aad salaad calaamadiso ama qodob dhammayso halkan ayaa lagu hayaa. Toddobaad kadib waxaad arki doontaa salaadaha aad badanaa goor hore tukato iyo qodobbada aad joogteyso.',
    daysActive: (days: number): string =>
      `${count(days, 'Hal maalin', 'maalmood')} ayaa la diiwaangeliyey`,
    prayers: 'Salaadaha',
    completed: 'La dhammeeyey',
    times: (n: number): string => (n === 1 ? 'hal mar' : `${n} jeer`),
    early: (minutes: number): string =>
      `badanaa qiyaastii ${minutes} daqiiqo marka waqtigu galo kadib`,
    late: (minutes: number): string =>
      `badanaa qiyaastii ${minutes} daqiiqo ka hor inta waqtigu uusan bixin`,
  },
  account: {
    title: 'Akoon',
    notSignedIn: 'Lama gelin',
    explanation:
      'Ikhtiyaari. Xogtaadu waxay ku jirtaa qalabkan ilaa aad gasho. Gelitaanku wuxuu ka dhigayaa taariikhdaada, horumarkaaga iyo dejintaada, oo goobtaada ku jirto, mid ku wada iswaafaqsan dhammaan qalabkaaga.',
    continueWithApple: 'Ku sii wad Apple',
    continueWithGoogle: 'Ku sii wad Google',
    signInWithApple: 'Ku gal Apple',
    signInWithGoogle: 'Ku gal Google',
    agreement: 'Markaad sii wadato, waxaad aqbashay {terms} iyo {privacy}.',
    terms: 'Shuruudaha',
    privacy: 'Siyaasadda asturnaanta',
    notice:
      'Diiwaanka camalkaaga, dejintaada iyo goobtaada qiyaasta ah waxaa lagu kaydiyaa Google Firebase (Maraykanka) si ay u iswaafaqaan, iyadoo ay la socdaan magacaaga iyo iimaylkaaga ee Apple ama Google. Waa inaad jirtaa 13 sano ama ka badan, ama da’da uu dalkaagu shardi ka dhigo (ilaa 16). Akoonkaaga waqti kasta tirtir.',
    signingIn: 'Waa la gelayaa…',
    signInFailed: 'Gelitaanku ma dhammaan. Waxba kuma beddelmin qalabkan.',
    errors: {
      network: 'Lama xiriiri karo. Hubi xiriirkaaga oo isku day mar kale.',
      auth: 'Gelitaanka lama aqbalin. Isku day mar kale.',
      sync: 'Xogtaada lama iswaafajin karin markan. Mar kale ayuu isku dayi doonaa.',
      unknown: 'Wax baa khaldamay. Isku day mar kale.',
      'remove-blocked': 'Akoonkaaga lama gaari karin, sidaas darteed waxba lama saarin.',
      'link-conflict':
        'Gelitaankan horeyba wuxuu u dhigmaa akoon Ihsaanly ah oo kale, sidaas darteed lama xiriirin. Si aad halkan u isticmaasho, ka soo dhoofi wixii aad rabto inaad haysato akoonka kale, tirtir akoonkaas, dabadeed mar kale xiriir, ama la xiriir taageerada.',
      'reauth-unavailable':
        'Tirtiriddu waxay kaa doonaysaa inaad mar kale ku gasho Apple, taas oo aan halkan laga heli karin. Akoonkaaga ka tirtir app-ka Ihsaanly ama companion.ihsaanly.app.',
    },
    signedInWith: { apple: 'Waxaad ku gashay Apple', google: 'Waxaad ku gashay Google' },
    lastSynced: (when: string): string => `Isku-waafajintii ugu dambeysay: ${when}`,
    neverSynced: 'Weli lama isku waafajin',
    justNow: 'hadda',
    minutesAgo: (n: number): string => `${n} daqiiqo kahor`,
    hoursAgo: (n: number): string => `${n} saac kahor`,
    daysAgo: (n: number): string => `${n} maalin kahor`,
    syncing: 'Waa la isku waafajinayaa…',
    upToDate: 'Wax walba waa la isku waafajiyey',
    syncFailed: 'Isku-waafajintii ugu dambeysay ma dhammaan. Mar kale ayaa la isku dayi doonaa.',
    syncNow: 'Hadda isku waafaji',
    signOut: 'Ka bax',
    signOutDetail: 'Waxay joojisaa isku-waafajinta qalabkan. Akoonkaagu wuu haysanayaa nuqulkiisa.',
    signOutTitle: 'Ma ka baxaysaa?',
    signOutBody:
      'Akoonkaagu wuxuu haystaa wax kasta oo hore loo isku waafajiyey. Dooro waxa ku dhici doona nuqulka qalabkan ku jira.',
    keepData: 'Xogta ku hay qalabkan',
    removeData: 'Ka saar qalabkan',
    deleteAccount: 'Tirtir akoonka',
    deleteAccountDetail: 'Waxay tirtirtaa akoonkaaga iyo wax kasta oo lagu isku waafajiyey.',
    deleteTitle: 'Akoonkaaga ma tirtiraa?',
    deleteBody:
      'Akoonkaaga iyo dhammaan xogta lagu isku waafajiyey waa laga tirtirayaa daruur, weligoodna. Lama celin karo.',
    deleteConfirm: 'Tirtir akoonka',
    deleteChoiceTitle: 'Xogta qalabkan ku jirtana?',
    deleteChoiceBody:
      'Ku hay si aad abka ugu sii isticmaasho akoon la’aan, ama ka saar si abku mar kale u bilaabmo.',
    mismatchTitle: 'Qalabkan waxaa ku jira xog akoon kale',
    mismatchBody: 'Ku dar akoonka aad hadda gashay, ama nadiifi qalabkan oo qaado xogta akoonkan.',
    merge: 'Ku dar akoonkan',
    fresh: 'Qalabkan ka bilow cusub',
    cancel: 'Jooji',
    linkTitle: 'Horeyba akoon ayaad leedahay',
    linkBody: (existing: string, attempted: string): string =>
      `Iimaylkan horeyba wuxuu leeyahay akoon Ihsaanly ah oo isticmaala ${existing}. Ku sii wad ${existing} si aad u furto; ${attempted} waa lagu xiri doonaa, markaa labadaba way shaqayn doonaan hadda ka dib.`,
    linkUnavailable:
      'Akoonkan wuxuu isticmaalaa Ku gal Apple, taas oo halkan lagu bixin. Ku gal app-ka Ihsaanly ama companion.ihsaanly.app, ku xiriir Google Akoon → Hababka gelitaanka, kadibna dib u soo noqo.',
    methodsTitle: 'Hababka gelitaanka',
    methodLinked: (provider: string): string => `${provider}, la xiriiriyey`,
    linkProvider: (provider: string): string => `Xiriir ${provider}`,
    methodsHint:
      'Haddii aad Apple la isticmaashay “Hide My Email”, halkan ku xiriir Google si labaduba u furaan isla akoonka.',
    restore: {
      backToSetup: 'Ku noqo dejinta',
      intro:
        'Ku gal akoonka aad horey u isticmaashay. Dejintaada, goobtaada iyo taariikhdaadu waxay la soo noqonayaan iswaafajinta ugu horreysa.',
      restoring: 'Xogtaada ayaa la soo celinayaa…',
      restored: 'Xogtaadii way soo noqotay.',
      needsSetupTitle: 'Weli wax la soo celiyo ma jiraan',
      needsSetupBody:
        'Akoonkan weli lama dejin. Sii wad dejinta — waad sii jiraysaa adigoo galay, doorashooyinkaaguna way iswaafajinayaan markaad socotid.',
      continueSetup: 'Sii wad dejinta',
      remindersTitle: 'Xusuusiyeyaashaadu way shidan yihiin',
      remindersBody:
        'Akoonkaagu xusuusiyeyaal ayuu shidan yahay. Halkan ku oggolow ogeysiisyada si ay qalabkan sidoo kale ugu yimaadaan.',
    },
  },
  data: {
    title: 'Xogtaada',
    explanation:
      'Wax walba oo halkan ah waxay ku jiraan qalabkan. Waxba kama baxaan ilaa adigu aad ka dirto shaashaddan, ama aad Akoon ka gasho si loo iswaafajiyo.',
    export: 'Dhoofi xogtayda',
    exportDetail: 'Qoraal la akhriyi karo oo aad hayn karto, ama u qaadan karto qalab kale.',
    importing: 'Ka soo gali fayl',
    importDetail:
      'Wuu isku daraa, ma beddelo. Isla faylka oo laba jeer la soo geliyo waxba ma beddelo.',
    diagnostics: 'Dir warbixin cilad-baaris',
    diagnosticsDetail:
      'Waxaa loogu talagalay xallinta dhibaato. Waxay ka kooban tahay dejintaada, diiwaanka camalkaaga, isku-duwayaashaada qiyaasta ah iyo khaladaadkii dhowaa. Waad arki doontaa inta aan la dirin.',
    imported: (n: number): string => `Waxaa lagu daray ${count(n, 'hal diiwaan', 'diiwaan')}.`,
    importFailed: 'Faylkaas lama akhriyi karo.',
    shareFailed: 'Wadaagistu qalabkan kama shaqeyso.',
    crashReports: 'La wadaag warbixinnada burburka',
    crashReportsDetail:
      'Dir warbixinnada burburka iyo khaladaadka si looga caawiyo hagaajinta dhibaatooyinka. Waxaa ku jira nooca qalabkaaga iyo nooca app-ka, marna cibaadadaada ama akoonkaaga.',
    delete: 'Tirtir xogtayda',
    deleteDetail:
      'Wax walba oo qalabkan ku jira: dejinta iyo diiwaanka camalkaaga. Abku mar kale ayuu bilaabanayaa.',
    deleteConfirmTitle: 'Wax walba ma la tirtiraa?',
    deleteConfirmBody:
      'Dejintaada iyo diiwaanka camalkaaga waa laga saarayaa qalabkan. Haddii aadan dhoofin ama aadan akoon la iswaafajin, meel kale nuqul kuma jiro.',
    deleteConfirmBodySignedIn:
      'Tani waxay dejintaada iyo diiwaanka camalkaaga ka saaraysaa qalabkan oo keliya. Akoonkaagu wuxuu hayaa nuqulkiisa la iswaafajiyay. Si aad kaas u tirtirto, tag Akoon → Tirtir akoonka.',
    deleteConfirm: 'Tirtir',
    cancel: 'Jooji',
  },
  diagnostics: {
    title: 'Warbixinta cilad-baarista',
    explanation:
      'Kani waa waxa warbixintu ka kooban tahay. Waxba lama dirayo ilaa aad doorato inaad dirto, adigaana dooranaya meesha ay u socoto.',
    version: 'Nooca abka',
    device: 'Qalabka',
    coordinates: 'Isku-duwayaasha qiyaasta ah',
    noCoordinates: 'Waxba lama kaydin',
    records: 'Diiwaanka camalka',
    settings: 'Dejinta la kaydiyey',
    failures: 'Cilladaha la diiwaangeliyey',
    failuresDetail: (n: number): string => `${n} uu abku xalliyey adigoon loo sheegin`,
    reminders: 'Xusuusiyeyaal',
    remindersDetail: (permission: string, pending: number): string =>
      `${permission} · ${pending} sugaya`,
    error: 'Khaladkii ugu dambeeyey',
    errorIncluded: 'Mid ayaa ku jira',
    showRaw: 'Tus warbixinta oo dhan',
    hideRaw: 'Qari warbixinta oo dhan',
    send: 'Dir',
    cancel: 'Hadda maya',
    reportProblem: 'Sheeg dhibaatadan',
  },
  feedback: {
    title: 'Dir fikrad',
    explanation:
      'Noo sheeg waxa khaldamay, ama waxa Ihsaanly ka dhigi kara mid ka wanaagsan. Waxba lama dirayo ilaa aad riixdo Dir.',
    signedOut:
      'Fikradda waxaa lagu diraa akoonkaaga, si aan kuugu jawaabno oo aan u celino fariimaha aan loo baahnayn. Gelitaanku waa ikhtiyaari wixii kale ee abka ku jira.',
    signIn: 'Gal si aad fikrad u dirto',
    emailFallback: 'Ma door bidaysaa iimaylka? Ku qor {email}.',
    kindLabel: 'Maxay ku saabsan tahay?',
    kinds: {
      bug: 'Sheeg dhibaato',
      idea: 'Soo jeedi fikrad',
      other: 'Wax kale',
    },
    messageLabel: 'Fariintaada',
    messagePlaceholder: 'Maxaa dhacay, ama maxaa caawin lahaa?',
    counter: (used: number, max: number): string => `${used} / ${max}`,
    contactLabel: 'Iimaylka xiriirka',
    contactHint: 'Ikhtiyaari. Kaliya haddii aad jawaab rabto.',
    contactPlaceholder: 'name@example.com',
    fillAccountEmail: (email: string): string => `Isticmaal ${email}`,
    includeDiagnostics: 'Ku dar macluumaadka cilad-baarista',
    includeDiagnosticsDetail:
      'Ikhtiyaari. Nooca abka, qalabka, goob qiyaas ah iyo tirada dhibaatooyinka. Waa dansan yahay ilaa aad shid.',
    showIncluded: 'Arag waxa ku jira',
    hideIncluded: 'Qari waxa ku jira',
    privacy:
      'Waxaa loo diraa Moh’d Inc. oo lala socdo akoonkaaga si aan kuugu soo laabanno. Waxaa la haynayaa ilaa 2 sano. {privacy}',
    privacyLink: 'Akhri Siyaasadda Asturnaanta',
    send: 'Dir',
    sending: 'Waa la dirayaa…',
    queuedTitle: 'Loo keydiyay mar dambe',
    queued:
      'Khadka ma joogtid. Fikraddaada waxaa lagu keydiyay qalabkan, waxaana la direyaa marka aad dib ugu soo noqoto khadka.',
    sentTitle: 'Mahadsanid',
    sent: 'Fikraddaada waa la diray.',
    done: 'Waa dhammaatay',
    sendAnother: 'Dir mid kale',
    errors: {
      'rate-limited': 'Hadda yar ayaad fikrad dirtay. Hal daqiiqo sug, kadibna isku day mar kale.',
      network:
        'Lama xiriiri karin. Fariintaadu halkan way taal. Hubi xiriirkaaga oo isku day mar kale.',
      'signed-out': 'Waxaa lagu keydiyay qalabkan. Waa la diri doonaa marka aad gasho.',
      invalid: 'Hubi fariintaada iyo iimaylka xiriirka, kadibna mar kale dir.',
      unknown: 'Wax baa khaldamay. Fariintaadu halkan way taal. Isku day mar kale.',
    },
  },
  about: {
    title: 'Ku saabsan',
    version: 'Nooca',
    content: 'Waxa ku jira',
    contentUnreviewed: (n: number): string =>
      `${n} qodob, qabyo ah oo sugaya in aqoonyahan diini ah oo magaciisa la sheegay dib u eego.`,
    contentReviewedBy: (name: string, n: number): string => `${n} qodob, uu dib u eegay ${name}.`,
    donate: 'Deeq bixi',
    donateBody:
      'Waa ikhtiyaari, waxna kuuma furayso. Qayb kasta oo abka ah waa bilaash, bilaashna way ahaan doontaa. Waxay ka furmaysaa biraawsarkaaga.',
    privacyPolicy: 'Siyaasadda asturnaanta',
    termsOfUse: 'Shuruudaha isticmaalka',
    privacyTitle: 'Xogtaadu waxay ku jirtaa qalabkan',
    privacyBody:
      'Ma jiro falanqayn iyo xayeysiis toona. Goobtaada waxaa qalabkan loogu isticmaalaa xisaabinta waqtiyada salaadda, diiwaanka camalkaaga iyo dejintaaduna halkan ayay ku jiraan. Appku wuxuu ihsaanly.app ka hubiyaa cusboonaysiinta nuxurka, isagoon waxba kaa dirin. Intaas ka sokow waxba kama baxaan qalabkan haddii aadan adigu dooran: dhoofin ama wadaag, dirista fikrad, shidista warbixinnada burburka ama ogeysiisyada (appka iOS iyo Android), ama gelitaan si loo iswaafajiyo. Gelitaanka Apple ama Google waa ikhtiyaari: markaas magacaaga iyo iimaylkaaga, diiwaanka camalkaaga, horumarkaaga, dejintaada iyo goobtaada qiyaasta ah (ilaa 1 km) waxaa lagu kaydiyaa Google Firebase ee Maraykanka, si ay ugu iswaafaqaan qalabkaaga. Akoonkaaga waqti kasta ka tirtir Akoon. Android-ka, Deeqdu waxay furaysaa browser-kaaga, boggaasuna qayb kama aha Ihsaanly.',
    licences: 'Waxaa lagu dhisay',
    licencesBody:
      'Expo iyo React Native, maktabadda adhan ee waqtiyada salaadda, jaantusyada kalandarka Umm al-Qura, xogta magaalooyinka ee city-timezones (oo ku dhisan GeoNames), iyo Natural Earth ee khariidadda. Mid kasta waxaa loo isticmaalaa sida ruqsaddiisa furan, oo ku qoran kaydka koodka.',
    geonames: 'Xogta magaalooyinka © GeoNames (CC BY 4.0)',
  },
  memorise: {
    title: 'Baro',
    start: 'Ku celceli',
    hide: 'Qari mid kale',
    known: 'Waan aqaan',
    knownDetail: 'Maktabadda ayuu ku jiraa. Xusuusiyeyaasha kama soo muuqdo mar dambe.',
    notKnown: 'Weli waan baranayaa',
    noAudio: 'Kan weli akhris cod ah uma laha.',
    play: 'Shid',
    stop: 'Jooji',
    loop: 'Ku celi',
  },
  language: {
    title: 'Luqadda',
    restart:
      'Carabigu wuxuu ka akhrismaa midig ilaa bidix. U beddelidda ama ka beddelidda waxay dib u bilaabaysaa abka, ama waxay kaa codsanaysaa inaad dib u furto.',
    incomplete:
      'Ingiriisigu waa asalka. Luqad kasta oo kale waa qabyo weli sugaysa dib u eegis qof si fiican u yaqaan.',
    reopenTitle: 'Dib u fur Ihsaanly',
    reopenBody:
      'Luqaddan waxay ka akhrismaa midig ilaa bidix. Xir Ihsaanly oo mar kale fur si isbeddelku u dhammaado.',
    names: {
      en: 'English',
      ar: 'العربية',
      fr: 'Français',
      it: 'Italiano',
      ja: '日本語',
      hi: 'हिन्दी',
      ur: 'اردو',
      so: 'Soomaali',
      zh: '中文（普通话）',
      yue: '廣東話',
    },
  },
  appearance: {
    title: 'Muuqaalka',
    system: 'Nidaamka',
    light: 'Iftiin',
    dark: 'Mugdi',
    note: 'Midabbadu weli nidaamka ayey ka yimaadaan, sidaa darteed dejintiisa kala-soocidda midabka way shaqeysaa labada xaaladoodba.',
  },
  moonSighting: {
    title: 'Muuqashada bisha',
    explanation:
      'Taariikhaha abkan waa la xisaabiyaa. Bulshooyinku way ku kala duwan yihiin inay raacaan xisaabta ama muuqashada deegaanka, labaduna inta badan hal maalin ayey ku kala duwan yihiin. Raac cidda bulshadaadu raacdo, oo taariikhda ka hagaaji dejinta si abku ula jaanqaado.',
    disclaimer: 'Kuwan waxaa loo taxay si aad taada u hesho. Abkani midkoodna ma taageerayo.',
  },
  tracking: {
    title: 'Diiwaangelinta',
    active: 'Shaqeynaysa',
    travelling: 'Safar',
    travellingDetail:
      'Gaabinta salaadda waa laguu soo bandhigayaa, sunnooyinka joogtada ah waa la dhinac dhigayaa, soonkuna waa laguu soo jeedinayaa, lagaama filayo.',
    paused: 'Hakad geli diiwaangelinta salaadda',
    pausedDetail:
      'Salaadaha lama diiwaangelinayo, qadaana kuma soo kordhayso. Way dansanaanaysaa ilaa aad dib u shiddo.',
    jumuah: 'Jimcaha maalinta Jimcaha',
    jumuahChoice: {
      auto: 'Si toos ah',
      attend: 'Waxaan tukadaa Jimcaha',
      dhuhr: 'Waxaan tukadaa Duhur',
    },
    jumuahAutoDetail:
      'Jimce maalinta Jimcaha, haddii aadan safar ku jirin ama aadan dooran "Walaal (dhedig)".',
    checkIn: 'I xusuusi inaan hubiyo',
    checkInAfter: (days: number): string =>
      `I xusuusi qiyaastii ${count(days, 'hal maalin', 'maalmood')} kadib`,
    checkInOff: 'Xusuusin ma jirto. Dib u shid diiwaangelinta markaad rabto.',
    checkInDays: 'Maalmo',
  },
  hijri: {
    title: 'Taariikhda Hijriga',
    offset: 'Hagaaji taariikhda',
    approximate: 'La xisaabiyey — ka xaqiiji hay’adda ay bulshadaadu raacdo.',
    explanation:
      'Kalandar la xisaabiyey iyo muuqashada bisha ee deegaanku inta badan hal ama laba maalmood ayey ku kala duwan yihiin. Halkan ka dhaqaaji taariikhda si abku ula jaanqaado bulshadaada. Taariikhaha maalmaha soonka had iyo jeer waxaa loo muujiyaa sida la filayo, marna sida hubaal ah.',
    offsetLabel: (days: number): string =>
      days === 0
        ? 'Isbeddel ma leh'
        : `${days > 0 ? '+' : ''}${days} ${Math.abs(days) === 1 ? 'maalin' : 'maalmood'}`,
    format: (day: number, month: string, year: number): string => `${day} ${month} ${year}`,
  },
  hijriMonth: {
    1: 'Muxarram',
    2: 'Safar',
    3: 'Rabiicul Awwal',
    4: 'Rabiicul Aakhir',
    5: 'Jamaadal Uulaa',
    6: 'Jamaadal Aakhira',
    7: 'Rajab',
    8: 'Shacbaan',
    9: 'Ramadaan',
    10: 'Shawwaal',
    11: 'Dul Qacda',
    12: 'Dul Xijja',
  },
  calculation: {
    title: 'Xisaabinta salaadda',
    method: 'Habka',
    asr: 'Casar',
    highLatitude: 'Loolka sare',
    selected: 'La doortay',
    explanation:
      'Waqtiyada salaadda qalabkan ayaa lagu xisaabiyaa, marna saacad ahaan looma muujiyo — waxay go’aamiyaan oo keliya qaybta maalinta aad ku jirto.',
    highLatitudeExplanation:
      'Qiyaastii 48° waqooyi wixii ka sarreeya, Cishuhu ma dhaco qayb ka mid ah sannadka. Tani waxay go’aamisaa waxa beddelkeeda la isticmaalo.',
  },
  asr: {
    shafi: 'Caadi',
    hanafi: 'Xanafi',
  },
  highLatitude: {
    middleofthenight: 'Bartamaha habeenka',
    seventhofthenight: 'Toddobaad meelood oo habeenka ah',
    twilightangle: 'Xagasha shafaqa',
  },
  method: {
    MuslimWorldLeague: 'Ururka Caalamka Islaamka',
    Egyptian: 'Hay’adda Guud ee Masar',
    Karachi: 'Jaamacadda Cilmiga Islaamka, Karachi',
    UmmAlQura: 'Umm al-Qura, Makka',
    Dubai: 'Dubay',
    MoonsightingCommittee: 'Guddiga Muuqashada Bisha',
    NorthAmerica: 'ISNA, Waqooyiga Ameerika',
    Kuwait: 'Kuwayt',
    Qatar: 'Qadar',
    Singapore: 'Singabuur',
    Tehran: 'Tehraan',
    Turkey: 'Turkiga',
  },
  library: {
    title: 'Maktabadda',
    empty: 'Adkaarta, ducooyinka iyo camallada sunnada ah halkan ayaa lagu taxi doonaa.',
    search: 'Ku raadi magac ama xaalad',
    searchLabel: 'Raadi maktabadda',
    noResults: 'Waxba lama mid aha.',
    filterAll: 'Dhammaan',
    filterOnToday: 'Maanta ku jira',
    filterKnown: 'La yaqaan',
    onToday: 'Maanta ku jira',
    known: 'La yaqaan',
    emptyOnToday: 'Weli waxba kuma jiraan Maanta. Fur qodob kasta oo shid.',
    emptyKnown:
      'Weli waxba looma calaamadin la yaqaan. Ku celceli qodob, oo sheeg marka aad xafiddo.',
    terms: 'Qaamuuska ereyada',
    termsDetail: 'Sunno, rawaatib, adkaar, qadaa iyo inta kale, mid kasta hal weedh.',
  },
  category: {
    adhkar: 'Adkaar',
    dhikr: 'Salaadda kadib',
    fasting: 'Soon',
    food: 'Cunid',
    home: 'Guri',
    masjid: 'Masaajid',
    prayer: 'Salaad',
    quran: "Qur'aanka",
    charity: 'Sadaqo',
    sleep: 'Hurdo iyo toosid',
    travel: 'Safar',
  },
  item: {
    done: 'Waa la sameeyey',
    doneToday: 'Maanta waa la sameeyey',
    undo: 'Ka noqo',
    counterReset: 'Dib u bilow',
    yourDay: 'Maalintaada',
    onToday: 'Maanta ku jira',
    onTodayDetail: 'Wuxuu soo muuqdaa marka xilligiisu yimaado',
    remind: 'I xusuusi',
    remindWindow: 'Marka waqtigiisu furmo',
    remindLookAhead: 'Fiidka ka horreeya',
    share: 'La wadaag',
    shareText: 'U wadaag qoraal ahaan',
    shareImage: 'U wadaag sawir ahaan',
    sharedFrom: 'Laga soo wadaagay Ihsaanly',
    transliteration: 'Higgaadda Laatiinka',
    translation: 'Macnaha',
    why: 'Sababta',
    how: 'Sida loo sameeyo',
    unreviewed: 'Sugaya dib u eegis',
    evidence: 'Daliilka',
    note: 'Culimadu way ku kala duwan yihiin',
    repeat: (times: number): string => `Ku celi ${times} jeer`,
    parts: 'Waxa la yiraahdo',
    partRepeat: (times: number): string => `${times} jeer`,
    gradedBy: (grader: string): string => `waxaa darajeeyey ${grader}`,
    quranReference: (surah: number, ayah: number): string => `Qur’aanka ${surah}:${ayah}`,
  },
  glossary: {
    title: 'Macnaha ereyada',
  },
  ruling: {
    fard: 'Faral',
    wajib: 'Waajib',
    'sunnah-muakkadah': 'Sunno la adkeeyey',
    sunnah: 'Sunno',
    mustahabb: 'Mustaxab',
    mubah: 'Bannaan',
  },
  grading: {
    sahih: 'Saxiix',
    hasan: 'Xasan',
    "da'if": 'Daciif',
    disputed: 'Lagu kala duwan yahay',
  },
  more: {
    title: 'Dheeraad',
    search: 'Raadi dejinta',
    searchLabel: 'Raadi Dheeraad',
    prayer: 'Salaadda',
    app: 'Abka',
    practice: 'Camalkaaga',
    empty: 'Taariikhda, dejinta iyo caawimaaddu halkan ayey ku jiri doonaan.',
    help: 'Caawimaad',
    showMeAround: 'Igu tus appka',
  },
  onboarding: {
    welcomeTitle: 'Xilliga, ee maaha saacadda.',
    welcomeBody:
      'Ihsaanly wuxuu kuu sheegaa marka adkaarta galabtu furan yihiin. Marna saacad maaha. Marna dhibco maaha.',
    howTitle: 'Ihsaanly wuxuu muujiyaa waxa waqtigan ku habboon. Goobo taabo markaad sameyso.',
    language: 'Luqadda',
    appearance: 'Muuqaalka',
    locationStep: 'Xaggee joogtaa?',
    locationWhy:
      'Qalabkan ayaa loogu isticmaalaa ogaanshaha qaybaha maalinta. Halkaas ayay ku jirtaa ilaa aad gasho si loo iswaafajiyo.',
    genderStep: 'Hakadka diiwaangelinta',
    genderWhy:
      'Maalmaha qaarkood diiwaangelinta salaadda waa inay joogsato, iyadoo aan qadaa soo kordhin. Tani waxay abka u sheegaysaa inuu taas soo bandhigo iyo in kale.',
    brother: 'Walaal (lab)',
    brotherDetail: 'Hakad ma jiro',
    sister: 'Walaal (dhedig)',
    sisterDetail: 'Hakad waa la soo bandhigayaa',
    skip: 'Door inaanan sheegin',
    skipDetail: 'Hakadka si kastaba waa la soo bandhigayaa.',
    genderPrivacy:
      'Qalabkan ayaa lagu kaydiyaa, waxaana la iswaafajiyaa oo keliya haddii aad gasho. Wax kale looma isticmaalo.',
    remindersStep: 'Fariimaha',
    remindersWhy: 'Dooro waxa Ihsaanly kuu soo diri karto. Labadaba goor dambe ka beddel Dheeraad.',
    dailyReminders: 'Xusuusiyeyaasha maalinlaha ah',
    dailyRemindersDetail:
      'Adkaarta subaxa iyo galabta iyo maalmaha soonka ee soo socda, lagu dejiyay qalabkan.',
    announcementsChoice: 'Ogeysiisyo ka yimaada Ihsaanly',
    announcementsChoiceDetail:
      'War mararka qaarkood ah, sida bilowga Ramadaan, oo annagu soo dirno. Way dansan yihiin ilaa aad shiddo.',
    startStep: 'Meel laga bilaabo',
    startWhy:
      'Dooro cabbir aad ku bilowdo. Wax kasta Maktabadda ku dar ama ka saar goorta aad rabto.',
    starting: 'Hadda bilaabaya',
    startingDetail: (n: number): string =>
      `${n} shay oo aad qaadi karto maalinta koowaad: laba waqti, hal dikri, laba duco. Qof waxan oo dhan ku cusub.`,
    essentials: 'Aasaasiga',
    essentialsDetail: (n: number): string =>
      `${n} qodob, maalin macquul ah ee maaha mid dhammaystiran. Qof horeba tukada oo raba sunnada ku xeeran.`,
    everything: 'Wax walba',
    everythingDetail: (n: number): string =>
      `Dhammaan ${n} qodob. Qof yaqaan waxa ku jira oo raba kalandarka oo dhan.`,
    skipIntro: 'Ka bood',
    skipLocation: 'Hadda ka bood',
    reminderPolicy: (perDay: number, from: number, to: number): string =>
      `Ugu badnaan ${perDay} maalintii, waxbana ${from}:00 iyo ${to}:00 dhexdooda.`,
    reminderCap: (perDay: number): string => `Ugu badnaan ${perDay} maalintii.`,
    included: 'Ku jira',
    andMore: (n: number): string => `iyo ${n} kale`,
    back: 'Dib',
    continue: 'Sii wad',
    allowReminders: 'Oggolow xusuusiyeyaasha',
    allowNotifications: 'Oggolow fariimaha',
    notNow: 'Hadda maya',
    done: 'Bilow',
    restore: 'Horey ma u isticmaashaa Ihsaanly? Gal si aad xogtaada u soo celiso',
  },
  location: {
    title: 'Goobta',
    notSet: 'Lama dejin',
    currentLocation: 'Goobta hadda',
    useDevice: 'Isticmaal goobtayda',
    useDeviceDetail: 'Qalabkan ayay ku jirtaa ilaa aad gasho si loo iswaafajiyo.',
    locating: 'Waa lagu raadinayaa…',
    orSearch: 'ama raadi magaalo',
    follows: 'Waqtiyada salaadda waxay raaci doonaan meeshan.',
    search: 'Raadi magaalo',
    searchLabel: 'Raadinta magaalooyinka',
    noResults: 'Magaalo taas la mid ah lama helin.',
    unavailable:
      'Adeegyada goobta waa laga damiyey qalabkan. Shid, ama beddelkeeda raadi magaaladaada.',
    declined:
      'Helitaanka goobta waa la diiday. Beddelkeeda raadi magaaladaada — wax walba way shaqeynayaan.',
    explanation:
      'Qalabkan ayaa loogu isticmaalaa ogaanshaha waqtiyada salaadda. Halkaas ayay ku jirtaa ilaa aad gasho si loo iswaafajiyo.',
    attribution: 'Xogta magaalooyinka waxaa laga qaatay city-timezones (MIT).',
  },
  textField: {
    clear: 'Tirtir',
  },
  error: {
    title: 'Wax baa khaldamay',
    retry: 'Isku day mar kale',
  },
  notFound: {
    title: 'Lama helin',
    body: 'Shaashaddaas ma jirto.',
  },
  widgets: {
    quickDuas: 'Duco degdeg ah',
    duaOfTheDay: 'Ducada maanta',
    nothingNow: 'Hadda waxba lagaa rabo ma jiraan',
    openApp: 'Fur Ihsaanly si aad u cusboonaysiiso',
  },
  web: {
    remindersUnavailable:
      'Xasuusinta waxay u baahan tahay abka taleefanka. Biraawsarku kuma xasuusin karo marka boggu xirmo.',
    homeDetectionUnavailable: 'Ogaanshaha guriga waxay u baahan tahay abka taleefanka.',
    storageAtRisk: 'Biraawsarkani si hubaal ah uma kaydinayo xogtaada. Ka soo dhoofi backup Xogta.',
    openInApp: 'Kaga fur abka',
    getApp: 'Hel abka',
    updateReady: 'Nooc cusub ayaa diyaar ah.',
    reload: 'Dib u soo rar',
    remindersThrough: (date: string): string =>
      `Xusuusinnada waxaa loo dejiyay ilaa ${date}. Fur Ihsaanly ka hor si ay u sii socdaan.`,
    dismiss: 'Iska daa',
  },
  panel: {
    close: 'Xir',
    markAll: 'Dhammaan calaamadi',
    progress: (count: number, target: number): string => `${count} ka mid ah ${target}`,
    tapToCount: 'Taabo si aad u tirisid',
  },
}
