import type { Strings } from './en'

/**
 * Simplified Chinese (Mandarin) interface copy. A complete draft, written in
 * one pass and awaiting review by a qualified speaker; the review is a release
 * condition, not a nicety. Content text (adhkar, duas, evidence) does not live
 * here.
 */
export const zh: Strings = {
  tabs: {
    today: '今天',
    library: '资料库',
    more: '更多',
  },
  today: {
    title: '今天',
    nothingElse: '今天没有别的要做了。',
    empty: '这里还没有内容。',
    needsLocationTitle: '你在哪里？',
    needsLocation:
      '礼拜时段、伊斯兰历日期以及一天中的各项功课，都依据一个大致的位置来推算。推算在这台设备上完成，除非你登录以同步，否则位置只留在这台设备上。',
    chooseCity: '改为选择城市',
    chooseCityDetail: '无需授权，所有功能照常可用。',
  },
  plan: {
    rightNow: '此刻',
    tryOneMore: '再试一项',
    add: '添加',
    notNow: '暂不',
    alsoNow: '此刻还有',
    upNext: '接下来',
    before: '之前',
    after: '之后',
    soon: '很快',
    inAboutAnHour: '大约一小时后',
    inAboutHours: (hours: number): string => `大约 ${hours} 小时后`,
    context: '你所在的情境',
    comingUp: '本周稍后',
    alsoToday: '今天还有',
    tomorrow: '明天',
    inDays: (days: number): string => `${days} 天后`,
    prayers: '礼拜',
    optional: '可选',
    expected: '预计',
    confirmLocally: '请向当地权威机构确认',
    prayed: '已礼',
    makeUp: '待补礼',
    outstanding: (count: number): string => `${count} 番待补礼`,
  },
  prayer: {
    fajr: '晨礼',
    dhuhr: '晌礼',
    asr: '晡礼',
    maghrib: '昏礼',
    isha: '宵礼',
    jumuah: '主麻',
  },
  window: {
    fajr: '晨礼',
    sunrise: '上午',
    dhuhr: '晌礼后',
    asr: '傍晚',
    maghrib: '昏礼后',
    isha: '夜间',
    jumuah: '主麻后',
  },
  notifications: {
    title: '提醒',
    windows: '早晚记念',
    lookAhead: '即将到来的斋戒日',
    prayers: '礼拜提醒',
    prayersDetail: '默认关闭——你的宣礼应用已经在做这件事。',
    quietHours: '免打扰时段',
    quietHoursDetail: (from: number, to: number): string => `${from}:00 至 ${to}:00`,
    quietHoursOff: '关闭',
    perDay: '每日上限',
    permission: '权限',
    permissionGranted: '已允许',
    permissionDenied: '已在系统设置中关闭',
    permissionUndetermined: '尚未询问',
    permissionUnavailable: '此设备不支持',
    openSettings: '打开系统设置',
    whichItems: '提醒哪些功课',
    whichItemsDetail: '这里只列出有特定时机可以提醒的功课。',
    sendTest: '发送一条测试提醒',
    sendTestDetail: '几秒钟后送达。',
    testTitle: '测试提醒',
    testBody: '这就是 Ihsaanly 提醒的样子。',
    action: {
      done: '完成',
      later: '稍后',
    },
    body: {
      window: '就是现在，直到这个时段结束。',
      windowUntil: (closes: string): string => `开放至 ${closes}。`,
      tomorrow: '明天。',
      prayerWindow: '礼拜时间已到。这个时段一直开放到下一番礼拜。',
    },
  },
  event: {
    ascending: '上行',
    descending: '下行',
    driving: '驾车',
    travel: '旅行',
    'leaving-home': '出门',
    'entering-home': '回家',
  },
  events: {
    title: '你所在的情境',
    explanation:
      '这些时刻大多根本无法由手机察觉——电梯、山坡、楼梯。它们的杜阿在资料库和小组件中，一点即可打开。',
    detectHome: '在我出门时提醒我',
    detectHomeDetail:
      '只是大致的。手机大约在离家门一百米左右、最多晚一分钟时才会察觉，所以把它当作一个提示，而不是那个确切的时刻。',
    setHome: '把当前位置设为家',
    homeUnset: '未设置',
    homeNeeded: '目前还没有在留意任何情境——请在下方设置家的位置。',
    noPlaceYet: '请先设置你所在的位置',
    manual: '改为手动告诉应用',
    manualDetail: '当没有传感器能察觉时，自己标记当前的状态。',
  },
  qada: {
    title: '补礼',
    intro:
      '开始记录之前欠下的礼拜，以及之后欠下的。只是一个数字，从不列出清单。从你标记的第一番礼拜开始计数。',
    owed: '之前欠下的',
    madeUp: '现在补礼',
    record: (count: number): string => (count === 1 ? '记录一番' : `记录 ${count} 番`),
    outstanding: (count: number): string => `欠 ${count} 番`,
    none: '没有欠下的',
    summary: (count: number): string => `欠 ${count} 番礼拜`,
    manage: '调整所欠的数目',
    manageDetail: '一次性设定延续下来的数目并记录补礼。',
  },
  fasting: {
    title: '斋戒',
    intro: '莱麦丹月中没有封斋的日子，以及之前欠下的。只是一个数字，从不列出清单。',
    notFastingToday: '今天不封斋',
    notFastingTodayDetail: '记下一天，留待日后补斋。',
    recordedToday: '已记下：今天不封斋',
    undo: '点按撤销',
    summary: (count: number): string => `${count} 天待补斋`,
    outstanding: (count: number): string => `欠 ${count} 天`,
    none: '没有欠下的',
    owed: '之前欠下的',
    recordMadeUp: '记录补斋一天',
  },
  history: {
    title: '记录',
    empty: '还没有任何记录。',
    firstWeek:
      '你每天标记的礼拜和完成的功课都会保存在这里。一周之后，你会看到哪些礼拜你常常礼得早，哪些功课你一直坚持。',
    daysActive: (days: number): string => `已记录 ${days} 天`,
    prayers: '礼拜',
    completed: '已完成',
    times: (count: number): string => `${count} 次`,
    early: (minutes: number): string => `通常在时段开始后约 ${minutes} 分钟`,
    late: (minutes: number): string => `通常在时段结束前约 ${minutes} 分钟`,
  },
  account: {
    title: '账户',
    notSignedIn: '未登录',
    explanation:
      '可选。除非你登录，否则你的数据只会留在这台设备上。登录后，你的记录、进度和设置（包括你的位置）会在你的所有设备之间同步。',
    continueWithApple: '通过 Apple 继续',
    continueWithGoogle: '通过 Google 继续',
    signInWithApple: '通过 Apple 登录',
    signInWithGoogle: '使用 Google 账号登录',
    agreement: '继续即表示你同意{terms}和{privacy}。',
    terms: '使用条款',
    privacy: '隐私政策',
    notice:
      '为了同步，你的功课记录、设置和大致位置会连同 Apple 或 Google 提供的姓名和邮箱，一起存储在 Google Firebase（美国）上。你必须年满 13 岁。你可以随时删除账户。',
    signingIn: '正在登录…',
    signInFailed: '登录未完成。这台设备上的内容没有任何变化。',
    errors: {
      network: '无法连接。请检查网络后重试。',
      auth: '登录未被接受。请重试。',
      sync: '这次未能同步你的数据。稍后会再试。',
      unknown: '出了点问题。请重试。',
      'remove-blocked': '无法连接到你的账户，因此没有移除任何内容。',
      'link-conflict':
        '该登录方式已属于另一个 Ihsaanly 账户，因此没有关联。若要在此使用，请先从另一个账户导出你想保留的内容，删除该账户，然后重新关联，或联系支持团队。',
      'reauth-unavailable':
        '删除需要你再次使用 Apple 登录，但此处无法使用。请在 Ihsaanly App 或 companion.ihsaanly.app 中删除你的账户。',
    },
    signedInWith: { apple: '已通过 Apple 登录', google: '已通过 Google 登录' },
    lastSynced: (when: string): string => `上次同步：${when}`,
    neverSynced: '尚未同步',
    justNow: '刚刚',
    minutesAgo: (n: number): string => `${n} 分钟前`,
    hoursAgo: (n: number): string => `${n} 小时前`,
    daysAgo: (n: number): string => `${n} 天前`,
    syncing: '正在同步…',
    upToDate: '已是最新',
    syncFailed: '上次同步未完成。稍后会再试。',
    syncNow: '立即同步',
    signOut: '退出登录',
    signOutDetail: '停止这台设备的同步。你的账户会保留它的副本。',
    signOutTitle: '退出登录？',
    signOutBody: '你的账户会保留所有已同步的内容。请选择如何处理这台设备上的副本。',
    keepData: '在这台设备上保留数据',
    removeData: '从这台设备上移除',
    deleteAccount: '删除账户',
    deleteAccountDetail: '清除你的账户及其中所有已同步的内容。',
    deleteTitle: '删除你的账户？',
    deleteBody: '你的账户及所有已同步的数据将从云端永久删除，无法撤销。',
    deleteConfirm: '删除账户',
    deleteChoiceTitle: '这台设备上的数据怎么办？',
    deleteChoiceBody: '保留它，即可无需账户继续使用应用；移除它，应用将从头开始。',
    mismatchTitle: '这台设备上有另一个账户的数据',
    mismatchBody: '可以合并到你当前登录的账户，也可以清除这台设备，改用此账户的数据。',
    merge: '合并到此账户',
    fresh: '在这台设备上重新开始',
    cancel: '取消',
    linkTitle: '你已有账户',
    linkBody: (existing: string, attempted: string): string =>
      `此邮箱已有一个使用 ${existing} 的 Ihsaanly 账户。请使用 ${existing} 继续以打开该账户；${attempted} 将被关联，此后两者都可使用。`,
    linkUnavailable:
      '此账户使用“通过 Apple 登录”，但此处不提供该方式。请在 Ihsaanly App 或 companion.ihsaanly.app 中登录，在“账户”→“登录方式”中关联 Google，然后再回来。',
    methodsTitle: '登录方式',
    methodLinked: (provider: string): string => `${provider}（已关联）`,
    linkProvider: (provider: string): string => `关联 ${provider}`,
    methodsHint:
      '如果你曾通过 Apple 使用“隐藏我的邮件地址”，请在此关联 Google，这样两者会打开同一个账户。',
    restore: {
      backToSetup: '返回设置',
      intro: '使用你已有的账户登录。你的设置、位置和记录会随第一次同步回来。',
      restoring: '正在恢复你的数据…',
      restored: '你的数据已恢复。',
      needsSetupTitle: '暂时没有可恢复的内容',
      needsSetupBody: '这个账户还没有完成设置。继续设置吧——你会保持登录，你的选择会随时同步。',
      continueSetup: '继续设置',
      remindersTitle: '你的提醒已开启',
      remindersBody: '你的账户开启了提醒。请在这里允许通知，这样提醒也能送达这台设备。',
    },
  },
  data: {
    title: '你的数据',
    explanation:
      '这里的一切都保存在这台设备上。除非你自己从这个页面发送，或在“账户”中登录以同步，否则什么都不会离开它。',
    export: '导出我的数据',
    exportDetail: '可读的文本，你可以保存，也可以带到另一台设备上。',
    importing: '从文件导入',
    importDetail: '合并而非替换。同一个文件导入两次不会有任何变化。',
    diagnostics: '发送诊断报告',
    diagnosticsDetail:
      '用于排查问题。包含你的设置、功课记录、大致坐标和最近的错误。发送之前你会先看到它的内容。',
    imported: (count: number): string => `已添加 ${count} 条记录。`,
    importFailed: '无法读取该文件。',
    shareFailed: '此设备不支持分享。',
    delete: '删除我的数据',
    deleteDetail: '这台设备上的一切：设置和你的功课记录。应用将从头开始。',
    deleteConfirmTitle: '删除所有内容？',
    deleteConfirmBody:
      '你的设置和功课记录将从这台设备上移除。除非你导出过，或已同步到账户，否则别处没有任何副本。',
    deleteConfirmBodySignedIn:
      '这只会从这台设备上移除你的设置和功课记录。你的账户仍保留已同步的副本。如要一并删除，请前往“账户”→“删除账户”。',
    deleteConfirm: '删除',
    cancel: '取消',
  },
  diagnostics: {
    title: '诊断报告',
    explanation: '这就是报告包含的内容。在你选择发送之前什么都不会发出，发送到哪里也由你决定。',
    version: '应用版本',
    device: '设备',
    coordinates: '大致坐标',
    noCoordinates: '未保存',
    records: '功课记录',
    settings: '已保存的设置',
    failures: '已记录的故障',
    failuresDetail: (count: number): string => `${count} 个，应用已自行处理，未打扰你`,
    reminders: '提醒',
    remindersDetail: (permission: string, pending: number): string =>
      `${permission} · ${pending} 条待发`,
    error: '最近的错误',
    errorIncluded: '已包含一条',
    showRaw: '显示完整报告',
    hideRaw: '隐藏完整报告',
    send: '发送',
    cancel: '暂不',
    reportProblem: '报告此问题',
  },
  feedback: {
    title: '发送反馈',
    explanation:
      '告诉我们哪里出了问题，或者怎样能让 Ihsaanly 更好。在你点按“发送”之前，不会发出任何内容。',
    signedOut:
      '反馈会连同你的账户一起发送，这样我们可以回复你，也能挡住垃圾信息。应用的其他功能无需登录。',
    signIn: '登录后发送反馈',
    emailFallback: '更想用邮件？请写信到 {email}。',
    kindLabel: '与什么有关？',
    kinds: {
      bug: '报告问题',
      idea: '提个建议',
      other: '其他',
    },
    messageLabel: '你的消息',
    messagePlaceholder: '发生了什么，或者什么会有帮助？',
    counter: (used: number, max: number): string => `${used} / ${max}`,
    contactLabel: '联系邮箱',
    contactHint: '可选。仅在你希望收到回复时填写。',
    contactPlaceholder: 'name@example.com',
    fillAccountEmail: (email: string): string => `使用 ${email}`,
    includeDiagnostics: '附上诊断信息',
    includeDiagnosticsDetail:
      '可选。包括应用版本、设备、大致位置和问题数量。除非你打开，否则不会附上。',
    showIncluded: '查看包含的内容',
    hideIncluded: '隐藏包含的内容',
    privacy: '连同你的账户发送给 Mohd Inc.，以便我们跟进。最长保存 2 年。{privacy}',
    privacyLink: '阅读隐私政策',
    send: '发送',
    sending: '正在发送…',
    queuedTitle: '已保存，稍后发送',
    queued: '你目前处于离线状态。反馈已保存在这台设备上，恢复联网后会发送。',
    sentTitle: '谢谢',
    sent: '你的反馈已发送。',
    done: '完成',
    sendAnother: '再发送一条',
    errors: {
      'rate-limited': '你刚刚发送过反馈。请等一分钟再试。',
      network: '无法连接。你的消息还在这里。请检查网络后重试。',
      'signed-out': '已保存在这台设备上。登录后会发送。',
      invalid: '请检查你的消息和联系邮箱，然后重新发送。',
      unknown: '出了点问题。你的消息还在这里。请重试。',
    },
  },
  about: {
    title: '关于',
    version: '版本',
    content: '内容',
    contentUnreviewed: (count: number): string =>
      `${count} 项内容，均为草稿，等待一位具名学者审阅。`,
    contentReviewedBy: (name: string, count: number): string =>
      `${count} 项内容，已由 ${name} 审阅。`,
    donate: '捐助',
    donateBody:
      '完全自愿，也不解锁任何功能。应用的每一部分都是免费的，并且永远免费。将在浏览器中打开。',
    privacyPolicy: '隐私政策',
    termsOfUse: '使用条款',
    privacyTitle: '你的数据留在这台设备上',
    privacyBody:
      '没有统计分析，也没有广告。你的位置在这台设备上用于推算礼拜时间，你的功课记录和设置也保存在这里。除非你自己导出或分享，或登录以同步，否则什么都不会离开这台设备。使用 Apple 或 Google 登录是可选的：登录后，你的姓名和邮箱、功课记录、进度、设置以及大致位置（精确到约 1 公里）会存储在美国的 Google Firebase 上，以便在你的设备之间同步。你可以随时在“账户”中删除账户。捐赠会打开你的浏览器，那个页面不属于 Ihsaanly。',
    licences: '构建所用',
    licencesBody:
      'Expo 与 React Native，用于礼拜时间的 adhan 库，乌姆古拉历法表，来自 city-timezones 的城市数据（基于 GeoNames），以及用于地图的 Natural Earth。每一项都依照各自的开源许可使用，许可列表见源代码仓库。',
    geonames: '城市数据 © GeoNames (CC BY 4.0)',
  },
  memorise: {
    title: '背记',
    start: '练习',
    hide: '再遮住一个',
    known: '我已经会了',
    knownDetail: '它仍留在资料库中，但不再出现在提醒里。',
    notKnown: '还在学习',
    noAudio: '这一项还没有诵读音频。',
    play: '播放',
    stop: '停止',
    loop: '重复',
  },
  language: {
    title: '语言',
    restart:
      '阿拉伯语从右向左书写。切换到阿拉伯语或从阿拉伯语切换回来时，应用会重新启动，或请你重新打开它。',
    incomplete: '英语是原文。其他所有语言都是草稿，仍在等待合格的母语者审阅。',
    reopenTitle: '重新打开 Ihsaanly',
    reopenBody: '这种语言从右向左书写。请关闭 Ihsaanly 后再重新打开，以完成切换。',
    names: {
      en: 'English',
      ar: 'العربية',
      fr: 'Français',
      it: 'Italiano',
      ja: '日本語',
      hi: 'हिन्दी',
      ur: 'اردو',
      so: 'Soomaali',
      zh: '中文（普通话）',
      yue: '廣東話',
    },
  },
  appearance: {
    title: '外观',
    system: '跟随系统',
    light: '浅色',
    dark: '深色',
    note: '颜色仍然来自系统，因此无论哪种设置，系统的对比度选项都会生效。',
  },
  moonSighting: {
    title: '观月',
    explanation:
      '本应用中的日期是推算出来的。各地社群对于依照推算还是依照当地观月看法不一，两者常常相差一天。请跟随你自己的社群，并在设置中调整日期，使应用与他们一致。',
    disclaimer: '列出这些机构只是为了方便你找到自己所跟随的。本应用不为其中任何一家背书。',
  },
  tracking: {
    title: '记录',
    active: '进行中',
    travelling: '旅行中',
    travellingDetail: '提供短礼，定时圣行拜暂且放下，斋戒改为可选而非预期。',
    paused: '暂停礼拜记录',
    pausedDetail: '不记录礼拜，也不会累积任何待补的礼拜。在你重新开启之前一直保持关闭。',
    jumuah: '周五的主麻',
    jumuahChoice: {
      auto: '自动',
      attend: '我参加主麻',
      dhuhr: '我礼晌礼',
    },
    jumuahAutoDetail: '周五礼主麻，除非你在旅行中或选择了“姐妹”。',
  },
  hijri: {
    title: '伊斯兰历日期',
    offset: '调整日期',
    approximate: '推算所得——请向你的社群所跟随的权威机构确认。',
    explanation:
      '推算的历法与当地观月常常相差一两天。在这里调整日期，使应用与你的社群一致。斋戒日的日期始终显示为预计，而不是确定。',
    offsetLabel: (days: number): string =>
      days === 0 ? '不调整' : `${days > 0 ? '+' : ''}${days} 天`,
    format: (day: number, month: string, year: number): string => `${year}年${month}${day}日`,
  },
  hijriMonth: {
    1: '穆哈兰姆月',
    2: '色法尔月',
    3: '赖比尔·敖外鲁月',
    4: '赖比尔·阿赫尔月',
    5: '主马达·敖外鲁月',
    6: '主马达·阿赫尔月',
    7: '赖哲卜月',
    8: '舍尔巴尼月',
    9: '莱麦丹月',
    10: '闪瓦鲁月',
    11: '都尔喀尔德月',
    12: '都尔黑哲月',
  },
  calculation: {
    title: '礼拜时间计算',
    method: '计算方法',
    asr: '晡礼',
    highLatitude: '高纬度',
    selected: '已选择',
    explanation:
      '礼拜时间在这台设备上计算，从不以钟点显示——它们只用来判断你正处在一天中的哪个时段。',
    highLatitudeExplanation:
      '在大约北纬 48° 以北，一年中有一段时间不会出现宵礼的时刻。这一项决定届时改用什么。',
  },
  asr: {
    shafi: '标准',
    hanafi: '哈乃斐',
  },
  highLatitude: {
    middleofthenight: '夜半',
    seventhofthenight: '夜晚的七分之一',
    twilightangle: '暮光角度',
  },
  method: {
    MuslimWorldLeague: '世界穆斯林联盟',
    Egyptian: '埃及测绘总局',
    Karachi: '卡拉奇伊斯兰科学大学',
    UmmAlQura: '乌姆古拉，麦加',
    Dubai: '迪拜',
    MoonsightingCommittee: '观月委员会',
    NorthAmerica: '北美伊斯兰协会（ISNA）',
    Kuwait: '科威特',
    Qatar: '卡塔尔',
    Singapore: '新加坡',
    Tehran: '德黑兰',
    Turkey: '土耳其',
  },
  library: {
    title: '资料库',
    empty: '记念、杜阿和圣行功课将列在这里。',
    search: '按名称或情境搜索',
    noResults: '没有匹配的内容。',
    filterAll: '全部',
    filterOnToday: '在今天中',
    filterKnown: '已会',
    onToday: '在今天中',
    known: '已会',
    emptyOnToday: '“今天”中还没有任何功课。打开任意一项并将其开启。',
    emptyKnown: '还没有标记为已会的功课。练习一项，会了之后再标记。',
    terms: '词汇表',
    termsDetail: '圣行、定时圣行拜、记念、补礼等，各用一句话说明。',
  },
  category: {
    adhkar: '记念',
    dhikr: '礼拜之后',
    fasting: '斋戒',
    food: '饮食',
    home: '家中',
    masjid: '清真寺',
    prayer: '礼拜',
    sleep: '睡眠与醒来',
    travel: '旅行',
  },
  item: {
    done: '完成',
    doneToday: '今天已完成',
    undo: '撤销',
    counterReset: '重新开始',
    yourDay: '你的一天',
    onToday: '在今天中',
    onTodayDetail: '到了它的时机就会出现',
    remind: '提醒我',
    remindWindow: '在它的时段开始时',
    remindLookAhead: '前一天晚上',
    share: '分享',
    shareText: '以文字分享',
    shareImage: '以图片分享',
    sharedFrom: '分享自 Ihsaanly',
    transliteration: '音译',
    translation: '译义',
    why: '为什么',
    how: '怎么做',
    unreviewed: '等待审阅',
    evidence: '依据',
    note: '学者意见不一',
    repeat: (times: number): string => `重复 ${times} 遍`,
    parts: '要念的内容',
    partRepeat: (times: number): string => `${times} 遍`,
    gradedBy: (grader: string): string => `${grader} 评定`,
    quranReference: (surah: number, ayah: number): string => `《古兰经》${surah}:${ayah}`,
  },
  glossary: {
    title: '词语释义',
  },
  ruling: {
    fard: '主命',
    wajib: '必然',
    'sunnah-muakkadah': '重要圣行',
    sunnah: '圣行',
    mustahabb: '可嘉',
    mubah: '准许',
  },
  grading: {
    sahih: '正确（萨希哈）',
    hasan: '良好（哈桑）',
    "da'if": '羸弱（达伊夫）',
    disputed: '有争议',
  },
  more: {
    title: '更多',
    search: '搜索设置',
    prayer: '礼拜',
    app: '应用',
    practice: '你的功课',
    empty: '记录、设置和帮助将放在这里。',
  },
  onboarding: {
    welcomeTitle: '看时机，不看钟点。',
    welcomeBody: 'Ihsaanly 会告诉你傍晚的记念何时开始。从不显示钟点，也从不打分。',
    howTitle: '你标记礼拜，圣行随之出现。',
    howBody:
      '礼完晌礼后点一下它，随后的记念就已经在等着你。除非你选择登录以同步，否则一切都留在这台设备上。',
    language: '语言',
    appearance: '外观',
    howSample: 'سُبْحَانَ اللهِ وَبِحَمْدِهِ',
    locationStep: '你在哪里？',
    locationWhy: '在这台设备上用来推算一天中的各个时段。除非你登录以同步，否则只留在这台设备上。',
    genderStep: '暂停记录',
    genderWhy:
      '有些日子里应当停止礼拜记录，并且不累积任何待补的礼拜。这一项告诉应用是否提供这个选项。',
    brother: '兄弟',
    brotherDetail: '不提供暂停',
    sister: '姐妹',
    sisterDetail: '提供暂停',
    skip: '不想说明',
    skipDetail: '仍然会提供暂停。',
    genderPrivacy: '保存在这台设备上，只有登录后才会同步。不作其他任何用途。',
    remindersStep: '提醒',
    remindersWhy: '每天两三条，夜间从不打扰。以后可以随时在“更多”中更改。',
    windowsDetail: '在每个时段开始时',
    lookAheadDetail: '前一天晚上',
    startStep: '一个起点',
    startWhy: '先选择一个开始的规模。之后随时可以在资料库中添加或移除任何内容。',
    starting: '刚刚开始',
    startingDetail: (count: number): string =>
      `${count} 项从第一天起就能坚持的功课：两个时段、一段记念、两段杜阿。适合对这一切都还陌生的人。`,
    essentials: '基本功课',
    essentialsDetail: (count: number): string =>
      `${count} 项功课，合理的一天，而不是面面俱到的一天。适合已经在礼拜、想加上相关圣行的人。`,
    everything: '全部',
    everythingDetail: (count: number): string =>
      `全部 ${count} 项功课。适合熟悉这些内容、想要完整日程的人。`,
    skipIntro: '跳过',
    skipLocation: '暂时跳过',
    reminderPolicy: (perDay: number, from: number, to: number): string =>
      `每天最多 ${perDay} 条，${from}:00 至 ${to}:00 之间不发送。`,
    reminderCap: (perDay: number): string => `每天最多 ${perDay} 条。`,
    included: '已包含',
    andMore: (count: number): string => `以及另外 ${count} 项`,
    back: '返回',
    continue: '继续',
    allowReminders: '允许提醒',
    notNow: '暂不',
    done: '开始',
    restore: '已经在用 Ihsaanly？登录以恢复你的数据',
  },
  location: {
    title: '位置',
    notSet: '未设置',
    currentLocation: '当前位置',
    useDevice: '使用我的位置',
    useDeviceDetail: '除非你登录以同步，否则只留在这台设备上。',
    locating: '正在定位……',
    orSearch: '或搜索城市',
    follows: '礼拜时段将依据这个地点。',
    search: '搜索城市',
    noResults: '没有匹配的城市。',
    unavailable: '此设备的定位服务已关闭。请开启定位，或改为搜索你所在的城市。',
    declined: '位置访问已被拒绝。请改为搜索你所在的城市——所有功能照常可用。',
    explanation: '在这台设备上用来推算礼拜时段。除非你登录以同步，否则只留在这台设备上。',
    attribution: '城市数据来自 city-timezones（MIT）。',
  },
  textField: {
    clear: '清除',
  },
  error: {
    title: '出了点问题',
    retry: '重试',
  },
  notFound: {
    title: '未找到',
    body: '该页面不存在。',
  },
  widgets: {
    quickDuas: '快捷杜阿',
    duaOfTheDay: '每日杜阿',
    nothingNow: '此刻没有要做的',
    openApp: '打开 Ihsaanly 以更新',
  },
  web: {
    remindersUnavailable: '提醒需要手机 App。网页关闭后浏览器无法提醒你。',
    homeDetectionUnavailable: '检测到家需要手机 App。',
    storageAtRisk: '此浏览器未能可靠地保存你的数据。请在“数据”中导出备份。',
    openInApp: '在 App 中打开',
    getApp: '获取 App',
    updateReady: '有新版本可用。',
    reload: '重新加载',
    remindersThrough: (date: string): string =>
      `提醒已设置到${date}。请在此之前打开 Ihsaanly，以便继续提醒。`,
    dismiss: '关闭',
  },
  panel: {
    close: '关闭',
  },
}
