// A small, hand-picked set of cities spanning a wide range of time zones, used
// as the demo's location picker. Kept separate from `@/location/cities`
// (city-timezones, a ~1.9 MB table) so the demo bundle stays small — the demo
// only needs a plausible default and a short list to choose from, not a full
// world gazetteer.

import type { Place } from '@/location/place'

export const MAKKAH: Place = {
  label: 'Makkah, Saudi Arabia',
  latitude: 21.3891,
  longitude: 39.8579,
  timeZone: 'Asia/Riyadh',
  source: 'city',
}

export const CITIES: Place[] = [
  MAKKAH,
  {
    label: 'Madinah, Saudi Arabia',
    latitude: 24.5247,
    longitude: 39.5692,
    timeZone: 'Asia/Riyadh',
    source: 'city',
  },
  {
    label: 'Riyadh, Saudi Arabia',
    latitude: 24.7136,
    longitude: 46.6753,
    timeZone: 'Asia/Riyadh',
    source: 'city',
  },
  {
    label: 'Jeddah, Saudi Arabia',
    latitude: 21.4858,
    longitude: 39.1925,
    timeZone: 'Asia/Riyadh',
    source: 'city',
  },
  {
    label: 'Dubai, United Arab Emirates',
    latitude: 25.2048,
    longitude: 55.2708,
    timeZone: 'Asia/Dubai',
    source: 'city',
  },
  {
    label: 'Abu Dhabi, United Arab Emirates',
    latitude: 24.4539,
    longitude: 54.3773,
    timeZone: 'Asia/Dubai',
    source: 'city',
  },
  {
    label: 'Doha, Qatar',
    latitude: 25.2854,
    longitude: 51.531,
    timeZone: 'Asia/Qatar',
    source: 'city',
  },
  {
    label: 'Kuwait City, Kuwait',
    latitude: 29.3759,
    longitude: 47.9774,
    timeZone: 'Asia/Kuwait',
    source: 'city',
  },
  {
    label: 'Manama, Bahrain',
    latitude: 26.2285,
    longitude: 50.586,
    timeZone: 'Asia/Bahrain',
    source: 'city',
  },
  {
    label: 'Muscat, Oman',
    latitude: 23.5859,
    longitude: 58.4059,
    timeZone: 'Asia/Muscat',
    source: 'city',
  },
  {
    label: 'Amman, Jordan',
    latitude: 31.9454,
    longitude: 35.9284,
    timeZone: 'Asia/Amman',
    source: 'city',
  },
  {
    label: 'Beirut, Lebanon',
    latitude: 33.8938,
    longitude: 35.5018,
    timeZone: 'Asia/Beirut',
    source: 'city',
  },
  {
    label: 'Baghdad, Iraq',
    latitude: 33.3152,
    longitude: 44.3661,
    timeZone: 'Asia/Baghdad',
    source: 'city',
  },
  {
    label: 'Tehran, Iran',
    latitude: 35.6892,
    longitude: 51.389,
    timeZone: 'Asia/Tehran',
    source: 'city',
  },
  {
    label: 'Istanbul, Turkey',
    latitude: 41.0082,
    longitude: 28.9784,
    timeZone: 'Europe/Istanbul',
    source: 'city',
  },
  {
    label: 'Ankara, Turkey',
    latitude: 39.9334,
    longitude: 32.8597,
    timeZone: 'Europe/Istanbul',
    source: 'city',
  },
  {
    label: 'Cairo, Egypt',
    latitude: 30.0444,
    longitude: 31.2357,
    timeZone: 'Africa/Cairo',
    source: 'city',
  },
  {
    label: 'Khartoum, Sudan',
    latitude: 15.5007,
    longitude: 32.5599,
    timeZone: 'Africa/Khartoum',
    source: 'city',
  },
  {
    label: 'Casablanca, Morocco',
    latitude: 33.5731,
    longitude: -7.5898,
    timeZone: 'Africa/Casablanca',
    source: 'city',
  },
  {
    label: 'Algiers, Algeria',
    latitude: 36.7538,
    longitude: 3.0588,
    timeZone: 'Africa/Algiers',
    source: 'city',
  },
  {
    label: 'Tunis, Tunisia',
    latitude: 36.8065,
    longitude: 10.1815,
    timeZone: 'Africa/Tunis',
    source: 'city',
  },
  {
    label: 'Tripoli, Libya',
    latitude: 32.8872,
    longitude: 13.1913,
    timeZone: 'Africa/Tripoli',
    source: 'city',
  },
  {
    label: 'Lagos, Nigeria',
    latitude: 6.5244,
    longitude: 3.3792,
    timeZone: 'Africa/Lagos',
    source: 'city',
  },
  {
    label: 'Nairobi, Kenya',
    latitude: -1.2921,
    longitude: 36.8219,
    timeZone: 'Africa/Nairobi',
    source: 'city',
  },
  {
    label: 'Mogadishu, Somalia',
    latitude: 2.0469,
    longitude: 45.3182,
    timeZone: 'Africa/Mogadishu',
    source: 'city',
  },
  {
    label: 'Johannesburg, South Africa',
    latitude: -26.2041,
    longitude: 28.0473,
    timeZone: 'Africa/Johannesburg',
    source: 'city',
  },
  {
    label: 'Karachi, Pakistan',
    latitude: 24.8607,
    longitude: 67.0011,
    timeZone: 'Asia/Karachi',
    source: 'city',
  },
  {
    label: 'Lahore, Pakistan',
    latitude: 31.5497,
    longitude: 74.3436,
    timeZone: 'Asia/Karachi',
    source: 'city',
  },
  {
    label: 'Islamabad, Pakistan',
    latitude: 33.6844,
    longitude: 73.0479,
    timeZone: 'Asia/Karachi',
    source: 'city',
  },
  {
    label: 'Delhi, India',
    latitude: 28.6139,
    longitude: 77.209,
    timeZone: 'Asia/Kolkata',
    source: 'city',
  },
  {
    label: 'Mumbai, India',
    latitude: 19.076,
    longitude: 72.8777,
    timeZone: 'Asia/Kolkata',
    source: 'city',
  },
  {
    label: 'Dhaka, Bangladesh',
    latitude: 23.8103,
    longitude: 90.4125,
    timeZone: 'Asia/Dhaka',
    source: 'city',
  },
  {
    label: 'Kabul, Afghanistan',
    latitude: 34.5553,
    longitude: 69.2075,
    timeZone: 'Asia/Kabul',
    source: 'city',
  },
  {
    label: 'Jakarta, Indonesia',
    latitude: -6.2088,
    longitude: 106.8456,
    timeZone: 'Asia/Jakarta',
    source: 'city',
  },
  {
    label: 'Kuala Lumpur, Malaysia',
    latitude: 3.139,
    longitude: 101.6869,
    timeZone: 'Asia/Kuala_Lumpur',
    source: 'city',
  },
  {
    label: 'Singapore',
    latitude: 1.3521,
    longitude: 103.8198,
    timeZone: 'Asia/Singapore',
    source: 'city',
  },
  {
    label: 'Manila, Philippines',
    latitude: 14.5995,
    longitude: 120.9842,
    timeZone: 'Asia/Manila',
    source: 'city',
  },
  {
    label: 'Hong Kong',
    latitude: 22.3193,
    longitude: 114.1694,
    timeZone: 'Asia/Hong_Kong',
    source: 'city',
  },
  {
    label: 'Beijing, China',
    latitude: 39.9042,
    longitude: 116.4074,
    timeZone: 'Asia/Shanghai',
    source: 'city',
  },
  {
    label: 'Tokyo, Japan',
    latitude: 35.6762,
    longitude: 139.6503,
    timeZone: 'Asia/Tokyo',
    source: 'city',
  },
  {
    label: 'Seoul, South Korea',
    latitude: 37.5665,
    longitude: 126.978,
    timeZone: 'Asia/Seoul',
    source: 'city',
  },
  {
    label: 'London, United Kingdom',
    latitude: 51.5074,
    longitude: -0.1278,
    timeZone: 'Europe/London',
    source: 'city',
  },
  {
    label: 'Paris, France',
    latitude: 48.8566,
    longitude: 2.3522,
    timeZone: 'Europe/Paris',
    source: 'city',
  },
  {
    label: 'Berlin, Germany',
    latitude: 52.52,
    longitude: 13.405,
    timeZone: 'Europe/Berlin',
    source: 'city',
  },
  {
    label: 'Madrid, Spain',
    latitude: 40.4168,
    longitude: -3.7038,
    timeZone: 'Europe/Madrid',
    source: 'city',
  },
  {
    label: 'Rome, Italy',
    latitude: 41.9028,
    longitude: 12.4964,
    timeZone: 'Europe/Rome',
    source: 'city',
  },
  {
    label: 'Amsterdam, Netherlands',
    latitude: 52.3676,
    longitude: 4.9041,
    timeZone: 'Europe/Amsterdam',
    source: 'city',
  },
  {
    label: 'Moscow, Russia',
    latitude: 55.7558,
    longitude: 37.6173,
    timeZone: 'Europe/Moscow',
    source: 'city',
  },
  {
    label: 'Toronto, Canada',
    latitude: 43.6532,
    longitude: -79.3832,
    timeZone: 'America/Toronto',
    source: 'city',
  },
  {
    label: 'New York, United States',
    latitude: 40.7128,
    longitude: -74.006,
    timeZone: 'America/New_York',
    source: 'city',
  },
  {
    label: 'Chicago, United States',
    latitude: 41.8781,
    longitude: -87.6298,
    timeZone: 'America/Chicago',
    source: 'city',
  },
  {
    label: 'Houston, United States',
    latitude: 29.7604,
    longitude: -95.3698,
    timeZone: 'America/Chicago',
    source: 'city',
  },
  {
    label: 'Los Angeles, United States',
    latitude: 34.0522,
    longitude: -118.2437,
    timeZone: 'America/Los_Angeles',
    source: 'city',
  },
  {
    label: 'Sydney, Australia',
    latitude: -33.8688,
    longitude: 151.2093,
    timeZone: 'Australia/Sydney',
    source: 'city',
  },
  {
    label: 'Melbourne, Australia',
    latitude: -37.8136,
    longitude: 144.9631,
    timeZone: 'Australia/Melbourne',
    source: 'city',
  },
  {
    label: 'Denver, United States',
    latitude: 39.7392,
    longitude: -104.9903,
    timeZone: 'America/Denver',
    source: 'city',
  },
  {
    label: 'Phoenix, United States',
    latitude: 33.4484,
    longitude: -112.074,
    timeZone: 'America/Phoenix',
    source: 'city',
  },
  {
    label: 'Anchorage, United States',
    latitude: 61.2181,
    longitude: -149.9003,
    timeZone: 'America/Anchorage',
    source: 'city',
  },
  {
    label: 'Honolulu, United States',
    latitude: 21.3069,
    longitude: -157.8583,
    timeZone: 'Pacific/Honolulu',
    source: 'city',
  },
  {
    label: 'Mexico City, Mexico',
    latitude: 19.4326,
    longitude: -99.1332,
    timeZone: 'America/Mexico_City',
    source: 'city',
  },
  {
    label: 'Bogotá, Colombia',
    latitude: 4.711,
    longitude: -74.0721,
    timeZone: 'America/Bogota',
    source: 'city',
  },
  {
    label: 'São Paulo, Brazil',
    latitude: -23.5505,
    longitude: -46.6333,
    timeZone: 'America/Sao_Paulo',
    source: 'city',
  },
  {
    label: 'Buenos Aires, Argentina',
    latitude: -34.6037,
    longitude: -58.3816,
    timeZone: 'America/Argentina/Buenos_Aires',
    source: 'city',
  },
  {
    label: 'Halifax, Canada',
    latitude: 44.6488,
    longitude: -63.5752,
    timeZone: 'America/Halifax',
    source: 'city',
  },
  {
    label: 'St. John’s, Canada',
    latitude: 47.5615,
    longitude: -52.7126,
    timeZone: 'America/St_Johns',
    source: 'city',
  },
  {
    label: 'Ponta Delgada, Portugal',
    latitude: 37.7412,
    longitude: -25.6756,
    timeZone: 'Atlantic/Azores',
    source: 'city',
  },
  {
    label: 'Dakar, Senegal',
    latitude: 14.7167,
    longitude: -17.4677,
    timeZone: 'Africa/Dakar',
    source: 'city',
  },
  {
    label: 'Tashkent, Uzbekistan',
    latitude: 41.2995,
    longitude: 69.2401,
    timeZone: 'Asia/Tashkent',
    source: 'city',
  },
  {
    label: 'Kathmandu, Nepal',
    latitude: 27.7172,
    longitude: 85.324,
    timeZone: 'Asia/Kathmandu',
    source: 'city',
  },
  {
    label: 'Yangon, Myanmar',
    latitude: 16.8409,
    longitude: 96.1735,
    timeZone: 'Asia/Yangon',
    source: 'city',
  },
  {
    label: 'Bangkok, Thailand',
    latitude: 13.7563,
    longitude: 100.5018,
    timeZone: 'Asia/Bangkok',
    source: 'city',
  },
  {
    label: 'Perth, Australia',
    latitude: -31.9505,
    longitude: 115.8605,
    timeZone: 'Australia/Perth',
    source: 'city',
  },
  {
    label: 'Darwin, Australia',
    latitude: -12.4634,
    longitude: 130.8456,
    timeZone: 'Australia/Darwin',
    source: 'city',
  },
  {
    label: 'Adelaide, Australia',
    latitude: -34.9285,
    longitude: 138.6007,
    timeZone: 'Australia/Adelaide',
    source: 'city',
  },
  {
    label: 'Brisbane, Australia',
    latitude: -27.4698,
    longitude: 153.0251,
    timeZone: 'Australia/Brisbane',
    source: 'city',
  },
  {
    label: 'Auckland, New Zealand',
    latitude: -36.8485,
    longitude: 174.7633,
    timeZone: 'Pacific/Auckland',
    source: 'city',
  },
]

/** Minutes ahead of UTC in `timeZone` at `at`, read from Intl rather than computed. */
function offsetMinutes(timeZone: string, at: Date): number {
  const parts = new Intl.DateTimeFormat('en-US', {
    timeZone,
    hourCycle: 'h23',
    year: 'numeric',
    month: 'numeric',
    day: 'numeric',
    hour: 'numeric',
    minute: 'numeric',
  }).formatToParts(at)
  const part = (type: string): number => Number(parts.find((p) => p.type === type)?.value ?? 0)
  const local = Date.UTC(part('year'), part('month') - 1, part('day'), part('hour'), part('minute'))
  return Math.round((local - at.getTime()) / 60_000)
}

/**
 * A built-in city in the visitor's time zone; failing that, one whose clock
 * reads the same right now, so the demo still follows the visitor's own time;
 * failing that, Makkah.
 */
export function defaultCityFor(timeZone: string, at: Date = new Date()): Place {
  const exact = CITIES.find((city) => city.timeZone === timeZone)
  if (exact) return exact
  const offset = offsetMinutes(timeZone, at)
  return CITIES.find((city) => offsetMinutes(city.timeZone, at) === offset) ?? MAKKAH
}
