// The .htaccess (Apache / GoDaddy shared hosting) and _headers (Netlify /
// Cloudflare Pages) writers every static web host uses: security and cache
// headers, and either marketing's per-page CSP map with a 404 error document,
// or a single policy with a client-side-routing SPA fallback.
import { COMMON_HEADERS, type HeaderMap, pathRegex, sentAlways } from './csp.ts'

function quoted(value: string): string {
  return `"${value.replaceAll('"', '\\"')}"`
}

/** A page is also reachable as its index.html, so both spellings get its policy. */
function spellings(path: string): string[] {
  return path.endsWith('/') ? [path, `${path}index.html`] : [path]
}

export interface AddType {
  type: string
  extension: string
}

export interface HtaccessOptions {
  headerMap: HeaderMap
  /** `ErrorDocument 404 <path>` — omit for an SPA that falls back to `spaFallback` instead. */
  notFoundPath?: string
  /**
   * SPA fallback: any request for a path that isn't a real file or directory
   * rewrites to this one (e.g. `/index.html`), so client-side routes survive
   * a reload.
   */
  spaFallback?: string
  /** Extra `AddType` lines, beyond the defaults (webmanifest, woff2). */
  extraAddTypes?: AddType[]
}

// <If> sections merge after <FilesMatch>, so these replace the cache tiers
// above for the paths they match.
function pathRules(paths: HeaderMap['paths'] = {}): string {
  return Object.entries(paths)
    .map(([pattern, set]) => {
      const lines = Object.entries(set)
        .map(
          ([name, value]) =>
            `    Header ${sentAlways(name) ? 'always set' : 'set'} ${name} ${quoted(value)}`,
        )
        .join('\n')
      return `\n  <If "%{REQUEST_URI} =~ m#${pathRegex(pattern)}#">\n${lines}\n  </If>`
    })
    .join('')
}

export function buildHtaccess({
  headerMap: { pages, fallback, headers, paths },
  notFoundPath,
  spaFallback,
  extraAddTypes = [],
}: HtaccessOptions): string {
  const common = Object.entries({ ...COMMON_HEADERS, ...headers })
    .map(([name, value]) => {
      const onlyHttps = name === 'Strict-Transport-Security' ? ' env=HTTPS' : ''
      return `  Header always set ${name} ${quoted(value)}${onlyHttps}`
    })
    .join('\n')
  // <If> sections are merged after the main context, so a page's policy
  // replaces the fallback, which covers 404s and anything unlisted.
  const perPage = Object.entries(pages)
    .filter(([path]) => path !== '/404.html')
    .map(([path, policy]) => {
      const list = spellings(path)
        .map((each) => `'${each}'`)
        .join(', ')
      return `  <If "%{REQUEST_URI} -in {${list}}">\n    Header always set Content-Security-Policy ${quoted(policy)}\n  </If>`
    })
    .join('\n')
  const addTypes = [
    'AddType application/manifest+json .webmanifest',
    'AddType font/woff2 .woff2',
    ...extraAddTypes.map(({ type, extension }) => `AddType ${type} ${extension}`),
  ].join('\n')
  const errorDocument = notFoundPath ? `ErrorDocument 404 ${notFoundPath}\n` : ''
  const spaRewrite = spaFallback
    ? `\n  RewriteCond %{REQUEST_FILENAME} !-f\n  RewriteCond %{REQUEST_FILENAME} !-d\n  RewriteRule ^ ${spaFallback} [L]`
    : ''
  return `# Generated by scripts/postbuild.ts: edit there, not here. See HOSTING.md.
${errorDocument}${addTypes}
AddDefaultCharset utf-8

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTPS} off
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]${spaRewrite}
</IfModule>

<IfModule mod_headers.c>
${common}
  Header always set Content-Security-Policy ${quoted(fallback)}
${perPage}

  # Vite names bundled assets with a content hash, so they never change.
  <FilesMatch "-[A-Za-z0-9_-]{8}\\.(css|js|woff2|ttf)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>
  <FilesMatch "\\.(png|svg|txt|webmanifest)$">
    Header set Cache-Control "public, max-age=2592000"
  </FilesMatch>
  # Pages, the sitemap and the server-function data are revalidated, so a new
  # build is live at once.
  <FilesMatch "\\.(html|xml|json)$">
    Header set Cache-Control "no-cache"
  </FilesMatch>${pathRules(paths)}
</IfModule>

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css text/plain text/xml text/javascript application/javascript application/json application/xml application/manifest+json image/svg+xml font/ttf
</IfModule>
`
}

export function buildHeadersFile({ pages, headers, paths = {} }: HeaderMap): string {
  const common = Object.entries({ ...COMMON_HEADERS, ...headers })
    .map(([name, value]) => `  ${name}: ${value}`)
    .join('\n')
  // Netlify joins a header set by several matching rules, and two CSPs would
  // intersect, so the policy is only ever set per page.
  const perPage = Object.entries(pages)
    .flatMap(([path, policy]) =>
      spellings(path).map((each) => `${each}\n  Content-Security-Policy: ${policy}`),
    )
    .join('\n\n')
  const perPath = Object.entries(paths)
    .map(
      ([pattern, set]) =>
        `${pattern}\n${Object.entries(set)
          .map(([name, value]) => `  ${name}: ${value}`)
          .join('\n')}\n\n`,
    )
    .join('')
  return `# Generated by scripts/postbuild.ts for hosts that read _headers (Netlify, Cloudflare Pages).
/*
${common}

/assets/*
  Cache-Control: public, max-age=2592000

${perPath}${perPage}
`
}
