import type { ReactElement } from 'react'
import { Image } from 'expo-image'
import { Text, View } from 'react-native'

const OUTLINE = require('../../assets/images/star-outline.png')
const SOLID = require('../../assets/images/star-solid.png')

interface StarProps {
  size: number
  color: string
  hollow?: boolean
  opacity?: number
}

/**
 * The eight-point star, drawn from the same stamps as the app icon rather than
 * from two overlapping squares. The union matters: composed squares show their
 * crossing lines when outlined, and a darker patch where they meet when shaded.
 * The stamps are white, so `tintColor` paints them from the palette.
 *
 * Generated by `scripts/build-brand-assets.ts`, which is also what draws the
 * icon, so the mark on screen and the mark on the home screen cannot drift.
 */
function Star({ size, color, hollow = false, opacity = 1 }: StarProps): ReactElement {
  return (
    <Image
      source={hollow ? OUTLINE : SOLID}
      tintColor={color}
      contentFit="contain"
      style={{ width: size, height: size, opacity }}
    />
  )
}

interface OnboardingArtProps {
  variant: 'welcome' | 'how'
  color: string
  onColor: string
}

const GRID = [0.3, 0.55, 0.3, 0.55, 1, 0.55, 0.3, 0.55, 0.3]

export function OnboardingArt({ variant, color, onColor }: OnboardingArtProps): ReactElement {
  if (variant === 'how') {
    return (
      <View className="items-center justify-center" style={{ width: 208, height: 208 }}>
        <View style={{ position: 'absolute' }}>
          <Star size={208} color={color} hollow />
        </View>
        <View
          className="items-center justify-center rounded-full"
          style={{ width: 52, height: 52, backgroundColor: color }}>
          <Text style={{ color: onColor, fontSize: 26 }}>✓</Text>
        </View>
      </View>
    )
  }

  return (
    <View className="flex-row flex-wrap justify-center" style={{ width: 228 }}>
      {GRID.map((opacity, index) => (
        <View key={index} style={{ padding: 6 }}>
          <Star size={64} color={color} hollow={index % 2 === 0 && index !== 4} opacity={opacity} />
        </View>
      ))}
    </View>
  )
}
