// Writes THIRD_PARTY_LICENSES.md: every production dependency (transitively) of
// the shipped apps, with its licence text, and a list of licences that need a
// human look (copyleft, source-available, or unknown).
//
//   bun scripts/licenses.ts
//
// Walks node_modules the way Node resolves it, so it needs `bun install` first
// and adds no dependencies of its own. Workspace packages are skipped.
import { existsSync, readdirSync, readFileSync, realpathSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

const ROOT = join(import.meta.dir, '..')
const APPS = ['companion', 'extension', 'mobile', 'marketing']
const FLAGGED = /(^|[^A-Z])(A?GPL|LGPL|SSPL|EUPL|CC-BY-NC|BUSL)/i

interface Manifest {
  name: string
  version: string
  license?: string | { type?: string }
  licenses?: { type?: string }[]
  dependencies?: Record<string, string>
  optionalDependencies?: Record<string, string>
  repository?: string | { url?: string }
}

interface Entry {
  name: string
  version: string
  license: string
  text: string
  apps: Set<string>
}

const readManifest = (dir: string): Manifest | null => {
  try {
    return JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')) as Manifest
  } catch {
    return null
  }
}

/** Node's lookup: the nearest node_modules/<name> walking up from `from`. */
function resolve(name: string, from: string): string | null {
  for (let dir = from; ; dir = dirname(dir)) {
    const candidate = join(dir, 'node_modules', name)
    if (existsSync(join(candidate, 'package.json'))) return realpathSync(candidate)
    if (dirname(dir) === dir) return null
  }
}

function licenceOf(manifest: Manifest): string {
  const { license, licenses } = manifest
  if (typeof license === 'string') return license
  if (license?.type) return license.type
  if (licenses?.length) return licenses.map((entry) => entry.type ?? '?').join(' OR ')
  return 'UNKNOWN'
}

function licenceText(dir: string): string {
  const file = readdirSync(dir).find((name) => /^(licen[sc]e|copying|notice)(\.|$)/i.test(name))
  return file ? readFileSync(join(dir, file), 'utf8').trim() : ''
}

const isWorkspace = (dir: string): boolean => !dir.includes('/node_modules/')

const entries = new Map<string, Entry>()

function visit(dir: string, app: string, seen: Set<string>): void {
  const manifest = readManifest(dir)
  if (!manifest || seen.has(dir)) return
  seen.add(dir)
  if (!isWorkspace(dir)) {
    const key = `${manifest.name}@${manifest.version}`
    const entry = entries.get(key) ?? {
      name: manifest.name,
      version: manifest.version,
      license: licenceOf(manifest),
      text: licenceText(dir),
      apps: new Set<string>(),
    }
    entry.apps.add(app)
    entries.set(key, entry)
  }
  const dependencies = { ...manifest.dependencies, ...manifest.optionalDependencies }
  for (const name of Object.keys(dependencies)) {
    const found = resolve(name, dir)
    if (found) visit(found, app, seen)
  }
}

for (const app of APPS) {
  const dir = join(ROOT, 'apps', app)
  const manifest = readManifest(dir)
  if (!manifest) continue
  const seen = new Set<string>([dir])
  for (const name of Object.keys(manifest.dependencies ?? {})) {
    const found = resolve(name, dir)
    if (found) visit(found, app, seen)
  }
}

const sorted = [...entries.values()].sort((a, b) =>
  `${a.name}@${a.version}`.localeCompare(`${b.name}@${b.version}`),
)

const flagged = sorted.filter((entry) => entry.license === 'UNKNOWN' || FLAGGED.test(entry.license))
const counts = new Map<string, number>()
for (const entry of sorted) counts.set(entry.license, (counts.get(entry.license) ?? 0) + 1)

const summary = [...counts.entries()].sort((a, b) => b[1] - a[1])
const out = [
  '# Third-party licences',
  '',
  'Generated by `bun run licenses`. Production dependencies of the companion, extension, mobile and marketing apps. Do not edit by hand.',
  '',
  '## Bundled font',
  '',
  'Amiri is licensed under the SIL Open Font License 1.1; see `tooling/tailwind/fonts/OFL-Amiri.txt`.',
  '',
  '## Summary',
  '',
  `${sorted.length} packages.`,
  '',
  ...summary.map(([license, count]) => `- ${license}: ${count}`),
  '',
  '## Needs review',
  '',
  ...(flagged.length
    ? flagged.map((entry) => `- ${entry.name}@${entry.version}: ${entry.license}`)
    : ['None.']),
  '',
  '## Packages',
  '',
  ...sorted.flatMap((entry) => [
    `### ${entry.name}@${entry.version}`,
    '',
    `Licence: ${entry.license} (${[...entry.apps].sort().join(', ')})`,
    '',
    ...(entry.text
      ? ['```text', entry.text.replaceAll('```', "'''"), '```', '']
      : ['(no licence file shipped)', '']),
  ]),
]

writeFileSync(join(ROOT, 'THIRD_PARTY_LICENSES.md'), `${out.join('\n')}\n`)
console.log(`${sorted.length} packages; ${flagged.length} need review`)
for (const entry of flagged) console.log(`  ${entry.name}@${entry.version}: ${entry.license}`)
