/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AppearanceRouteImport } from './routes/appearance'
import { Route as CalculationRouteImport } from './routes/calculation'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as HijriRouteImport } from './routes/hijri'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as LocationRouteImport } from './routes/location'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as QadaRouteImport } from './routes/qada'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ItemIdRouteImport } from './routes/item/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppearanceRoute = AppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculationRoute = CalculationRouteImport.update({
  id: '/calculation',
  path: '/calculation',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const HijriRoute = HijriRouteImport.update({
  id: '/hijri',
  path: '/hijri',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const QadaRoute = QadaRouteImport.update({
  id: '/qada',
  path: '/qada',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/appearance': typeof AppearanceRoute
  '/calculation': typeof CalculationRoute
  '/feedback': typeof FeedbackRoute
  '/glossary': typeof GlossaryRoute
  '/hijri': typeof HijriRoute
  '/language': typeof LanguageRoute
  '/location': typeof LocationRoute
  '/notifications': typeof NotificationsRoute
  '/qada': typeof QadaRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/item/$id': typeof ItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/appearance': typeof AppearanceRoute
  '/calculation': typeof CalculationRoute
  '/feedback': typeof FeedbackRoute
  '/glossary': typeof GlossaryRoute
  '/hijri': typeof HijriRoute
  '/language': typeof LanguageRoute
  '/location': typeof LocationRoute
  '/notifications': typeof NotificationsRoute
  '/qada': typeof QadaRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/item/$id': typeof ItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/appearance': typeof AppearanceRoute
  '/calculation': typeof CalculationRoute
  '/feedback': typeof FeedbackRoute
  '/glossary': typeof GlossaryRoute
  '/hijri': typeof HijriRoute
  '/language': typeof LanguageRoute
  '/location': typeof LocationRoute
  '/notifications': typeof NotificationsRoute
  '/qada': typeof QadaRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/item/$id': typeof ItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/appearance'
    | '/calculation'
    | '/feedback'
    | '/glossary'
    | '/hijri'
    | '/language'
    | '/location'
    | '/notifications'
    | '/qada'
    | '/settings'
    | '/today'
    | '/item/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/appearance'
    | '/calculation'
    | '/feedback'
    | '/glossary'
    | '/hijri'
    | '/language'
    | '/location'
    | '/notifications'
    | '/qada'
    | '/settings'
    | '/today'
    | '/item/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/appearance'
    | '/calculation'
    | '/feedback'
    | '/glossary'
    | '/hijri'
    | '/language'
    | '/location'
    | '/notifications'
    | '/qada'
    | '/settings'
    | '/today'
    | '/item/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AppearanceRoute: typeof AppearanceRoute
  CalculationRoute: typeof CalculationRoute
  FeedbackRoute: typeof FeedbackRoute
  GlossaryRoute: typeof GlossaryRoute
  HijriRoute: typeof HijriRoute
  LanguageRoute: typeof LanguageRoute
  LocationRoute: typeof LocationRoute
  NotificationsRoute: typeof NotificationsRoute
  QadaRoute: typeof QadaRoute
  SettingsRoute: typeof SettingsRoute
  TodayRoute: typeof TodayRoute
  ItemIdRoute: typeof ItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appearance': {
      id: '/appearance'
      path: '/appearance'
      fullPath: '/appearance'
      preLoaderRoute: typeof AppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculation': {
      id: '/calculation'
      path: '/calculation'
      fullPath: '/calculation'
      preLoaderRoute: typeof CalculationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hijri': {
      id: '/hijri'
      path: '/hijri'
      fullPath: '/hijri'
      preLoaderRoute: typeof HijriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qada': {
      id: '/qada'
      path: '/qada'
      fullPath: '/qada'
      preLoaderRoute: typeof QadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AppearanceRoute: AppearanceRoute,
  CalculationRoute: CalculationRoute,
  FeedbackRoute: FeedbackRoute,
  GlossaryRoute: GlossaryRoute,
  HijriRoute: HijriRoute,
  LanguageRoute: LanguageRoute,
  LocationRoute: LocationRoute,
  NotificationsRoute: NotificationsRoute,
  QadaRoute: QadaRoute,
  SettingsRoute: SettingsRoute,
  TodayRoute: TodayRoute,
  ItemIdRoute: ItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
