/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R404RouteImport } from './routes/404'
import { Route as Char123LangChar125RouteRouteImport } from './routes/{-$lang}/route'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}/index'
import { Route as Char123LangChar125LegalDeleteAccountRouteImport } from './routes/{-$lang}/legal/delete-account'
import { Route as Char123LangChar125LegalPrivacyRouteImport } from './routes/{-$lang}/legal/privacy'
import { Route as Char123LangChar125LegalTermsRouteImport } from './routes/{-$lang}/legal/terms'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125RouteRoute = Char123LangChar125RouteRouteImport.update({
  id: '/{-$lang}',
  path: '/{-$lang}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Char123LangChar125RouteRoute,
} as any)
const Char123LangChar125LegalDeleteAccountRoute =
  Char123LangChar125LegalDeleteAccountRouteImport.update({
    id: '/legal/delete-account',
    path: '/legal/delete-account',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125LegalPrivacyRoute =
  Char123LangChar125LegalPrivacyRouteImport.update({
    id: '/legal/privacy',
    path: '/legal/privacy',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125LegalTermsRoute =
  Char123LangChar125LegalTermsRouteImport.update({
    id: '/legal/terms',
    path: '/legal/terms',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$lang}': typeof Char123LangChar125RouteRouteWithChildren
  '/404': typeof R404Route
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/legal/delete-account': typeof Char123LangChar125LegalDeleteAccountRoute
  '/{-$lang}/legal/privacy': typeof Char123LangChar125LegalPrivacyRoute
  '/{-$lang}/legal/terms': typeof Char123LangChar125LegalTermsRoute
}
export interface FileRoutesByTo {
  '/404': typeof R404Route
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/{-$lang}/legal/delete-account': typeof Char123LangChar125LegalDeleteAccountRoute
  '/{-$lang}/legal/privacy': typeof Char123LangChar125LegalPrivacyRoute
  '/{-$lang}/legal/terms': typeof Char123LangChar125LegalTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$lang}': typeof Char123LangChar125RouteRouteWithChildren
  '/404': typeof R404Route
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/legal/delete-account': typeof Char123LangChar125LegalDeleteAccountRoute
  '/{-$lang}/legal/privacy': typeof Char123LangChar125LegalPrivacyRoute
  '/{-$lang}/legal/terms': typeof Char123LangChar125LegalTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$lang}'
    | '/404'
    | '/{-$lang}/'
    | '/{-$lang}/legal/delete-account'
    | '/{-$lang}/legal/privacy'
    | '/{-$lang}/legal/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/404'
    | '/{-$lang}'
    | '/{-$lang}/legal/delete-account'
    | '/{-$lang}/legal/privacy'
    | '/{-$lang}/legal/terms'
  id:
    | '__root__'
    | '/{-$lang}'
    | '/404'
    | '/{-$lang}/'
    | '/{-$lang}/legal/delete-account'
    | '/{-$lang}/legal/privacy'
    | '/{-$lang}/legal/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LangChar125RouteRoute: typeof Char123LangChar125RouteRouteWithChildren
  R404Route: typeof R404Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}': {
      id: '/{-$lang}'
      path: '/{-$lang}'
      fullPath: '/{-$lang}'
      preLoaderRoute: typeof Char123LangChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/legal/delete-account': {
      id: '/{-$lang}/legal/delete-account'
      path: '/legal/delete-account'
      fullPath: '/{-$lang}/legal/delete-account'
      preLoaderRoute: typeof Char123LangChar125LegalDeleteAccountRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/legal/privacy': {
      id: '/{-$lang}/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/{-$lang}/legal/privacy'
      preLoaderRoute: typeof Char123LangChar125LegalPrivacyRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/legal/terms': {
      id: '/{-$lang}/legal/terms'
      path: '/legal/terms'
      fullPath: '/{-$lang}/legal/terms'
      preLoaderRoute: typeof Char123LangChar125LegalTermsRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
  }
}

interface Char123LangChar125RouteRouteChildren {
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
  Char123LangChar125LegalDeleteAccountRoute: typeof Char123LangChar125LegalDeleteAccountRoute
  Char123LangChar125LegalPrivacyRoute: typeof Char123LangChar125LegalPrivacyRoute
  Char123LangChar125LegalTermsRoute: typeof Char123LangChar125LegalTermsRoute
}

const Char123LangChar125RouteRouteChildren: Char123LangChar125RouteRouteChildren =
  {
    Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
    Char123LangChar125LegalDeleteAccountRoute:
      Char123LangChar125LegalDeleteAccountRoute,
    Char123LangChar125LegalPrivacyRoute: Char123LangChar125LegalPrivacyRoute,
    Char123LangChar125LegalTermsRoute: Char123LangChar125LegalTermsRoute,
  }

const Char123LangChar125RouteRouteWithChildren =
  Char123LangChar125RouteRoute._addFileChildren(
    Char123LangChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LangChar125RouteRoute: Char123LangChar125RouteRouteWithChildren,
  R404Route: R404Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
